/*********************************************************
 **
 ** File  aol_symbology_layer.h
 **
 ** Specification File:  D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_es2\PrimaryFlightDisplay.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:54:53
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_es2\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_es2\PrimaryFlightDisplay.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_es2\PrimaryFlightDisplay.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_es2\PrimaryFlightDisplay.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_es2\PrimaryFlightDisplay.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_es2\PrimaryFlightDisplay.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_es2\PrimaryFlightDisplay.sgfx
 *********************************************************/

#ifndef AOL_SYMBOLOGY_LAYER_H
#define AOL_SYMBOLOGY_LAYER_H

#include "sgl_types.h"


/* Accessors */
#ifndef aol_symbology_layer_G_PN_AIRSPEED
#define aol_symbology_layer_G_PN_AIRSPEED(_C_) (_C_)->PN_AIRSPEED
#define aol_symbology_layer_S_PN_AIRSPEED(_C_,_V_) (_C_)->PN_AIRSPEED = (_V_)
#endif /* aol_symbology_layer_G_PN_AIRSPEED */
#ifndef aol_symbology_layer_G_PN_ALTI
#define aol_symbology_layer_G_PN_ALTI(_C_) (_C_)->PN_ALTI
#define aol_symbology_layer_S_PN_ALTI(_C_,_V_) (_C_)->PN_ALTI = (_V_)
#endif /* aol_symbology_layer_G_PN_ALTI */
#ifndef aol_symbology_layer_G_PN_PITCH_ANGLE
#define aol_symbology_layer_G_PN_PITCH_ANGLE(_C_) (_C_)->PN_PITCH_ANGLE
#define aol_symbology_layer_S_PN_PITCH_ANGLE(_C_,_V_) (_C_)->PN_PITCH_ANGLE = (_V_)
#endif /* aol_symbology_layer_G_PN_PITCH_ANGLE */
#ifndef aol_symbology_layer_G_PN_ROLL_ANGLE
#define aol_symbology_layer_G_PN_ROLL_ANGLE(_C_) (_C_)->PN_ROLL_ANGLE
#define aol_symbology_layer_S_PN_ROLL_ANGLE(_C_,_V_) (_C_)->PN_ROLL_ANGLE = (_V_)
#endif /* aol_symbology_layer_G_PN_ROLL_ANGLE */

/* Context type */
typedef struct aol_typ_symbology_layer_ {
  /* ------------------------- inputs --------------------------- */
  SGLfloat PN_AIRSPEED;
  SGLfloat PN_ALTI;
  SGLfloat PN_PITCH_ANGLE;
  SGLfloat PN_ROLL_ANGLE;
} aol_typ_symbology_layer;

/* Associated functions */
extern void aol_symbology_layer_init(aol_typ_symbology_layer *pContext);
extern void aol_symbology_layer_predraw(aol_typ_symbology_layer *pContext);
extern void aol_symbology_layer_draw(aol_typ_symbology_layer *pContext, SGLint32 pPriority);

#endif /* AOL_SYMBOLOGY_LAYER_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:54:53
 *********************************************************/

