/*********************************************************
 **
 ** File  aol_line_width_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:53:13
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sgfx
 *********************************************************/

#include "aol_line_width_table.h"

/* Line width table definition */
const sgl_line_width aol_line_width_table[aol_line_width_table_size] = 
{
{ 2.4F,             1.5F,             3.5F             }, /* 0 : Line width 2 */
{ 2.55F,            1.65F,            3.65F            }, /* 1 : Line width 3 */
{ 2.75F,            2.25F,            4.25F            }, /* 2 : Line width 4 */
{ 3.55F,            2.55F,            4.55F            }, /* 3 : Line width 5 */
{ 4.55F,            3.55F,            5.55F            }, /* 4 : Line width 6 */
{ 5.55F,            4.25F,            6.25F            }, /* 5 : Line width 7 */
{ 6.55F,            5.F,              7.F              }, /* 6 : Line width 8 */
{ 1.5F,             1.5F,             3.5F             }  /* 7 : Line width 1 */
};

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:53:13
 *********************************************************/

