/*********************************************************
 **
 ** File  aol_symbology_layer.c
 **
 ** Specification File:  D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:53:12
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sgfx
 *********************************************************/

#include "aol_symbology_layer.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_symbology_layer_init(aol_typ_symbology_layer *pContext)
{
  aol_symbology_layer_S_CircAngle(pContext, 0.0F);
  aol_symbology_layer_S_CircInside(pContext, SGL_FALSE);
  aol_symbology_layer_S_CircPercent(pContext, 0.0F);
  aol_symbology_layer_S_RectHeightPercent(pContext, 0.0F);
  aol_symbology_layer_S_RectInside(pContext, SGL_FALSE);
  aol_symbology_layer_S_RectWidthPercent(pContext, 0.0F);
  aol_symbology_layer_S_ShapeInside(pContext, SGL_FALSE);
  aol_symbology_layer_S_Click(pContext, SGL_FALSE);
  aol_symbology_layer_S_Pressed(pContext, SGL_FALSE);
  aol_symbology_layer_S_locMaskIndex(pContext, 0L);
  aol_symbology_layer_S_locVisiShapes(pContext, SGL_TRUE);
  aol_symbology_layer_S_locSmoothMode(pContext, SGL_TRUE);
  aol_symbology_layer_S_locPushedRendering(pContext, SGL_FALSE);
  aol_symbology_layer_S_locPushedTF(pContext, SGL_FALSE);
  aol_symbology_layer_S_locPushedMask(pContext, SGL_FALSE);

}

void aol_symbology_layer_predraw(aol_typ_symbology_layer *pContext)
{

}

/* indexes declaration for static sequences */
static SGLuint32 aol_symbology_layer_stc0 = 0UL;
static SGLuint32 aol_symbology_layer_stc1 = 0UL;
static SGLuint32 aol_symbology_layer_stc2 = 0UL;
static SGLuint32 aol_symbology_layer_stc3 = 0UL;

void aol_symbology_layer_static_sequences(void)
{
  /* Static sequence for Object: texturedGroup, Type: container, OID: 7fa4fd2b-eeb0-4fc2-b4ae-62ce5386c11f */
  aol_symbology_layer_stc0 = sglBeginStaticSequence(-459.0F, -46.042583F, 316.0F, 371.0F);

  /* Object: arc, Type: arc, OID: 6f9ae833-61b9-48cf-b63f-53876eb32ae3 */
  {
    sglDisable(SGL_MODULATE);
    /* texture object part */
    sglBindTexture(SGL_TEXTURE_2D, 5L);
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = -423.911F;
      lY[0UL] = 187.089F;
      lX[1UL] = -334.089F;
      lY[1UL] = 276.911F;
      sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    sglEnable(SGL_TEXTURE_2D);
    sglDisable(SGL_GRADIENT);
    /* fill object part */
    sgluArcSector2f(-379.0F, 232.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_FILLED);
    /* outline object part */
    sglIndexColori(16L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(0L);
    sglIndexLineStipplei(0L);
    sglEnable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sgluArcSector2f(-379.0F, 232.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_CIRCLE_LINE);
  }

  /* Object: circle_1, Type: circle, OID: 75f49a6f-df3c-424f-bda1-04ac98ca8912 */
  {
    /* texture object part */
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = -433.235F;
      lY[0UL] = 64.765F;
      lX[1UL] = -326.765F;
      lY[1UL] = 171.235F;
      sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    /* fill object part */
    sgluArcSector2f(-380.0F, 118.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
    /* outline object part */
    sgluArcSector2f(-380.0F, 118.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_CIRCLE_LINE);
  }

  /* Object: line, Type: line, OID: 1bfbf57b-6a2a-4e25-979e-b74a35ea6381 */
  {
    /* outline object part */
    sglBegin(SGL_LINE_STRIP);
    sglVertex2f(-453.0F, 343.0F);
    sglVertex2f(-406.0F, 365.0F);
    sglVertex2f(-334.0F, 341.0F);
    sglVertex2f(-296.0F, 303.0F);
    sglEnd();
  }

  /* Object: crown, Type: crown, OID: 0c1ea3c2-82e7-49c6-9fbd-8cb54a204f2e */
  {
    /* texture object part */
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = -419.044F;
      lY[0UL] = -38.044F;
      lX[1UL] = -328.956F;
      lY[1UL] = 52.044F;
      sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    /* fill object part */
    sgluCrown2f(-374.0F, 7.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_FILLED);
    /* outline object part */
    sgluCrown2f(-374.0F, 7.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_OUTLINE);
  }

  /* Object: rightGroup, Type: container, OID: df75d961-2b0d-43e6-8ec0-d242dddcc205 */
  {
    sglPushMatrixAndTranslate(-76.0F, -2.0F);

    /* Object: shape_1, Type: shape, OID: 1a2aea15-a605-42a8-8f74-a1e2460cef58 */
    {
      /* texture object part */
      {
        SGLfloat lX[4UL];
        SGLfloat lY[4UL];
        lX[0UL] = 17.0F;
        lY[0UL] = 296.0F;
        lX[1UL] = 147.0F;
        lY[1UL] = 296.0F;
        lX[2UL] = 147.0F;
        lY[2UL] = 356.0F;
        lX[3UL] = 17.0F;
        lY[3UL] = 356.0F;
        sglFormatTexture(4UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
      }
      /* fill object part */
      sglDisable(SGL_TESSELLATION);
      sglBegin(SGL_POLYGON);
      sglTexVertex4f(17.0F, 296.0F, 0.0F, 1.0F);
      sglTexVertex4f(147.0F, 296.0F, 0.0F, 0.0F);
      sglTexVertex4f(147.0F, 356.0F, 1.0F, 0.0F);
      sglTexVertex4f(17.0F, 356.0F, 1.0F, 1.0F);
      sglEnd();
      /* outline object part */
      sglBegin(SGL_LINE_LOOP);
      sglVertex2f(17.0F, 296.0F);
      sglVertex2f(147.0F, 296.0F);
      sglVertex2f(147.0F, 356.0F);
      sglVertex2f(17.0F, 356.0F);
      sglEnd();
    }

    /* Object: shape_2, Type: shape, OID: 7d4e06fa-3fe6-4e10-973e-e131f88df7b6 */
    {
      /* texture object part */
      {
        SGLfloat lX[5UL];
        SGLfloat lY[5UL];
        lX[0UL] = -27.0F;
        lY[0UL] = 156.0F;
        lX[1UL] = 57.0F;
        lY[1UL] = 221.0F;
        lX[2UL] = 129.0F;
        lY[2UL] = 228.0F;
        lX[3UL] = 174.0F;
        lY[3UL] = 158.0F;
        lX[4UL] = 87.0F;
        lY[4UL] = 64.0F;
        sglFormatTexture(5UL, lX, lY, 2.0F, 2.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
      }
      /* fill object part */
      sglBegin(SGL_POLYGON);
      sglVertex2f(-27.0F, 156.0F);
      sglVertex2f(57.0F, 221.0F);
      sglVertex2f(129.0F, 228.0F);
      sglVertex2f(174.0F, 158.0F);
      sglVertex2f(87.0F, 64.0F);
      sglEnd();
      /* outline object part */
      sglBegin(SGL_LINE_LOOP);
      sglVertex2f(-27.0F, 156.0F);
      sglVertex2f(57.0F, 221.0F);
      sglVertex2f(129.0F, 228.0F);
      sglVertex2f(174.0F, 158.0F);
      sglVertex2f(87.0F, 64.0F);
      sglEnd();
    }

    /* Object: rectangle_5, Type: rectangle, OID: f93fb56b-b7f0-4dbb-850b-47de860ed725 */
    {
      /* texture object part */
      sglBindTexture(SGL_TEXTURE_2D, 1L);
      {
        SGLfloat lX[2UL];
        SGLfloat lY[2UL];
        lX[0UL] = 179.0F;
        lY[0UL] = 297.0F;
        lX[1UL] = 309.0F;
        lY[1UL] = 357.0F;
        sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
      }
      /* fill object part */
      sglBegin(SGL_POLYGON);
      sglVertex2f(179.0F, 297.0F);
      sglVertex2f(309.0F, 297.0F);
      sglVertex2f(309.0F, 357.0F);
      sglVertex2f(179.0F, 357.0F);
      sglEnd();
    }

    /* Object: shapeModulate, Type: shape, OID: 9a439eb7-27ab-4974-92b7-20f098fb41a5 */
    {
      /* color object part */
      sglEnable(SGL_MODULATE);
      sglDisable(SGL_POLYGON_SMOOTH);
      /* texture object part */
      sglBindTexture(SGL_TEXTURE_2D, 0L);
      {
        SGLfloat lX[8UL];
        SGLfloat lY[8UL];
        lX[0UL] = 185.0F;
        lY[0UL] = 155.0F;
        sglGetArcSegmentBounds(SGL_TRUE, 53.397F, 185.0F, 155.0F, 341.0F, 227.0F, &(lX[1UL]), &(lY[1UL]), &(lX[2UL]), &(lY[2UL]));
        lX[3UL] = 341.0F;
        lY[3UL] = 227.0F;
        lX[4UL] = 386.0F;
        lY[4UL] = 157.0F;
        lX[5UL] = 299.0F;
        lY[5UL] = 63.0F;
        sglGetArcSegmentBounds(SGL_TRUE, 37.302F, 299.0F, 63.0F, 185.0F, 155.0F, &(lX[6UL]), &(lY[6UL]), &(lX[7UL]), &(lY[7UL]));
        sglFormatTexture(8UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
      }
      /* fill object part */
      sglBegin(SGL_POLYGON);
      sglVertex2f(185.0F, 155.0F);
      sgluArcSegment(SGL_TRUE, 53.397F);
      sglVertex2f(341.0F, 227.0F);
      sglVertex2f(386.0F, 157.0F);
      sglVertex2f(299.0F, 63.0F);
      sgluArcSegment(SGL_TRUE, 37.302F);
      sglEnd();
    }
    sglPopMatrixAndTranslate();
  }

  /* Object: line_1, Type: line, OID: a715c1d3-a838-479f-ad3a-88af8000144a */
  {
    /* outline object part */
    sglIndexLineStipplei(1L);
    sglBegin(SGL_LINE_STRIP);
    sglVertex2f(-260.0F, 336.0F);
    sglVertex2f(-213.0F, 358.0F);
    sglVertex2f(-141.0F, 334.0F);
    sglVertex2f(-103.0F, 296.0F);
    sglEnd();
  }

  /* Object: arc_1, Type: arc, OID: 043f9557-245a-46a3-8edd-385cf66ff43a */
  {
    sglDisable(SGL_MODULATE);
    /* texture object part */
    sglBindTexture(SGL_TEXTURE_2D, 2L);
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = -260.911F;
      lY[0UL] = 190.089F;
      lX[1UL] = -171.089F;
      lY[1UL] = 279.911F;
      sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    /* fill object part */
    sgluArcSector2f(-216.0F, 235.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_FILLED);
  }

  /* Object: circle_2, Type: circle, OID: 902c3a86-6d1c-4722-9f29-e441b1c060c0 */
  {
    /* texture object part */
    sglBindTexture(SGL_TEXTURE_2D, 1L);
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = -267.235F;
      lY[0UL] = 63.765F;
      lX[1UL] = -160.765F;
      lY[1UL] = 170.235F;
      sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    /* fill object part */
    sgluArcSector2f(-214.0F, 117.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
  }

  /* Object: crown_textured_repeat, Type: crown, OID: b98dd0e3-d9fb-4499-af5e-75ca09f55eca */
  {
    /* texture object part */
    sglBindTexture(SGL_TEXTURE_2D, 5L);
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = -259.044F;
      lY[0UL] = -40.044F;
      lX[1UL] = -168.956F;
      lY[1UL] = 50.044F;
      sglFormatTexture(2UL, lX, lY, 3.0F, 3.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    /* fill object part */
    sgluCrown2f(-214.0F, 5.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_FILLED);
  }

  /* Object: circle_3, Type: circle, OID: 3ca565c8-2d9a-4fc9-8e85-ca7eeb3f7ba3 */
  {
    /* color object part */
    sglIndexColori(11L);
    sglEnable(SGL_MODULATE);
    sglEnable(SGL_POLYGON_SMOOTH);
    /* texture object part */
    sglBindTexture(SGL_TEXTURE_2D, 4L);
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = -163.0F;
      lY[0UL] = 165.0F;
      lX[1UL] = -103.0F;
      lY[1UL] = 225.0F;
      sglFormatTexture(2UL, lX, lY, 0.95F, 0.95F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    /* fill object part */
    sgluArcSector2f(-133.0F, 195.0F, 30.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
  }

  /* Object: line_2, Type: line, OID: 3741cebb-b144-41d9-9c94-fab28661413f */
  {
    /* outline object part */
    sglIndexColori(16L);
    sglIndexLineWidthi(6L);
    sglIndexLineStipplei(0L);
    sglSetLineCaps(SGL_STRAIGHT_CAPS);
    sglBegin(SGL_LINE_STRIP);
    sglVertex2f(-453.0F, 335.0F);
    sglVertex2f(-406.0F, 357.0F);
    sgluArcSegment(SGL_FALSE, 80.545F);
    sglVertex2f(-334.0F, 333.0F);
    sglVertex2f(-296.0F, 295.0F);
    sglEnd();
  }

  /* Object: line_3, Type: line, OID: 07983846-7b2d-4005-8397-51cd04ba1456 */
  {
    /* outline object part */
    sglIndexLineStipplei(4L);
    sglBegin(SGL_LINE_STRIP);
    sglVertex2f(-260.0F, 324.0F);
    sglVertex2f(-213.0F, 346.0F);
    sgluArcSegment(SGL_FALSE, 80.545F);
    sglVertex2f(-141.0F, 322.0F);
    sglVertex2f(-103.0F, 284.0F);
    sglEnd();
  }

  /* Object: ellipse, Type: ellipse, OID: a4732726-06ee-4628-a069-a134a936a392 */
  {
    sglDisable(SGL_MODULATE);
    /* texture object part */
    sglBindTexture(SGL_TEXTURE_2D, 5L);
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = -48.0F;
      lY[0UL] = 235.0F;
      lX[1UL] = 40.0F;
      lY[1UL] = 277.0F;
      sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    /* fill object part */
    sgluArcEllipse2f(-4.0F, 256.0F, 44.0F, 21.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_FILLED);
  }

  /* Object: ellipse_1, Type: ellipse, OID: f4780d06-e733-42b6-996c-a3e039692259 */
  {
    /* texture object part */
    {
      SGLfloat lX[2UL];
      SGLfloat lY[2UL];
      lX[0UL] = 98.0F;
      lY[0UL] = 184.0F;
      lX[1UL] = 132.0F;
      lY[1UL] = 280.0F;
      sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    }
    /* fill object part */
    sgluArcEllipse2f(115.0F, 232.0F, 17.0F, 48.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_FILLED);
    /* outline object part */
    sglIndexColori(37L);
    sglIndexLineWidthi(1L);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sgluArcEllipse2f(115.0F, 232.0F, 17.0F, 48.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_OUTLINE);
  }
  sglEndStaticSequence();
  /* Static sequence for Object: coloredGroup, Type: container, OID: e357515a-2000-4bea-b6b6-ab34ec27097e */
  aol_symbology_layer_stc1 = sglBeginStaticSequence(-459.0F, -46.042583F, 316.0F, 371.0F);

  /* Object: arc_4, Type: arc, OID: d05b01e2-6c17-4a28-9dd5-158f70517144 */
  {
    /* color object part */
    sglIndexColori(6L);
    sglDisable(SGL_MODULATE);
    sglEnable(SGL_POLYGON_SMOOTH);
    sglTransparency8(255L);
    sglDisable(SGL_TEXTURE_2D);
    sglDisable(SGL_GRADIENT);
    /* fill object part */
    sgluArcSector2f(-379.0F, 232.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_FILLED);
    /* outline object part */
    sglIndexColori(16L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(0L);
    sglIndexLineStipplei(0L);
    sglEnable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sgluArcSector2f(-379.0F, 232.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_CIRCLE_LINE);
  }

  /* Object: circle_7, Type: circle, OID: 593e111b-bfd1-4764-9717-059ba90c518d */
  {
    /* color object part */
    sglIndexColori(6L);
    /* fill object part */
    sgluArcSector2f(-380.0F, 118.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
    /* outline object part */
    sglIndexColori(16L);
    sgluArcSector2f(-380.0F, 118.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_CIRCLE_LINE);
  }

  /* Object: line_8, Type: line, OID: fdbaf612-a3e3-4f03-9301-b5f287439af1 */
  {
    /* outline object part */
    sglBegin(SGL_LINE_STRIP);
    sglVertex2f(-453.0F, 343.0F);
    sglVertex2f(-406.0F, 365.0F);
    sglVertex2f(-334.0F, 341.0F);
    sglVertex2f(-296.0F, 303.0F);
    sglEnd();
  }

  /* Object: crown_2, Type: crown, OID: 0c2a7acf-05d5-446a-af82-c7a407e18782 */
  {
    /* color object part */
    sglIndexColori(6L);
    /* fill object part */
    sgluCrown2f(-374.0F, 7.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_FILLED);
    /* outline object part */
    sglIndexColori(16L);
    sgluCrown2f(-374.0F, 7.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_OUTLINE);
  }

  /* Object: group_3, Type: container, OID: fc8711f8-6426-4f29-80b8-adce173b943a */
  {
    sglPushMatrixAndTranslate(-76.0F, -3.0F);

    /* Object: rectangle_9, Type: rectangle, OID: 2ed1e629-8e79-492e-942e-17426036df26 */
    {
      /* color object part */
      sglIndexColori(6L);
      /* fill object part */
      sglDisable(SGL_TESSELLATION);
      sglBegin(SGL_POLYGON);
      sglVertex2f(17.0F, 296.0F);
      sglVertex2f(147.0F, 296.0F);
      sglVertex2f(147.0F, 356.0F);
      sglVertex2f(17.0F, 356.0F);
      sglEnd();
      /* outline object part */
      sglIndexColori(16L);
      sglBegin(SGL_LINE_LOOP);
      sglVertex2f(17.0F, 296.0F);
      sglVertex2f(147.0F, 296.0F);
      sglVertex2f(147.0F, 356.0F);
      sglVertex2f(17.0F, 356.0F);
      sglEnd();
    }

    /* Object: shape_5, Type: shape, OID: 3349a3a6-64dc-4a4b-bf19-e4f23dff299e */
    {
      /* color object part */
      sglIndexColori(6L);
      /* fill object part */
      sglBegin(SGL_POLYGON);
      sglVertex2f(-27.0F, 156.0F);
      sglVertex2f(57.0F, 221.0F);
      sglVertex2f(129.0F, 228.0F);
      sglVertex2f(174.0F, 158.0F);
      sglVertex2f(87.0F, 64.0F);
      sglEnd();
      /* outline object part */
      sglIndexColori(16L);
      sglBegin(SGL_LINE_LOOP);
      sglVertex2f(-27.0F, 156.0F);
      sglVertex2f(57.0F, 221.0F);
      sglVertex2f(129.0F, 228.0F);
      sglVertex2f(174.0F, 158.0F);
      sglVertex2f(87.0F, 64.0F);
      sglEnd();
    }

    /* Object: rectangle_10, Type: rectangle, OID: 66f5fb4a-b2a8-441f-ae83-f4247f30524f */
    {
      /* color object part */
      sglIndexColori(11L);
      sglDisable(SGL_POLYGON_SMOOTH);
      /* fill object part */
      sglBegin(SGL_POLYGON);
      sglVertex2f(179.0F, 297.0F);
      sglVertex2f(309.0F, 297.0F);
      sglVertex2f(309.0F, 357.0F);
      sglVertex2f(179.0F, 357.0F);
      sglEnd();
    }

    /* Object: shape_6, Type: shape, OID: 0258bde7-d07e-4b66-8e2a-a0c412d2279b */
    {
      /* color object part */
      sglIndexColori(6L);
      /* fill object part */
      sglBegin(SGL_POLYGON);
      sglVertex2f(185.0F, 155.0F);
      sgluArcSegment(SGL_TRUE, 53.594F);
      sglVertex2f(341.0F, 227.0F);
      sglVertex2f(386.0F, 157.0F);
      sglVertex2f(299.0F, 63.0F);
      sgluArcSegment(SGL_TRUE, 37.302F);
      sglEnd();
    }
    sglPopMatrixAndTranslate();
  }

  /* Object: line_9, Type: line, OID: 5fb36401-e52b-4a72-a097-773058fbe327 */
  {
    /* outline object part */
    sglIndexColori(16L);
    sglIndexLineStipplei(1L);
    sglBegin(SGL_LINE_STRIP);
    sglVertex2f(-260.0F, 336.0F);
    sglVertex2f(-213.0F, 358.0F);
    sglVertex2f(-141.0F, 334.0F);
    sglVertex2f(-103.0F, 296.0F);
    sglEnd();
  }

  /* Object: arc_5, Type: arc, OID: 3a03179f-993a-4f01-8591-f09e4665011a */
  {
    /* color object part */
    sglIndexColori(11L);
    /* fill object part */
    sgluArcSector2f(-216.0F, 235.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_FILLED);
  }

  /* Object: circle_8, Type: circle, OID: 572233af-00af-48ea-ba6a-3897f5e78f2b */
  {
    /* color object part */
    /* fill object part */
    sgluArcSector2f(-214.0F, 117.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
  }

  /* Object: crown_3, Type: crown, OID: aa0021ff-649f-4c85-8a0c-2c50e9c5ca4c */
  {
    /* color object part */
    sglEnable(SGL_POLYGON_SMOOTH);
    /* fill object part */
    sgluCrown2f(-214.0F, 5.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_FILLED);
  }

  /* Object: circle_9, Type: circle, OID: 555e2fb6-6c56-4929-a615-dbea3e20da52 */
  {
    /* color object part */
    sglIndexColori(41L);
    /* fill object part */
    sgluArcSector2f(-133.0F, 195.0F, 30.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
  }

  /* Object: line_10, Type: line, OID: a0c0390e-6f88-4a98-aa6d-4e1127e71b23 */
  {
    /* outline object part */
    sglIndexColori(16L);
    sglIndexLineWidthi(6L);
    sglIndexLineStipplei(0L);
    sglSetLineCaps(SGL_STRAIGHT_CAPS);
    sglBegin(SGL_LINE_STRIP);
    sglVertex2f(-453.0F, 335.0F);
    sglVertex2f(-406.0F, 357.0F);
    sgluArcSegment(SGL_FALSE, 80.545F);
    sglVertex2f(-334.0F, 333.0F);
    sglVertex2f(-296.0F, 295.0F);
    sglEnd();
  }

  /* Object: line_11, Type: line, OID: f6948f3e-c881-41e0-ab56-b0502b2092e2 */
  {
    /* outline object part */
    sglIndexLineStipplei(4L);
    sglBegin(SGL_LINE_STRIP);
    sglVertex2f(-260.0F, 324.0F);
    sglVertex2f(-213.0F, 346.0F);
    sgluArcSegment(SGL_FALSE, 80.545F);
    sglVertex2f(-141.0F, 322.0F);
    sglVertex2f(-103.0F, 284.0F);
    sglEnd();
  }

  /* Object: ellipse_4, Type: ellipse, OID: 58c4771b-e025-43ee-9e69-9275699f77ef */
  {
    /* color object part */
    sglIndexColori(15L);
    /* fill object part */
    sgluArcEllipse2f(-4.0F, 256.0F, 44.0F, 21.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_FILLED);
  }

  /* Object: ellipse_5, Type: ellipse, OID: f3d54f10-58d1-49bc-bb39-ce19cc41b092 */
  {
    /* color object part */
    sglDisable(SGL_POLYGON_SMOOTH);
    /* fill object part */
    sgluArcEllipse2f(115.0F, 232.0F, 17.0F, 48.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_FILLED);
    /* outline object part */
    sglIndexColori(37L);
    sglIndexLineWidthi(1L);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sgluArcEllipse2f(115.0F, 232.0F, 17.0F, 48.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_OUTLINE);
  }
  sglEndStaticSequence();
  /* Static sequence for Object: Text, Type: container, OID: 9793bbab-87cb-4e78-ad96-91cd732a0507 */
  aol_symbology_layer_stc2 = sglBeginStaticSequence(-59.0F, -505.0F, 505.0F, -106.67557F);

  /* Object: rectangle_14, Type: rectangle, OID: f8b77c94-de70-4acd-a767-b310c36635a8 */
  {
    /* color object part */
    sglIndexColori(41L);
    sglDisable(SGL_MODULATE);
    sglEnable(SGL_POLYGON_SMOOTH);
    sglTransparency8(255L);
    sglDisable(SGL_TEXTURE_2D);
    sglDisable(SGL_GRADIENT);
    /* fill object part */
    sglDisable(SGL_TESSELLATION);
    sglBegin(SGL_POLYGON);
    sglVertex2f(-53.0F, -164.0F);
    sglVertex2f(276.0F, -164.0F);
    sglVertex2f(276.0F, -190.0F);
    sglVertex2f(-53.0F, -190.0F);
    sglEnd();
  }

  /* Object: text_14, Type: text, OID: f1dfe7fa-6e12-4783-a797-d7bc1305c66c */
  {
    static SGLuint8 lArray0_text_14[255UL] = {65U,66U,67U,68U,69U,70U,71U,72U,73U,74U,75U,76U,77U,78U,79U,80U,81U,82U,83U,84U,85U,86U,87U,88U,89U,90U};
    sglIndexColori(16L);
    sglIndexHaloColori(-1L);
    sglIndexFontLineWidthi(2L);
    sglIndexFonti(0L);
    sglEnable(SGL_LINE_HALOING);
    sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
    sgluWriteText(-44.0F, -157.0F, lArray0_text_14, 255L);
  }

  /* Object: textMultiline, Type: text, OID: 67e180e4-df11-4658-b76c-cfcda99b5eb9 */
  {
    static SGLint32 lArray0_textMultiline[255UL] = {65L,66L,67L,68L,69L,70L,71L,72L,73L,74L,75L,76L,77L,78L,79L,80L,81L,82L,83L,84L,85L,86L,87L,88L,89L,90L};
    sglIndexFonti(5L);
    sgluWriteUnicodeText(-47.0F, -186.0F, lArray0_textMultiline, 255L);
  }

  /* Object: bi_font_4, Type: bifont, OID: b41b7e70-c69e-46ac-87cb-ed7cfaf202ee */
  {
    sglIndexFonti(2L);
    sglSetSecondFontAttributes(16L, 0L, 2L);
    {
      sgl_numeric_format lFormat;
      lFormat.l_integralPart = 3L;
      lFormat.l_fractionalPart = 3L;
      lFormat.l_secondFontPos = 0L;
      lFormat.b_separator = 46U;
      lFormat.b_leadingZeros = SGL_FALSE;
      lFormat.l_displaySign = SGL_SIGN_NEVER;
      sgluWriteFloat(-42.0F, -128.0F, 12.345F, &lFormat);
    }
  }

  /* Object: bi_font_5, Type: bifont, OID: 5fb28d5a-524a-420b-a7bb-bb4020a180a1 */
  {
    sglIndexFonti(0L);
    sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    sglSetSecondFontAttributes(16L, 2L, 2L);
    {
      sgl_numeric_format lFormat;
      lFormat.l_integralPart = 3L;
      lFormat.l_fractionalPart = 3L;
      lFormat.l_secondFontPos = 0L;
      lFormat.b_separator = 46U;
      lFormat.b_leadingZeros = SGL_TRUE;
      lFormat.l_displaySign = SGL_SIGN_NEVER;
      sgluWriteFloat(81.0F, -121.0F, 67.89F, &lFormat);
    }
  }

  /* Object: rich_text, Type: richText, OID: 44639678-2386-4bfe-895a-25b947bf92f7 */
  {
    static SGLuint8 lArray0_rich_text[255UL] = {27U,78U,32U,77U,89U,32U,27U,65U,36U,82U,73U,67U,72U,32U,27U,65U,46U,84U,69U,88U,84U,32U,27U,79U};
    sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
    sgluWriteRichText(228.0F, -126.0F, lArray0_rich_text, 255L);
  }

  /* Object: rectangle_15, Type: rectangle, OID: 146368d3-5038-4c27-825d-2c202152a93b */
  {
    /* outline object part */
    sglIndexLineWidthi(0L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglBegin(SGL_LINE_LOOP);
    sglVertex2f(247.0F, -499.0F);
    sglVertex2f(393.0F, -499.0F);
    sglVertex2f(393.0F, -375.0F);
    sglVertex2f(247.0F, -375.0F);
    sglEnd();
  }

  /* Object: text_area, Type: textArea, OID: 9e7d3fd9-3af2-42d6-ba07-f0df3829472c */
  {
    static SGLuint8 lArray0_text_area[255UL] = {84U,104U,105U,115U,32U,105U,115U,32U,97U,32U,116U,101U,120U,116U,32U,97U,114U,101U,97U,46U,13U,10U,84U,104U,101U,114U,101U,32U,97U,114U,101U,32U,115U,101U,118U,101U,114U,97U,108U,32U,108U,105U,110U,101U,115U,46U};
    sglIndexFonti(5L);
    sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_TOP);
    sgluWriteTextArea(247.0F, -480.0F, 398.0F, -375.0F, lArray0_text_area, 255L);
  }
  sglEndStaticSequence();
  /* Static sequence for Object: Bitmaps, Type: container, OID: c3206f8c-1d44-4979-a8d0-0607e255220c */
  aol_symbology_layer_stc3 = sglBeginStaticSequence(-503.0F, 162.335F, -340.0F, 303.33502F);

  /* Object: SDYLOGO, Type: bitmap, OID: 3164c19c-df55-43c9-b33d-acb4363ad213 */
  {
    sgluDrawBitmap(6L, -496.0F, 244.335F);
  }

  /* Object: SCADELOGO, Type: bitmap, OID: 9994ce19-dcf5-414c-a1f3-1d3a80a4ee8c */
  {
    sgluDrawBitmap(7L, -497.0F, 168.335F);
  }
  sglEndStaticSequence();
}

void aol_symbology_layer_draw(aol_typ_symbology_layer *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, 0L)) {

    /* Object: symbology_layer, Type: layer, OID: 6da3ee9d-e919-4928-b606-256737b70b29 */
    {
      sglPushMatrixAndTranslate(384.0F, 384.0F);

      /* Object: pointer_event_listener, Type: pointerEvent, OID: 85bba733-1eff-4d49-ad1f-fdda9e10c3ea */
      {
        aol_pointer(0L, &(aol_symbology_layer_G_Pressed(pContext)), &(aol_symbology_layer_G_Click(pContext)), SGL_NULL, SGL_NULL, SGL_NULL, SGL_NULL);
      }

      /* Object: SetRenderMode, Type: importedFunction, OID: a1bac465-3995-4279-a7b9-28e1b869ba06 */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglSetRenderMode(aol_symbology_layer_G_locSmoothMode(pContext));
      }

      /* Object: Interactive, Type: container, OID: e76beac7-6086-408a-9160-6e5567c7f946 */
      {
        sglPushMatrixAndTranslate(117.0F, 6.0F);

        /* Object: rectangle, Type: rectangle, OID: 36ee83e6-bdd7-4b00-b542-24e2dd35c009 */
        {
          /* color object part */
          sglIndexColori(37L);
          sglDisable(SGL_MODULATE);
          sglEnable(SGL_POLYGON_SMOOTH);
          sglTransparency8(125L);
          sglDisable(SGL_TEXTURE_2D);
          sglDisable(SGL_GRADIENT);
          /* fill object part */
          sglDisable(SGL_TESSELLATION);
          sglBegin(SGL_POLYGON);
          sglVertex2f(-507.0F, -70.0F);
          sglVertex2f(111.0F, -70.0F);
          sglVertex2f(111.0F, -382.0F);
          sglVertex2f(-507.0F, -382.0F);
          sglEnd();
        }

        /* Object: InteractiveButtons, Type: container, OID: 59451c3e-b728-4e2c-ac16-019f2f6750f8 */
        {
          sglPushMatrixAndTranslate(2.0F, -218.0F);

          /* Object: InteractiveBox, Type: container, OID: 76b38af7-4e86-4e65-b9ed-040666fcb16d */
          {

            /* Object: rectangle_1, Type: rectangle, OID: 17c76db1-df94-48de-8b80-e15a2df8a960 */
            {
              /* color object part */
              sglIndexColori(23L);
              sglTransparency8(99L);
              /* fill object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-497.0F, 137.0F);
              sglVertex2f(-194.0F, 137.0F);
              sglVertex2f(-194.0F, -159.0F);
              sglVertex2f(-497.0F, -159.0F);
              sglEnd();
              /* outline object part */
              sglIndexColori(41L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(0L);
              sglIndexLineStipplei(0L);
              sglEnable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-497.0F, 137.0F);
              sglVertex2f(-194.0F, 137.0F);
              sglVertex2f(-194.0F, -159.0F);
              sglVertex2f(-497.0F, -159.0F);
              sglEnd();
            }

            /* Object: text, Type: text, OID: 831b2ae4-b37a-498b-bb92-e5eae148176c */
            {
              static SGLuint8 lArray0_text[255UL] = {67U,79U,78U,84U,82U,79U,76U,83U};
              sglIndexColori(1L);
              sglIndexFontLineWidthi(2L);
              sglIndexFonti(0L);
              sglDisable(SGL_LINE_HALOING);
              sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
              sgluWriteText(-405.0F, -150.0F, lArray0_text, 255L);
            }
          }

          /* Object: SmoothRaw, Type: container, OID: 843a7cad-1606-437b-8805-077d2f5fd1b1 */
          {

            /* Object: rectangle_area, Type: rectangleArea, OID: 9e6a504d-890f-4b74-9a7f-0fb6c1e8d311 */
            {
              SGLfloat lX = 0.0F;
              SGLfloat lY = 0.0F;
              aol_locate(-1L, &lX, &lY);
              aol_symbology_layer_G_RectInside(pContext) = sglRectangleActiveAreaGetStatus(lX, lY, -478.0F, 85.0F, -214.0F, 124.0F);
              aol_symbology_layer_G_RectWidthPercent(pContext) = sglRectangleActiveAreaGetWidthRate(lX, lY, -478.0F, 85.0F, -214.0F, 124.0F);
              aol_symbology_layer_G_RectHeightPercent(pContext) = sglRectangleActiveAreaGetHeightRate(lX, lY, -478.0F, 85.0F, -214.0F, 124.0F);
            }

            /* Object: assignment, Type: assignment, OID: 484a3645-c18c-4379-a82b-2f3808da8051 */
            {
              aol_symbology_layer_G_locSmoothMode(pContext) = (SGLbool_and(aol_symbology_layer_G_RectInside(pContext), aol_symbology_layer_G_Click(pContext)) ? SGLbool_not(aol_symbology_layer_G_locSmoothMode(pContext)) : aol_symbology_layer_G_locSmoothMode(pContext));
            }

            /* Object: assignment_1, Type: assignment, OID: c699f047-3602-4578-b845-b4198d309542 */
            {
              aol_symbology_layer_G_locPushedRendering(pContext) = (SGLbool_and(aol_symbology_layer_G_Pressed(pContext), aol_symbology_layer_G_RectInside(pContext)) ? SGL_TRUE : aol_symbology_layer_G_locPushedRendering(pContext));
            }

            /* Object: assignment_2, Type: assignment, OID: 45632eb3-bd10-43c1-a068-657ba48c97d7 */
            {
              aol_symbology_layer_G_locPushedRendering(pContext) = (aol_symbology_layer_G_Click(pContext) ? SGL_FALSE : aol_symbology_layer_G_locPushedRendering(pContext));
            }

            /* Object: ButtonSmoothRaw, Type: container, OID: b448658d-c464-4413-9323-b7ac74762949 */
            {

              /* Object: rectangle_2, Type: rectangle, OID: ada42cbb-c783-4e78-bf92-61d64853a90e */
              {
                /* color object part */
                sglIndexColori((aol_symbology_layer_G_locPushedRendering(pContext) ? 24L : 21L));
                sglTransparency8(255L);
                /* fill object part */
                sglBegin(SGL_POLYGON);
                sglVertex2f(-479.0F, 84.0F);
                sglVertex2f(-215.0F, 84.0F);
                sglVertex2f(-215.0F, 124.0F);
                sglVertex2f(-479.0F, 124.0F);
                sglEnd();
                /* outline object part */
                sglIndexColori(41L);
                sglEnable(SGL_LINE_HALOING);
                sglBegin(SGL_LINE_LOOP);
                sglVertex2f(-479.0F, 84.0F);
                sglVertex2f(-215.0F, 84.0F);
                sglVertex2f(-215.0F, 124.0F);
                sglVertex2f(-479.0F, 124.0F);
                sglEnd();
              }

              /* Object: text_1, Type: text, OID: 75057650-ed51-4e4b-8ca6-eb0b45f9b30e */
              {
                static SGLuint8 lArray0_text_1[255UL] = {67U,72U,65U,78U,71U,69U,32U,82U,69U,78U,68U,69U,82U,73U,78U,71U,32U,77U,79U,68U,69U};
                sgluWriteText(-451.0F, 99.0F, lArray0_text_1, 255L);
              }
            }
          }

          /* Object: TexturedFilled, Type: container, OID: 5b9ec13d-16a9-4b9d-b158-8346faa9ec68 */
          {
            sglPushMatrix();
            sglTranslatef(-114.0F, -6.0F);
            sglScalef(0.7F, 1.0F);

            /* Object: circle_area, Type: circleArea, OID: 80d656a1-0c75-4d3c-a74d-1690a85a41b1 */
            {
              SGLfloat lX = 0.0F;
              SGLfloat lY = 0.0F;
              aol_locate(-1L, &lX, &lY);
              aol_symbology_layer_G_CircInside(pContext) = sglCircleActiveAreaGetStatus(lX, lY, -355.0F, 16.0F, 50.01F);
              aol_symbology_layer_G_CircPercent(pContext) = sglCircleActiveAreaGetRate(lX, lY, -355.0F, 16.0F, 50.01F);
              aol_symbology_layer_G_CircAngle(pContext) = sglCircleActiveAreaGetAngle(lX, lY, -355.0F, 16.0F);
            }

            /* Object: assignment_3, Type: assignment, OID: dcc72937-383e-4d0c-8caa-8a9ff3f94296 */
            {
              aol_symbology_layer_G_locVisiShapes(pContext) = (SGLbool_and(aol_symbology_layer_G_CircInside(pContext), aol_symbology_layer_G_Click(pContext)) ? SGLbool_not(aol_symbology_layer_G_locVisiShapes(pContext)) : aol_symbology_layer_G_locVisiShapes(pContext));
            }

            /* Object: assignment_4, Type: assignment, OID: 476d5558-2be0-494b-9d16-e2150a66b2a2 */
            {
              aol_symbology_layer_G_locPushedTF(pContext) = (SGLbool_and(aol_symbology_layer_G_CircInside(pContext), aol_symbology_layer_G_Pressed(pContext)) ? SGL_TRUE : aol_symbology_layer_G_locPushedTF(pContext));
            }

            /* Object: assignment_5, Type: assignment, OID: 1e3dd679-84a5-499a-aa3c-6dfaf7fe44de */
            {
              aol_symbology_layer_G_locPushedTF(pContext) = (aol_symbology_layer_G_Click(pContext) ? SGL_FALSE : aol_symbology_layer_G_locPushedTF(pContext));
            }

            /* Object: ButtonTexturedFilled, Type: container, OID: cf46af4d-aa50-44c0-ae4e-b7242d77978a */
            {
              sglPushMatrixAndTranslate(-1.0F, -24.0F);

              /* Object: circle, Type: circle, OID: 6fb2e7cb-2e4e-402d-bff3-6b74769ed737 */
              {
                /* color object part */
                sglIndexColori((aol_symbology_layer_G_locPushedTF(pContext) ? 24L : 21L));
                /* fill object part */
                sgluArcSector2f(-354.0F, 39.0F, 50.01F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
                /* outline object part */
                sglIndexColori(41L);
                sgluArcSector2f(-354.0F, 39.0F, 50.01F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_CIRCLE_LINE);
              }

              /* Object: text_2, Type: text, OID: b26d55b4-f915-4b18-a204-c2d081ff3abf */
              {
                static SGLuint8 lArray0_text_2[255UL] = {70U,73U,76U,76U};
                sgluWriteText(-373.0F, 35.0F, lArray0_text_2, 255L);
              }

              /* Object: text_3, Type: text, OID: 40600b16-9d64-4d7d-a4bd-7ec00834c1ad */
              {
                static SGLuint8 lArray0_text_3[255UL] = {67U,72U,65U,78U,71U,69U};
                sgluWriteText(-382.0F, 54.0F, lArray0_text_3, 255L);
              }

              /* Object: text_4, Type: text, OID: b86fd072-afbc-4687-a380-c9843e4c4968 */
              {
                static SGLuint8 lArray0_text_4[255UL] = {77U,79U,68U,69U};
                sgluWriteText(-374.0F, 14.0F, lArray0_text_4, 255L);
              }
              sglPopMatrixAndTranslate();
            }
            sglPopMatrix();
          }

          /* Object: Masks, Type: container, OID: 1799f772-9b7d-4cd9-bb5a-77d54aa2523b */
          {

            /* Object: shape_area, Type: shapeArea, OID: 43004c2f-3557-4a89-832c-1b6bbbde4966 */
            {
              SGLfloat lX = 0.0F;
              SGLfloat lY = 0.0F;
              static SGLfloat lShapeArea[8UL][2UL] = {{-421.0F,-104.0F},{-421.0F,-74.0F},{-391.0F,-57.0F},{-336.0F,-57.0F},{-304.0F,-71.0F},{-304.0F,-104.0F},{-336.0F,-118.0F},{-394.0F,-118.0F}};
              aol_locate(-1L, &lX, &lY);
              aol_symbology_layer_G_ShapeInside(pContext) = sglShapeActiveAreaGetStatus(lX, lY, 8UL, lShapeArea);
            }

            /* Object: assignment_6, Type: assignment, OID: 773d9f9e-da21-4064-b2d1-f148ccf049d0 */
            {
              aol_symbology_layer_G_locMaskIndex(pContext) = (SGLbool_and(aol_symbology_layer_G_ShapeInside(pContext), aol_symbology_layer_G_Click(pContext)) ? SGLint32_rem(SGLint32_add(aol_symbology_layer_G_locMaskIndex(pContext), 1L), 5L) : aol_symbology_layer_G_locMaskIndex(pContext));
            }

            /* Object: assignment_7, Type: assignment, OID: e09be995-4f3d-445b-b680-4c688f5d582c */
            {
              aol_symbology_layer_G_locPushedMask(pContext) = (SGLbool_and(aol_symbology_layer_G_ShapeInside(pContext), aol_symbology_layer_G_Pressed(pContext)) ? SGL_TRUE : aol_symbology_layer_G_locPushedMask(pContext));
            }

            /* Object: assignment_8, Type: assignment, OID: 5a4685da-b61f-4c6c-9fb4-38872fdd87fc */
            {
              aol_symbology_layer_G_locPushedMask(pContext) = (aol_symbology_layer_G_Click(pContext) ? SGL_FALSE : aol_symbology_layer_G_locPushedMask(pContext));
            }

            /* Object: ButtonMask, Type: container, OID: 6944aa53-165a-45f9-a1b9-c0decf97ce60 */
            {
              sglPushMatrixAndTranslate(58.0F, -49.0F);

              /* Object: shape, Type: shape, OID: 709863b8-b2f1-4c88-89f6-3a3f2c45d211 */
              {
                /* color object part */
                sglIndexColori((aol_symbology_layer_G_locPushedMask(pContext) ? 24L : 21L));
                /* fill object part */
                sglBegin(SGL_POLYGON);
                sglVertex2f(-479.0F, -55.0F);
                sglVertex2f(-479.0F, -25.0F);
                sglVertex2f(-449.0F, -8.0F);
                sglVertex2f(-394.0F, -8.0F);
                sglVertex2f(-362.0F, -22.0F);
                sglVertex2f(-362.0F, -55.0F);
                sglVertex2f(-394.0F, -69.0F);
                sglVertex2f(-452.0F, -69.0F);
                sglEnd();
                /* outline object part */
                sglIndexColori(41L);
                sglBegin(SGL_LINE_LOOP);
                sglVertex2f(-479.0F, -55.0F);
                sglVertex2f(-479.0F, -25.0F);
                sglVertex2f(-449.0F, -8.0F);
                sglVertex2f(-394.0F, -8.0F);
                sglVertex2f(-362.0F, -22.0F);
                sglVertex2f(-362.0F, -55.0F);
                sglVertex2f(-394.0F, -69.0F);
                sglVertex2f(-452.0F, -69.0F);
                sglEnd();
              }

              /* Object: text_5, Type: text, OID: 89a2daa9-b6e6-4204-9927-fca431b72ed0 */
              {
                static SGLuint8 lArray0_text_5[255UL] = {67U,72U,65U,78U,71U,69U,32U,77U,65U,83U,75U};
                sgluWriteText(-477.0F, -44.0F, lArray0_text_5, 255L);
              }
              sglPopMatrixAndTranslate();
            }
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: InteractiveOutputs, Type: container, OID: fa150a50-babd-4720-b99c-da7990a85142 */
        {
          sglPushMatrixAndTranslate(317.0F, -215.0F);

          /* Object: InteractiveBox_1, Type: container, OID: c4e1d765-10ad-414a-a5c3-8ff1a60925ba */
          {
            sglPushMatrixAndTranslate(0.0F, -1.0F);

            /* Object: rectangle_3, Type: rectangle, OID: df80dd4a-3014-46d2-be91-9ac29dab7fbe */
            {
              /* color object part */
              sglIndexColori(23L);
              sglTransparency8(99L);
              /* fill object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-497.0F, 133.0F);
              sglVertex2f(-210.0F, 133.0F);
              sglVertex2f(-210.0F, -161.0F);
              sglVertex2f(-497.0F, -161.0F);
              sglEnd();
              /* outline object part */
              sglIndexColori(41L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-497.0F, 133.0F);
              sglVertex2f(-210.0F, 133.0F);
              sglVertex2f(-210.0F, -161.0F);
              sglVertex2f(-497.0F, -161.0F);
              sglEnd();
            }

            /* Object: MouseOutputs, Type: container, OID: e0e18df5-8f3f-4ae1-afac-e2964cf28541 */
            {
              sglPushMatrixAndTranslate(10.0F, -115.0F);

              /* Object: RectangleOutputs, Type: container, OID: 08483460-00fe-4380-8e51-80500089f476 */
              {
                sglPushMatrixAndTranslate(20.0F, 4.0F);

                /* Object: text_6, Type: text, OID: f5a7997f-65e3-45a8-b321-e6155eb0b46b */
                {
                  static SGLuint8 lArray0_text_6[255UL] = {82U,69U,67U,84U,65U,78U,71U,76U,69U,32U,87U,37U,58U};
                  sgluWriteText(-490.0F, 104.0F, lArray0_text_6, 255L);
                }

                /* Object: text_7, Type: text, OID: 43569ad2-cc8c-461e-8ae5-cb6c96f70da8 */
                {
                  static SGLuint8 lArray0_text_7[255UL] = {82U,69U,67U,84U,65U,78U,71U,76U,69U,32U,72U,37U,58U};
                  sgluWriteText(-490.0F, 86.0F, lArray0_text_7, 255L);
                }

                /* Object: bi_font, Type: bifont, OID: e0657d12-dd57-4aff-a584-782bb0fbd519 */
                {
                  sglSetSecondFontAttributes(41L, 0L, 2L);
                  {
                    sgl_numeric_format lFormat;
                    lFormat.l_integralPart = 3L;
                    lFormat.l_fractionalPart = 0L;
                    lFormat.l_secondFontPos = 1L;
                    lFormat.b_separator = 46U;
                    lFormat.b_leadingZeros = SGL_TRUE;
                    lFormat.l_displaySign = SGL_SIGN_NEVER;
                    sgluWriteFloat(-339.0F, 104.0F, SGLfloat_mul(aol_symbology_layer_G_RectWidthPercent(pContext), 100.0F), &lFormat);
                  }
                }

                /* Object: bi_font_1, Type: bifont, OID: a9dd6da2-5d7d-4d85-8d6e-4d912f2d53ee */
                {
                  sgl_numeric_format lFormat;
                  lFormat.l_integralPart = 3L;
                  lFormat.l_fractionalPart = 0L;
                  lFormat.l_secondFontPos = 1L;
                  lFormat.b_separator = 46U;
                  lFormat.b_leadingZeros = SGL_TRUE;
                  lFormat.l_displaySign = SGL_SIGN_NEVER;
                  sgluWriteFloat(-339.0F, 86.0F, SGLfloat_mul(aol_symbology_layer_G_RectHeightPercent(pContext), 100.0F), &lFormat);
                }

                /* Object: text_8, Type: text, OID: c64b6b9c-60df-4b37-9c15-ade76d3ff4c3 */
                {
                  static SGLuint8 lArray0_text_8[255UL] = {82U,69U,67U,84U,65U,78U,71U,76U,69U};
                  sgluWriteText(-490.0F, 67.0F, lArray0_text_8, 255L);
                }

                /* Object: InOut, Type: conditional, OID: 2d90a09b-a8b1-4f17-af06-9b25741380d4 */
                {
                  sglPushMatrixAndTranslate(-14.107F, 5.0F);
                  switch ((aol_symbology_layer_G_RectInside(pContext) ? 1L : 2L)) {

                  case 1L:

                    /* Object: IN, Type: text, OID: 81fcbbea-7170-41f9-9a7d-066b5e73b1c7 */
                    {
                      static SGLuint8 lArray0_IN[255UL] = {73U,78U};
                      sgluWriteText(-369.0F, 62.0F, lArray0_IN, 255L);
                    }
                    break;

                  case 2L:

                    /* Object: OUT, Type: text, OID: cb3fceaf-7485-4e2f-bec5-9c12241c5567 */
                    {
                      static SGLuint8 lArray0_OUT[255UL] = {79U,85U,84U};
                      sgluWriteText(-367.0F, 62.0F, lArray0_OUT, 255L);
                    }
                    break;

                  default:
                    /* Do nothing */
                    break;
                  }
                  sglPopMatrixAndTranslate();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: CircleOutputs, Type: container, OID: 466405ec-7336-4604-b541-a42a98adada4 */
              {
                sglPushMatrixAndTranslate(3.0F, -64.0F);

                /* Object: text_9, Type: text, OID: a54529b0-05b7-4619-9d34-569917f194c7 */
                {
                  static SGLuint8 lArray0_text_9[255UL] = {67U,73U,82U,67U,76U,69U,37U,58U};
                  sgluWriteText(-473.0F, 113.0F, lArray0_text_9, 255L);
                }

                /* Object: text_10, Type: text, OID: 1370fcc9-d183-476c-9325-a7f9aa365227 */
                {
                  static SGLuint8 lArray0_text_10[255UL] = {65U,78U,71U,76U,69U,58U};
                  sgluWriteText(-473.0F, 95.0F, lArray0_text_10, 255L);
                }

                /* Object: bi_font_2, Type: bifont, OID: d94fe903-3fde-43ce-873b-6b7515821c55 */
                {
                  sgl_numeric_format lFormat;
                  lFormat.l_integralPart = 3L;
                  lFormat.l_fractionalPart = 0L;
                  lFormat.l_secondFontPos = 1L;
                  lFormat.b_separator = 46U;
                  lFormat.b_leadingZeros = SGL_TRUE;
                  lFormat.l_displaySign = SGL_SIGN_NEVER;
                  sgluWriteFloat(-322.0F, 112.0F, aol_symbology_layer_G_CircPercent(pContext), &lFormat);
                }

                /* Object: bi_font_3, Type: bifont, OID: 5d0949bd-d957-4d41-8bc9-ed991f5839d9 */
                {
                  sgl_numeric_format lFormat;
                  lFormat.l_integralPart = 3L;
                  lFormat.l_fractionalPart = 0L;
                  lFormat.l_secondFontPos = 1L;
                  lFormat.b_separator = 46U;
                  lFormat.b_leadingZeros = SGL_TRUE;
                  lFormat.l_displaySign = SGL_SIGN_NEVER;
                  sgluWriteFloat(-322.0F, 95.0F, aol_symbology_layer_G_CircAngle(pContext), &lFormat);
                }

                /* Object: text_11, Type: text, OID: e5bb1d8a-c3f1-4f48-be2c-84a0d2545ea6 */
                {
                  static SGLuint8 lArray0_text_11[255UL] = {67U,73U,82U,67U,76U,69U};
                  sgluWriteText(-473.0F, 77.0F, lArray0_text_11, 255L);
                }

                /* Object: InOut_1, Type: conditional, OID: 156a7541-6257-4968-a7c5-11bd1eb6b429 */
                {
                  sglPushMatrixAndTranslate(3.0F, 15.0F);
                  switch ((aol_symbology_layer_G_CircInside(pContext) ? 1L : 2L)) {

                  case 1L:

                    /* Object: IN_1, Type: text, OID: cdb72934-05e1-4165-b1cb-94bb9be7cdb8 */
                    {
                      static SGLuint8 lArray0_IN_1[255UL] = {73U,78U};
                      sgluWriteText(-369.0F, 62.0F, lArray0_IN_1, 255L);
                    }
                    break;

                  case 2L:

                    /* Object: OUT_1, Type: text, OID: d5b2f844-4c48-4438-af4b-81bae21b8193 */
                    {
                      static SGLuint8 lArray0_OUT_1[255UL] = {79U,85U,84U};
                      sgluWriteText(-367.0F, 62.0F, lArray0_OUT_1, 255L);
                    }
                    break;

                  default:
                    /* Do nothing */
                    break;
                  }
                  sglPopMatrixAndTranslate();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: text_12, Type: text, OID: 6f943036-969c-4c89-a461-ddd0454266e3 */
              {
                static SGLuint8 lArray0_text_12[255UL] = {73U,78U,84U,69U,82U,65U,67U,84U,73U,86U,69U,32U,79U,85U,84U,80U,85U,84U,83U};
                sglIndexColori(1L);
                sglDisable(SGL_LINE_HALOING);
                sgluWriteText(-480.0F, -30.0F, lArray0_text_12, 255L);
              }

              /* Object: rectangle_4, Type: rectangle, OID: 3d5f467f-269b-499c-acf5-4f00e0b3c88a */
              {
                /* outline object part */
                sglIndexColori(41L);
                sglEnable(SGL_LINE_HALOING);
                sglBegin(SGL_LINE_LOOP);
                sglVertex2f(-485.0F, 128.0F);
                sglVertex2f(-266.0F, 128.0F);
                sglVertex2f(-266.0F, -36.0F);
                sglVertex2f(-485.0F, -36.0F);
                sglEnd();
              }

              /* Object: ShapeOutputs, Type: container, OID: a45e21eb-f6a2-478e-97ad-bae840299a28 */
              {

                /* Object: text_13, Type: text, OID: cca16313-3c85-4cb9-a386-dd59f7d1eb8d */
                {
                  static SGLuint8 lArray0_text_13[255UL] = {83U,72U,65U,80U,69U};
                  sgluWriteText(-471.0F, -10.0F, lArray0_text_13, 255L);
                }

                /* Object: InOut_2, Type: conditional, OID: 7d7551f7-26c9-47db-ac4f-160ac6da2a45 */
                {
                  sglPushMatrixAndTranslate(7.0F, -72.0F);
                  switch ((aol_symbology_layer_G_ShapeInside(pContext) ? 1L : 2L)) {

                  case 1L:

                    /* Object: IN_2, Type: text, OID: a40ab36e-9ef8-41a4-bab5-4804ef6a4175 */
                    {
                      static SGLuint8 lArray0_IN_2[255UL] = {73U,78U};
                      sgluWriteText(-369.0F, 62.0F, lArray0_IN_2, 255L);
                    }
                    break;

                  case 2L:

                    /* Object: OUT_2, Type: text, OID: c7db44ea-79c8-4fac-b0a6-e9f0ce320be2 */
                    {
                      static SGLuint8 lArray0_OUT_2[255UL] = {79U,85U,84U};
                      sgluWriteText(-367.0F, 62.0F, lArray0_OUT_2, 255L);
                    }
                    break;

                  default:
                    /* Do nothing */
                    break;
                  }
                  sglPopMatrixAndTranslate();
                }
              }
              sglPopMatrixAndTranslate();
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: TitleRenderingMode, Type: text, OID: 9a904836-6ebd-4b4b-9fc6-8290fb3be288 */
          {
            static SGLuint8 lArray0_TitleRenderingMode[255UL] = {70U,73U,76U,76U,69U,68U,32U,77U,79U,68U,69U,58U,32U};
            sgluWriteText(-490.0F, 78.675F, lArray0_TitleRenderingMode, 255L);
          }

          /* Object: FilledModeGroup, Type: conditional, OID: a3169b97-09dc-4cc7-8ffd-2204888bf507 */
          {
            sglPushMatrixAndTranslate(-10.0F, 0.0F);
            switch ((aol_symbology_layer_G_locVisiShapes(pContext) ? 1L : 2L)) {

            case 1L:

              /* Object: COLORED, Type: text, OID: 947b843a-dfe7-4d5d-938b-d38fca9a6602 */
              {
                static SGLuint8 lArray0_COLORED[255UL] = {67U,79U,76U,79U,82U,69U,68U};
                sgluWriteText(-311.891F, 80.0F, lArray0_COLORED, 255L);
              }
              break;

            case 2L:

              /* Object: TEXTURED, Type: text, OID: 862eebae-2337-4678-aaa1-18f920f57c04 */
              {
                static SGLuint8 lArray0_TEXTURED[255UL] = {84U,69U,88U,84U,85U,82U,69U,68U};
                sgluWriteText(-310.0F, 80.0F, lArray0_TEXTURED, 255L);
              }
              break;

            default:
              /* Do nothing */
              break;
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: TitleFilledMode, Type: text, OID: ae11fdbd-0e20-4c48-9822-47ece8d4b599 */
          {
            static SGLuint8 lArray0_TitleFilledMode[255UL] = {82U,69U,78U,68U,69U,82U,73U,78U,71U,32U,77U,79U,68U,69U,58U};
            sgluWriteText(-490.0F, 110.0F, lArray0_TitleFilledMode, 255L);
          }

          /* Object: RenderingModeGroup, Type: conditional, OID: 5087dee5-43b8-465e-b536-1d0543a2eddc */
          {
            sglPushMatrixAndTranslate(-20.0F, 0.0F);
            switch ((aol_symbology_layer_G_locSmoothMode(pContext) ? 1L : 2L)) {

            case 1L:

              /* Object: SMOOTH, Type: text, OID: d0f67208-46be-4e80-ba47-70f71f7cfb29 */
              {
                static SGLuint8 lArray0_SMOOTH[255UL] = {83U,77U,79U,79U,84U,72U};
                sgluWriteText(-300.0F, 110.0F, lArray0_SMOOTH, 255L);
              }
              break;

            case 2L:

              /* Object: RAW, Type: text, OID: 62b233ba-24f9-45d4-98ed-d91f6c35404d */
              {
                static SGLuint8 lArray0_RAW[255UL] = {82U,65U,87U};
                sgluWriteText(-300.0F, 109.0F, lArray0_RAW, 255L);
              }
              break;

            default:
              /* Do nothing */
              break;
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: TitleMask, Type: text, OID: 8486450b-4b13-4205-b3ec-87c06dc49449 */
          {
            static SGLuint8 lArray0_TitleMask[255UL] = {77U,65U,83U,75U,58U,32U};
            sgluWriteText(-491.134F, 48.675F, lArray0_TitleMask, 255L);
          }

          /* Object: MaskGroup, Type: conditional, OID: fbaea3c5-f3a4-45e3-8733-780994c07bad */
          {
            sglPushMatrixAndTranslate(-9.621F, -30.0F);
            switch (SGLint32_add(aol_symbology_layer_G_locMaskIndex(pContext), 1L)) {

            case 2L:

              /* Object: CLIP_PLANE, Type: text, OID: 999c16c2-b0af-4e7b-81b0-b6c54280918a */
              {
                static SGLuint8 lArray0_CLIP_PLANE[255UL] = {67U,76U,73U,80U,32U,80U,76U,65U,78U,69U};
                sgluWriteText(-310.0F, 80.0F, lArray0_CLIP_PLANE, 255L);
              }
              break;

            case 3L:

              /* Object: CLIP_BOX, Type: text, OID: ad971946-6fb1-4275-95fb-5da6ad6c198a */
              {
                static SGLuint8 lArray0_CLIP_BOX[255UL] = {67U,76U,73U,80U,32U,66U,79U,88U};
                sgluWriteText(-310.0F, 80.0F, lArray0_CLIP_BOX, 255L);
              }
              break;

            case 4L:

              /* Object: STENCIL, Type: text, OID: 919888ad-e46a-46bf-8ec6-b2ce5b6e5e60 */
              {
                static SGLuint8 lArray0_STENCIL[255UL] = {83U,84U,69U,78U,67U,73U,76U};
                sgluWriteText(-310.0F, 80.0F, lArray0_STENCIL, 255L);
              }
              break;

            case 5L:

              /* Object: SCISSOR, Type: text, OID: 2c2b5c0f-fac8-445d-959f-eb43918ac0ed */
              {
                static SGLuint8 lArray0_SCISSOR[255UL] = {83U,67U,73U,83U,83U,79U,82U};
                sgluWriteText(-310.0F, 80.0F, lArray0_SCISSOR, 255L);
              }
              break;

            default:
            /* case 1L */

              /* Object: NONE, Type: text, OID: bb453220-82c5-48f4-948a-aec1604f70e0 */
              {
                static SGLuint8 lArray0_NONE[255UL] = {78U,79U,78U,69U};
                sgluWriteText(-310.0F, 80.0F, lArray0_NONE, 255L);
              }
              break;
            }
            sglPopMatrixAndTranslate();
          }
          sglPopMatrixAndTranslate();
        }
        sglPopMatrixAndTranslate();
      }

      /* Object: TexturedShapes, Type: container, OID: 877222d6-975f-4a73-9268-f9ec669ab4ec */
      {
        SGLuint32 lMask_clip_box = SGL_NO_MASK;
        SGLuint32 lMask_stencil = SGL_NO_MASK;
        if (SGLbool_not(aol_symbology_layer_G_locVisiShapes(pContext))) {
          sglPushMatrixAndTranslate(76.0F, 0.0F);

          /* Object: clip_box, Type: clipBox, OID: b126a81d-7359-431b-a789-8562cb5d577f */
          {
            if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 2L)) {
              lMask_clip_box = sglAllocateMaskID(SGL_TYPE_CLIP_BOX);
              sglClipBox(lMask_clip_box, SGL_VISIBLE_INSIDE, -276.0F, 334.0F, 90.0F, 41.0F);
            }
          }

          /* Object: stencil, Type: stencil, OID: 688f8aaf-6017-4d0b-81df-d6d871fc48b8 */
          {
            if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 3L)) {
              lMask_stencil = sglAllocateMaskID(SGL_TYPE_STENCIL);
              sglBegin(SGLuint32_to_uint8(lMask_stencil));
              sglVertex2f(-402.0F, 96.0F);
              sglVertex2f(-311.0F, 363.0F);
              sglVertex2f(192.0F, 323.0F);
              sglVertex2f(170.0F, 121.0F);
              sglVertex2f(-27.0F, 28.0F);
              sglEnd();
            }
          }

          /* Object: group, Type: container, OID: f21774d7-7aee-4364-bc58-7582fab7d4a5 */
          {
            if (SGLint32_ne(aol_symbology_layer_G_locMaskIndex(pContext), 4L)) {

              /* Object: maskGroup, Type: container, OID: b797604a-6729-4fa9-bc65-7ffbb695f188 */
              {

                /* Object: RectangleClipBox, Type: rectangle, OID: c6f9f00e-e6fd-4a17-8825-17d3ce19c96b */
                {
                  if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 2L)) {
                    sglSetActiveMasks(lMask_clip_box|lMask_stencil);
                    /* outline object part */
                    sglIndexColori(16L);
                    sglTransparency8(255L);
                    sglBegin(SGL_LINE_LOOP);
                    sglVertex2f(-276.0F, 333.0F);
                    sglVertex2f(89.0F, 333.0F);
                    sglVertex2f(89.0F, 41.0F);
                    sglVertex2f(-276.0F, 41.0F);
                    sglEnd();
                  }
                }

                /* Object: shapeStencil, Type: shape, OID: d0e68de8-2b5f-4b54-b231-43d71dd051e2 */
                {
                  if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 3L)) {
                    sglSetActiveMasks(lMask_clip_box|lMask_stencil);
                    /* outline object part */
                    sglIndexColori(16L);
                    sglTransparency8(255L);
                    sglBegin(SGL_LINE_LOOP);
                    sglVertex2f(-311.0F, 363.0F);
                    sglVertex2f(190.0F, 321.0F);
                    sglVertex2f(171.0F, 122.0F);
                    sglVertex2f(-26.0F, 29.0F);
                    sglVertex2f(-400.0F, 96.0F);
                    sglEnd();
                  }
                }
              }

              /* Object: texturedGroup, Type: container, OID: 7fa4fd2b-eeb0-4fc2-b4ae-62ce5386c11f */
              {
                sglSetActiveMasks(lMask_clip_box|lMask_stencil);
                sglCallStaticSequence(aol_symbology_layer_stc0);
              }
            }
          }

          /* Object: panel_group, Type: panel, OID: 62e101aa-2abf-472f-8339-bc3a834c5952 */
          {
            if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 4L)) {
              sglBeginScissor(261.0F, 287.0F);

              /* Object: arc_2, Type: arc, OID: 838acd2f-5c07-408c-9198-8e14bd904d4d */
              {
                sglSetActiveMasks(lMask_clip_box|lMask_stencil);
                sglDisable(SGL_MODULATE);
                /* texture object part */
                sglBindTexture(SGL_TEXTURE_2D, 5L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = -423.911F;
                  lY[0UL] = 187.089F;
                  lX[1UL] = -334.089F;
                  lY[1UL] = 276.911F;
                  sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                sglEnable(SGL_TEXTURE_2D);
                sglDisable(SGL_GRADIENT);
                /* fill object part */
                sgluArcSector2f(-379.0F, 232.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_FILLED);
                /* outline object part */
                sglIndexColori(16L);
                sglIndexHaloColori(-1L);
                sglIndexLineWidthi(0L);
                sglIndexLineStipplei(0L);
                sglEnable(SGL_LINE_HALOING);
                sglSetLineCaps(SGL_ROUNDED_CAPS);
                sglTransparency8(255L);
                sgluArcSector2f(-379.0F, 232.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_CIRCLE_LINE);
              }

              /* Object: circle_4, Type: circle, OID: f8026cf0-1220-4167-8bfb-9c3c7284c004 */
              {
                /* texture object part */
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = -433.235F;
                  lY[0UL] = 64.765F;
                  lX[1UL] = -326.765F;
                  lY[1UL] = 171.235F;
                  sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                /* fill object part */
                sgluArcSector2f(-380.0F, 118.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
                /* outline object part */
                sgluArcSector2f(-380.0F, 118.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_CIRCLE_LINE);
              }

              /* Object: line_4, Type: line, OID: e53b6818-c004-4e3a-9afe-b6330475975c */
              {
                /* outline object part */
                sglBegin(SGL_LINE_STRIP);
                sglVertex2f(-453.0F, 343.0F);
                sglVertex2f(-406.0F, 365.0F);
                sglVertex2f(-334.0F, 341.0F);
                sglVertex2f(-296.0F, 303.0F);
                sglEnd();
              }

              /* Object: crown_1, Type: crown, OID: df291509-6836-4e7b-a630-3e729bdfbd0f */
              {
                /* texture object part */
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = -419.044F;
                  lY[0UL] = -38.044F;
                  lX[1UL] = -328.956F;
                  lY[1UL] = 52.044F;
                  sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                /* fill object part */
                sgluCrown2f(-374.0F, 7.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_FILLED);
                /* outline object part */
                sgluCrown2f(-374.0F, 7.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_OUTLINE);
              }

              /* Object: group_1, Type: container, OID: 0620e69b-d773-4e51-b811-c22e5efe130a */
              {
                sglPushMatrixAndTranslate(-76.0F, -2.0F);

                /* Object: rectangle_6, Type: rectangle, OID: 757a6b05-d88a-4b40-9df6-3725b9ef5b1a */
                {
                  /* texture object part */
                  sglBindTexture(SGL_TEXTURE_2D, 0L);
                  {
                    SGLfloat lX[2UL];
                    SGLfloat lY[2UL];
                    lX[0UL] = 17.0F;
                    lY[0UL] = 296.0F;
                    lX[1UL] = 147.0F;
                    lY[1UL] = 356.0F;
                    sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  }
                  /* fill object part */
                  sglDisable(SGL_TESSELLATION);
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(17.0F, 296.0F);
                  sglVertex2f(147.0F, 296.0F);
                  sglVertex2f(147.0F, 356.0F);
                  sglVertex2f(17.0F, 356.0F);
                  sglEnd();
                  /* outline object part */
                  sglBegin(SGL_LINE_LOOP);
                  sglVertex2f(17.0F, 296.0F);
                  sglVertex2f(147.0F, 296.0F);
                  sglVertex2f(147.0F, 356.0F);
                  sglVertex2f(17.0F, 356.0F);
                  sglEnd();
                }

                /* Object: shape_3, Type: shape, OID: e8f9ae8e-660a-4e06-92af-7bb49772be38 */
                {
                  /* texture object part */
                  sglBindTexture(SGL_TEXTURE_2D, 5L);
                  {
                    SGLfloat lX[5UL];
                    SGLfloat lY[5UL];
                    lX[0UL] = -27.0F;
                    lY[0UL] = 156.0F;
                    lX[1UL] = 57.0F;
                    lY[1UL] = 221.0F;
                    lX[2UL] = 129.0F;
                    lY[2UL] = 228.0F;
                    lX[3UL] = 174.0F;
                    lY[3UL] = 158.0F;
                    lX[4UL] = 87.0F;
                    lY[4UL] = 64.0F;
                    sglFormatTexture(5UL, lX, lY, 2.0F, 2.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  }
                  /* fill object part */
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(-27.0F, 156.0F);
                  sglVertex2f(57.0F, 221.0F);
                  sglVertex2f(129.0F, 228.0F);
                  sglVertex2f(174.0F, 158.0F);
                  sglVertex2f(87.0F, 64.0F);
                  sglEnd();
                  /* outline object part */
                  sglBegin(SGL_LINE_LOOP);
                  sglVertex2f(-27.0F, 156.0F);
                  sglVertex2f(57.0F, 221.0F);
                  sglVertex2f(129.0F, 228.0F);
                  sglVertex2f(174.0F, 158.0F);
                  sglVertex2f(87.0F, 64.0F);
                  sglEnd();
                }

                /* Object: rectangle_7, Type: rectangle, OID: ea82bb4b-cb7a-4c50-aac5-29cea60d9a47 */
                {
                  /* texture object part */
                  sglBindTexture(SGL_TEXTURE_2D, 1L);
                  {
                    SGLfloat lX[2UL];
                    SGLfloat lY[2UL];
                    lX[0UL] = 179.0F;
                    lY[0UL] = 297.0F;
                    lX[1UL] = 309.0F;
                    lY[1UL] = 357.0F;
                    sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  }
                  /* fill object part */
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(179.0F, 297.0F);
                  sglVertex2f(309.0F, 297.0F);
                  sglVertex2f(309.0F, 357.0F);
                  sglVertex2f(179.0F, 357.0F);
                  sglEnd();
                }

                /* Object: shape_4, Type: shape, OID: 2fde10ff-b561-447a-86d3-912825d82e20 */
                {
                  /* color object part */
                  sglEnable(SGL_MODULATE);
                  sglDisable(SGL_POLYGON_SMOOTH);
                  /* texture object part */
                  sglBindTexture(SGL_TEXTURE_2D, 0L);
                  {
                    SGLfloat lX[8UL];
                    SGLfloat lY[8UL];
                    lX[0UL] = 185.0F;
                    lY[0UL] = 155.0F;
                    sglGetArcSegmentBounds(SGL_TRUE, 53.397F, 185.0F, 155.0F, 341.0F, 227.0F, &(lX[1UL]), &(lY[1UL]), &(lX[2UL]), &(lY[2UL]));
                    lX[3UL] = 341.0F;
                    lY[3UL] = 227.0F;
                    lX[4UL] = 386.0F;
                    lY[4UL] = 157.0F;
                    lX[5UL] = 299.0F;
                    lY[5UL] = 63.0F;
                    sglGetArcSegmentBounds(SGL_TRUE, 37.302F, 299.0F, 63.0F, 185.0F, 155.0F, &(lX[6UL]), &(lY[6UL]), &(lX[7UL]), &(lY[7UL]));
                    sglFormatTexture(8UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                  }
                  /* fill object part */
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(185.0F, 155.0F);
                  sgluArcSegment(SGL_TRUE, 53.397F);
                  sglVertex2f(341.0F, 227.0F);
                  sglVertex2f(386.0F, 157.0F);
                  sglVertex2f(299.0F, 63.0F);
                  sgluArcSegment(SGL_TRUE, 37.302F);
                  sglEnd();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: line_5, Type: line, OID: 90fdbb3d-57c2-4802-becd-8ebdc177f9f3 */
              {
                /* outline object part */
                sglIndexLineStipplei(1L);
                sglBegin(SGL_LINE_STRIP);
                sglVertex2f(-260.0F, 336.0F);
                sglVertex2f(-213.0F, 358.0F);
                sglVertex2f(-141.0F, 334.0F);
                sglVertex2f(-103.0F, 296.0F);
                sglEnd();
              }

              /* Object: arc_3, Type: arc, OID: 6c056328-47e7-4bce-8158-09a4aadedf86 */
              {
                sglDisable(SGL_MODULATE);
                /* texture object part */
                sglBindTexture(SGL_TEXTURE_2D, 2L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = -260.911F;
                  lY[0UL] = 190.089F;
                  lX[1UL] = -171.089F;
                  lY[1UL] = 279.911F;
                  sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                /* fill object part */
                sgluArcSector2f(-216.0F, 235.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_FILLED);
              }

              /* Object: circle_5, Type: circle, OID: af4dd9e1-2a7b-4647-a902-97995309483e */
              {
                /* texture object part */
                sglBindTexture(SGL_TEXTURE_2D, 1L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = -267.235F;
                  lY[0UL] = 63.765F;
                  lX[1UL] = -160.765F;
                  lY[1UL] = 170.235F;
                  sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                /* fill object part */
                sgluArcSector2f(-214.0F, 117.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
              }

              /* Object: crown_textured_repeat_1, Type: crown, OID: 3503b48f-a41b-4b17-96e3-3a8ec9ac123b */
              {
                /* texture object part */
                sglBindTexture(SGL_TEXTURE_2D, 5L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = -259.044F;
                  lY[0UL] = -40.044F;
                  lX[1UL] = -168.956F;
                  lY[1UL] = 50.044F;
                  sglFormatTexture(2UL, lX, lY, 3.0F, 3.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                /* fill object part */
                sgluCrown2f(-214.0F, 5.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_FILLED);
              }

              /* Object: circle_6, Type: circle, OID: 3b0deed3-223d-492d-8aa5-b6df4fc42e3b */
              {
                /* texture object part */
                sglBindTexture(SGL_TEXTURE_2D, 4L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = -163.0F;
                  lY[0UL] = 165.0F;
                  lX[1UL] = -103.0F;
                  lY[1UL] = 225.0F;
                  sglFormatTexture(2UL, lX, lY, 0.95F, 0.95F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                /* fill object part */
                sgluArcSector2f(-133.0F, 195.0F, 30.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
              }

              /* Object: line_6, Type: line, OID: a7b5f7fd-8fc6-49e0-aa27-9604d4665975 */
              {
                /* outline object part */
                sglIndexLineWidthi(6L);
                sglIndexLineStipplei(0L);
                sglSetLineCaps(SGL_STRAIGHT_CAPS);
                sglBegin(SGL_LINE_STRIP);
                sglVertex2f(-453.0F, 335.0F);
                sglVertex2f(-406.0F, 357.0F);
                sgluArcSegment(SGL_FALSE, 80.545F);
                sglVertex2f(-334.0F, 333.0F);
                sglVertex2f(-296.0F, 295.0F);
                sglEnd();
              }

              /* Object: line_7, Type: line, OID: 5cee7050-2d77-4764-a6f8-a3bb7e2852ad */
              {
                /* outline object part */
                sglIndexLineStipplei(4L);
                sglBegin(SGL_LINE_STRIP);
                sglVertex2f(-260.0F, 324.0F);
                sglVertex2f(-213.0F, 346.0F);
                sgluArcSegment(SGL_FALSE, 80.545F);
                sglVertex2f(-141.0F, 322.0F);
                sglVertex2f(-103.0F, 284.0F);
                sglEnd();
              }

              /* Object: ellipse_2, Type: ellipse, OID: 2c3b074c-8998-4ba2-8f56-b8e9b54e218a */
              {
                /* texture object part */
                sglBindTexture(SGL_TEXTURE_2D, 5L);
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = -48.0F;
                  lY[0UL] = 235.0F;
                  lX[1UL] = 40.0F;
                  lY[1UL] = 277.0F;
                  sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                /* fill object part */
                sgluArcEllipse2f(-4.0F, 256.0F, 44.0F, 21.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_FILLED);
              }

              /* Object: ellipse_3, Type: ellipse, OID: 013c492a-4246-4061-8f78-2a7c1bef1e09 */
              {
                /* texture object part */
                {
                  SGLfloat lX[2UL];
                  SGLfloat lY[2UL];
                  lX[0UL] = 98.0F;
                  lY[0UL] = 184.0F;
                  lX[1UL] = 132.0F;
                  lY[1UL] = 280.0F;
                  sglFormatTexture(2UL, lX, lY, 1.0F, 1.0F, SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                }
                /* fill object part */
                sgluArcEllipse2f(115.0F, 232.0F, 17.0F, 48.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_FILLED);
                /* outline object part */
                sglIndexColori(37L);
                sglIndexLineWidthi(1L);
                sglSetLineCaps(SGL_ROUNDED_CAPS);
                sgluArcEllipse2f(115.0F, 232.0F, 17.0F, 48.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_OUTLINE);
              }
              sglEndScissor();
            }
          }

          /* Object: rectangle_8, Type: rectangle, OID: bed63d29-2639-4f82-9721-a774d50a75e0 */
          {
            if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 4L)) {
              sglSetActiveMasks(lMask_clip_box|lMask_stencil);
              /* outline object part */
              sglIndexColori(16L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglEnable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(0.0F, 0.0F);
              sglVertex2f(261.0F, 0.0F);
              sglVertex2f(261.0F, 287.0F);
              sglVertex2f(0.0F, 287.0F);
              sglEnd();
            }
          }
          sglFreeMaskID(lMask_clip_box|lMask_stencil);
          sglPopMatrixAndTranslate();
        }
      }

      /* Object: Shapes, Type: container, OID: 4e43c04a-3a93-40a8-9a23-c0f5aa0b929a */
      {
        SGLuint32 lMask_clip_box_1 = SGL_NO_MASK;
        SGLuint32 lMask_stencil_1 = SGL_NO_MASK;
        if (aol_symbology_layer_G_locVisiShapes(pContext)) {
          sglPushMatrixAndTranslate(76.0F, 0.0F);

          /* Object: clip_box_1, Type: clipBox, OID: b126a81d-7359-431b-a789-8562cb5d577f */
          {
            if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 2L)) {
              lMask_clip_box_1 = sglAllocateMaskID(SGL_TYPE_CLIP_BOX);
              sglClipBox(lMask_clip_box_1, SGL_VISIBLE_INSIDE, -276.0F, 334.0F, 90.0F, 41.0F);
            }
          }

          /* Object: stencil_1, Type: stencil, OID: 688f8aaf-6017-4d0b-81df-d6d871fc48b8 */
          {
            if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 3L)) {
              sglDisable(SGL_TESSELLATION);
              lMask_stencil_1 = sglAllocateMaskID(SGL_TYPE_STENCIL);
              sglBegin(SGLuint32_to_uint8(lMask_stencil_1));
              sglVertex2f(-402.0F, 96.0F);
              sglVertex2f(-311.0F, 363.0F);
              sglVertex2f(192.0F, 323.0F);
              sglVertex2f(170.0F, 121.0F);
              sglVertex2f(-27.0F, 28.0F);
              sglEnd();
            }
          }

          /* Object: group_2, Type: container, OID: e40a911a-e038-4068-9ce0-aba0359cd8c3 */
          {
            if (SGLint32_ne(aol_symbology_layer_G_locMaskIndex(pContext), 4L)) {

              /* Object: maskGroup_1, Type: container, OID: 128b21b8-9e17-4be8-b485-471a42f18fcf */
              {

                /* Object: RectangleClipBox_1, Type: rectangle, OID: 2a0791b3-16e7-4abf-a2f3-07b7f7cf1317 */
                {
                  if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 2L)) {
                    sglSetActiveMasks(lMask_clip_box_1|lMask_stencil_1);
                    /* outline object part */
                    sglIndexColori(16L);
                    sglIndexHaloColori(-1L);
                    sglIndexLineWidthi(0L);
                    sglIndexLineStipplei(0L);
                    sglEnable(SGL_LINE_HALOING);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglTransparency8(255L);
                    sglBegin(SGL_LINE_LOOP);
                    sglVertex2f(-274.0F, 332.0F);
                    sglVertex2f(87.0F, 332.0F);
                    sglVertex2f(87.0F, 42.0F);
                    sglVertex2f(-274.0F, 42.0F);
                    sglEnd();
                  }
                }

                /* Object: shapeStencil_1, Type: shape, OID: 16bdda76-73eb-4dbd-ad38-74e937e56131 */
                {
                  if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 3L)) {
                    sglSetActiveMasks(lMask_clip_box_1|lMask_stencil_1);
                    /* outline object part */
                    sglIndexColori(16L);
                    sglIndexHaloColori(-1L);
                    sglIndexLineWidthi(0L);
                    sglIndexLineStipplei(0L);
                    sglEnable(SGL_LINE_HALOING);
                    sglSetLineCaps(SGL_ROUNDED_CAPS);
                    sglTransparency8(255L);
                    sglBegin(SGL_LINE_LOOP);
                    sglVertex2f(-310.0F, 361.0F);
                    sglVertex2f(191.0F, 322.0F);
                    sglVertex2f(167.0F, 119.0F);
                    sglVertex2f(-27.0F, 28.0F);
                    sglVertex2f(-400.0F, 96.0F);
                    sglEnd();
                  }
                }
              }

              /* Object: coloredGroup, Type: container, OID: e357515a-2000-4bea-b6b6-ab34ec27097e */
              {
                sglSetActiveMasks(lMask_clip_box_1|lMask_stencil_1);
                sglCallStaticSequence(aol_symbology_layer_stc1);
              }
            }
          }

          /* Object: panel_group_1, Type: panel, OID: 536c6f3f-740a-4bf7-974f-9c8093c84f78 */
          {
            if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 4L)) {
              sglPushMatrixAndTranslate(-224.0F, 71.0F);
              sglBeginScissor(323.0F, 233.0F);

              /* Object: arc_6, Type: arc, OID: 2fce0865-0b5e-4132-abf8-e13a271cc4ae */
              {
                sglSetActiveMasks(lMask_clip_box_1|lMask_stencil_1);
                /* color object part */
                sglIndexColori(6L);
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sglDisable(SGL_GRADIENT);
                /* fill object part */
                sgluArcSector2f(-155.0F, 161.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_FILLED);
                /* outline object part */
                sglIndexColori(16L);
                sglIndexHaloColori(-1L);
                sglIndexLineWidthi(0L);
                sglIndexLineStipplei(0L);
                sglEnable(SGL_LINE_HALOING);
                sglSetLineCaps(SGL_ROUNDED_CAPS);
                sgluArcSector2f(-155.0F, 161.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_CIRCLE_LINE);
              }

              /* Object: circle_10, Type: circle, OID: 5a36b0fe-1104-4499-9be4-3428387ae7f9 */
              {
                /* color object part */
                sglIndexColori(6L);
                /* fill object part */
                sgluArcSector2f(-156.0F, 47.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
                /* outline object part */
                sglIndexColori(16L);
                sgluArcSector2f(-156.0F, 47.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_CIRCLE_LINE);
              }

              /* Object: line_12, Type: line, OID: 4a3a5343-084f-4116-a581-dda96d01143a */
              {
                /* outline object part */
                sglBegin(SGL_LINE_STRIP);
                sglVertex2f(-229.0F, 272.0F);
                sglVertex2f(-182.0F, 294.0F);
                sglVertex2f(-110.0F, 270.0F);
                sglVertex2f(-72.0F, 232.0F);
                sglEnd();
              }

              /* Object: crown_4, Type: crown, OID: 2f75987b-dd3d-4833-a55a-e8727a3ee3ae */
              {
                /* color object part */
                sglIndexColori(6L);
                /* fill object part */
                sgluCrown2f(-150.0F, -64.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_FILLED);
                /* outline object part */
                sglIndexColori(16L);
                sgluCrown2f(-150.0F, -64.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_OUTLINE);
              }

              /* Object: group_4, Type: container, OID: bd69a804-003c-428e-b081-53d080028c14 */
              {
                sglPushMatrixAndTranslate(148.0F, -74.0F);

                /* Object: rectangle_11, Type: rectangle, OID: 366adfb4-0607-4e1d-99c0-f63ea9dc5a84 */
                {
                  /* color object part */
                  sglIndexColori(6L);
                  /* fill object part */
                  sglDisable(SGL_TESSELLATION);
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(17.0F, 296.0F);
                  sglVertex2f(147.0F, 296.0F);
                  sglVertex2f(147.0F, 356.0F);
                  sglVertex2f(17.0F, 356.0F);
                  sglEnd();
                  /* outline object part */
                  sglIndexColori(16L);
                  sglBegin(SGL_LINE_LOOP);
                  sglVertex2f(17.0F, 296.0F);
                  sglVertex2f(147.0F, 296.0F);
                  sglVertex2f(147.0F, 356.0F);
                  sglVertex2f(17.0F, 356.0F);
                  sglEnd();
                }

                /* Object: shape_7, Type: shape, OID: c7c26d36-0765-46a3-bfde-a45d45c05cb3 */
                {
                  /* color object part */
                  sglIndexColori(6L);
                  /* fill object part */
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(-27.0F, 156.0F);
                  sglVertex2f(57.0F, 221.0F);
                  sglVertex2f(129.0F, 228.0F);
                  sglVertex2f(174.0F, 158.0F);
                  sglVertex2f(87.0F, 64.0F);
                  sglEnd();
                  /* outline object part */
                  sglIndexColori(16L);
                  sglBegin(SGL_LINE_LOOP);
                  sglVertex2f(-27.0F, 156.0F);
                  sglVertex2f(57.0F, 221.0F);
                  sglVertex2f(129.0F, 228.0F);
                  sglVertex2f(174.0F, 158.0F);
                  sglVertex2f(87.0F, 64.0F);
                  sglEnd();
                }

                /* Object: rectangle_12, Type: rectangle, OID: 1ff89701-da5f-4b01-806e-0c71a8e83642 */
                {
                  /* color object part */
                  sglIndexColori(11L);
                  sglDisable(SGL_POLYGON_SMOOTH);
                  /* fill object part */
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(179.0F, 297.0F);
                  sglVertex2f(309.0F, 297.0F);
                  sglVertex2f(309.0F, 357.0F);
                  sglVertex2f(179.0F, 357.0F);
                  sglEnd();
                }

                /* Object: shape_8, Type: shape, OID: 67021de6-8edd-49be-8866-7b338c232956 */
                {
                  /* color object part */
                  sglIndexColori(6L);
                  /* fill object part */
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(185.0F, 155.0F);
                  sgluArcSegment(SGL_TRUE, 53.594F);
                  sglVertex2f(341.0F, 227.0F);
                  sglVertex2f(386.0F, 157.0F);
                  sglVertex2f(299.0F, 63.0F);
                  sgluArcSegment(SGL_TRUE, 37.302F);
                  sglEnd();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: line_13, Type: line, OID: dac5fc98-0491-4f5f-912b-61621226f075 */
              {
                /* outline object part */
                sglIndexColori(16L);
                sglIndexLineStipplei(1L);
                sglBegin(SGL_LINE_STRIP);
                sglVertex2f(-36.0F, 265.0F);
                sglVertex2f(11.0F, 287.0F);
                sglVertex2f(83.0F, 263.0F);
                sglVertex2f(121.0F, 225.0F);
                sglEnd();
              }

              /* Object: arc_7, Type: arc, OID: 79e6abf3-8a6b-4f0f-b016-c0b1ffd970bb */
              {
                /* color object part */
                sglIndexColori(11L);
                /* fill object part */
                sgluArcSector2f(8.0F, 164.0F, 44.911F, 11.56F, 278.746F, SGL_FALSE, SGL_ARC_FILLED);
              }

              /* Object: circle_11, Type: circle, OID: 6ba9bea6-9dc8-4614-8238-f3541a3b008f */
              {
                /* color object part */
                /* fill object part */
                sgluArcSector2f(10.0F, 46.0F, 53.235F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
              }

              /* Object: crown_5, Type: crown, OID: b48d68e4-1a15-4899-82dc-c8a802534879 */
              {
                /* color object part */
                sglEnable(SGL_POLYGON_SMOOTH);
                /* fill object part */
                sgluCrown2f(10.0F, -66.0F, 45.044F, 20.779F, 357.455F, 278.13F, SGL_FALSE, SGL_CROWN_FILLED);
              }

              /* Object: circle_12, Type: circle, OID: 94d01291-b429-4e24-a8c5-262fea922053 */
              {
                /* color object part */
                sglIndexColori(41L);
                /* fill object part */
                sgluArcSector2f(91.0F, 124.0F, 30.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_FILLED);
              }

              /* Object: line_14, Type: line, OID: 67bdc266-753b-4260-af46-c4b5e8eeeb30 */
              {
                /* outline object part */
                sglIndexColori(16L);
                sglIndexLineWidthi(6L);
                sglIndexLineStipplei(0L);
                sglSetLineCaps(SGL_STRAIGHT_CAPS);
                sglBegin(SGL_LINE_STRIP);
                sglVertex2f(-238.0F, 274.0F);
                sglVertex2f(-191.0F, 296.0F);
                sgluArcSegment(SGL_FALSE, 80.545F);
                sglVertex2f(-119.0F, 272.0F);
                sglVertex2f(-81.0F, 234.0F);
                sglEnd();
              }

              /* Object: line_15, Type: line, OID: a8aba726-5917-44eb-8ac7-2077d8d274f8 */
              {
                /* outline object part */
                sglIndexLineStipplei(4L);
                sglBegin(SGL_LINE_STRIP);
                sglVertex2f(-45.0F, 263.0F);
                sglVertex2f(2.0F, 285.0F);
                sgluArcSegment(SGL_FALSE, 80.545F);
                sglVertex2f(74.0F, 261.0F);
                sglVertex2f(112.0F, 223.0F);
                sglEnd();
              }

              /* Object: ellipse_6, Type: ellipse, OID: 290e87b9-2f99-4361-8a8c-d1af650b5393 */
              {
                /* color object part */
                sglIndexColori(15L);
                /* fill object part */
                sgluArcEllipse2f(-4.0F, 256.0F, 44.0F, 21.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_FILLED);
              }

              /* Object: ellipse_7, Type: ellipse, OID: 6ce2f014-c7ed-4b8b-bb3d-183b90ba4ca9 */
              {
                /* color object part */
                sglDisable(SGL_POLYGON_SMOOTH);
                /* fill object part */
                sgluArcEllipse2f(115.0F, 232.0F, 17.0F, 48.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_FILLED);
                /* outline object part */
                sglIndexColori(37L);
                sglIndexLineWidthi(1L);
                sglSetLineCaps(SGL_ROUNDED_CAPS);
                sgluArcEllipse2f(115.0F, 232.0F, 17.0F, 48.0F, 0.0F, 360.0F, SGL_TRUE, SGL_ELLIPSE_OUTLINE);
              }
              sglEndScissor();
              sglPopMatrixAndTranslate();
            }
          }

          /* Object: rectangle_13, Type: rectangle, OID: 37d4b749-4932-4b84-927d-a4b04b53b441 */
          {
            if (SGLint32_eq(aol_symbology_layer_G_locMaskIndex(pContext), 4L)) {
              sglSetActiveMasks(lMask_clip_box_1|lMask_stencil_1);
              /* outline object part */
              sglIndexColori(16L);
              sglIndexHaloColori(-1L);
              sglIndexLineWidthi(1L);
              sglIndexLineStipplei(0L);
              sglEnable(SGL_LINE_HALOING);
              sglSetLineCaps(SGL_ROUNDED_CAPS);
              sglTransparency8(255L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-224.0F, 71.0F);
              sglVertex2f(99.0F, 71.0F);
              sglVertex2f(99.0F, 304.0F);
              sglVertex2f(-224.0F, 304.0F);
              sglEnd();
            }
          }
          sglFreeMaskID(lMask_clip_box_1|lMask_stencil_1);
          sglPopMatrixAndTranslate();
        }
      }

      /* Object: Text, Type: container, OID: 9793bbab-87cb-4e78-ad96-91cd732a0507 */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglPushMatrixAndTranslate(-16.0F, 149.0F);
        sglCallStaticSequence(aol_symbology_layer_stc2);
        sglPopMatrixAndTranslate();
      }

      /* Object: Bitmaps, Type: container, OID: c3206f8c-1d44-4979-a8d0-0607e255220c */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        sglPushMatrixAndTranslate(725.0F, -361.335F);
        sglCallStaticSequence(aol_symbology_layer_stc3);
        sglPopMatrixAndTranslate();
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:53:12
 *********************************************************/

