/*********************************************************
 **
 ** File  aol_line_stipple_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:53:13
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sgfx
 *********************************************************/

#ifndef AOL_LINE_STIPPLE_TABLE_H
#define AOL_LINE_STIPPLE_TABLE_H

#include "sgl_types.h"

/* Line stipple table definition */

#define aol_line_stipple_table_size 5UL

extern const sgl_linestipple aol_line_stipple_table[aol_line_stipple_table_size];

#endif /* AOL_LINE_STIPPLE_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:53:13
 *********************************************************/

