/*********************************************************
 **
 ** File  aol_imported_functions.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:53:13
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es2\AllObjects.sgfx
 *********************************************************/

#ifndef AOL_IMPORTED_FUNCTIONS_H
#define AOL_IMPORTED_FUNCTIONS_H

#include "sgl_types.h"

/* Imported functions */
extern void aol_locate(SGLint32 pPointer, SGLfloat *pX, SGLfloat *pY);
extern void aol_pointer(SGLint32 pPointer, SGLbool *pPressed, SGLbool *pReleased, SGLint32 *pButton, SGLfloat *pX, SGLfloat *pY, SGLint32 *pModifiers);
extern void sglSetRenderMode(SGLbool pSmoothMode);

#endif /* AOL_IMPORTED_FUNCTIONS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:53:13
 *********************************************************/

