/*********************************************************
 **
 ** File  aol_symbology_layer.h
 **
 ** Specification File:  D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:52:35
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sgfx
 *********************************************************/

#ifndef AOL_SYMBOLOGY_LAYER_H
#define AOL_SYMBOLOGY_LAYER_H

#include "sgl_types.h"


/* Accessors */
#ifndef aol_symbology_layer_G_CircAngle
#define aol_symbology_layer_G_CircAngle(_C_) (_C_)->CircAngle
#define aol_symbology_layer_S_CircAngle(_C_,_V_) (_C_)->CircAngle = (_V_)
#endif /* aol_symbology_layer_G_CircAngle */
#ifndef aol_symbology_layer_G_CircInside
#define aol_symbology_layer_G_CircInside(_C_) (_C_)->CircInside
#define aol_symbology_layer_S_CircInside(_C_,_V_) (_C_)->CircInside = (_V_)
#endif /* aol_symbology_layer_G_CircInside */
#ifndef aol_symbology_layer_G_CircPercent
#define aol_symbology_layer_G_CircPercent(_C_) (_C_)->CircPercent
#define aol_symbology_layer_S_CircPercent(_C_,_V_) (_C_)->CircPercent = (_V_)
#endif /* aol_symbology_layer_G_CircPercent */
#ifndef aol_symbology_layer_G_RectHeightPercent
#define aol_symbology_layer_G_RectHeightPercent(_C_) (_C_)->RectHeightPercent
#define aol_symbology_layer_S_RectHeightPercent(_C_,_V_) (_C_)->RectHeightPercent = (_V_)
#endif /* aol_symbology_layer_G_RectHeightPercent */
#ifndef aol_symbology_layer_G_RectInside
#define aol_symbology_layer_G_RectInside(_C_) (_C_)->RectInside
#define aol_symbology_layer_S_RectInside(_C_,_V_) (_C_)->RectInside = (_V_)
#endif /* aol_symbology_layer_G_RectInside */
#ifndef aol_symbology_layer_G_RectWidthPercent
#define aol_symbology_layer_G_RectWidthPercent(_C_) (_C_)->RectWidthPercent
#define aol_symbology_layer_S_RectWidthPercent(_C_,_V_) (_C_)->RectWidthPercent = (_V_)
#endif /* aol_symbology_layer_G_RectWidthPercent */
#ifndef aol_symbology_layer_G_ShapeInside
#define aol_symbology_layer_G_ShapeInside(_C_) (_C_)->ShapeInside
#define aol_symbology_layer_S_ShapeInside(_C_,_V_) (_C_)->ShapeInside = (_V_)
#endif /* aol_symbology_layer_G_ShapeInside */
#ifndef aol_symbology_layer_G_Click
#define aol_symbology_layer_G_Click(_C_) (_C_)->Click
#define aol_symbology_layer_S_Click(_C_,_V_) (_C_)->Click = (_V_)
#endif /* aol_symbology_layer_G_Click */
#ifndef aol_symbology_layer_G_Pressed
#define aol_symbology_layer_G_Pressed(_C_) (_C_)->Pressed
#define aol_symbology_layer_S_Pressed(_C_,_V_) (_C_)->Pressed = (_V_)
#endif /* aol_symbology_layer_G_Pressed */
#ifndef aol_symbology_layer_G_locMaskIndex
#define aol_symbology_layer_G_locMaskIndex(_C_) (_C_)->locMaskIndex
#define aol_symbology_layer_S_locMaskIndex(_C_,_V_) (_C_)->locMaskIndex = (_V_)
#endif /* aol_symbology_layer_G_locMaskIndex */
#ifndef aol_symbology_layer_G_locVisiShapes
#define aol_symbology_layer_G_locVisiShapes(_C_) (_C_)->locVisiShapes
#define aol_symbology_layer_S_locVisiShapes(_C_,_V_) (_C_)->locVisiShapes = (_V_)
#endif /* aol_symbology_layer_G_locVisiShapes */
#ifndef aol_symbology_layer_G_locSmoothMode
#define aol_symbology_layer_G_locSmoothMode(_C_) (_C_)->locSmoothMode
#define aol_symbology_layer_S_locSmoothMode(_C_,_V_) (_C_)->locSmoothMode = (_V_)
#endif /* aol_symbology_layer_G_locSmoothMode */
#ifndef aol_symbology_layer_G_locPushedRendering
#define aol_symbology_layer_G_locPushedRendering(_C_) (_C_)->locPushedRendering
#define aol_symbology_layer_S_locPushedRendering(_C_,_V_) (_C_)->locPushedRendering = (_V_)
#endif /* aol_symbology_layer_G_locPushedRendering */
#ifndef aol_symbology_layer_G_locPushedTF
#define aol_symbology_layer_G_locPushedTF(_C_) (_C_)->locPushedTF
#define aol_symbology_layer_S_locPushedTF(_C_,_V_) (_C_)->locPushedTF = (_V_)
#endif /* aol_symbology_layer_G_locPushedTF */
#ifndef aol_symbology_layer_G_locPushedMask
#define aol_symbology_layer_G_locPushedMask(_C_) (_C_)->locPushedMask
#define aol_symbology_layer_S_locPushedMask(_C_,_V_) (_C_)->locPushedMask = (_V_)
#endif /* aol_symbology_layer_G_locPushedMask */

/* Context type */
typedef struct aol_typ_symbology_layer_ {
  /* ------------------------- outputs -------------------------- */
  SGLfloat CircAngle;
  SGLbool CircInside;
  SGLfloat CircPercent;
  SGLfloat RectHeightPercent;
  SGLbool RectInside;
  SGLfloat RectWidthPercent;
  SGLbool ShapeInside;
  SGLbool Click;
  SGLbool Pressed;
  /* ------------------------- locals --------------------------- */
  SGLint32 locMaskIndex;
  SGLbool locVisiShapes;
  SGLbool locSmoothMode;
  SGLbool locPushedRendering;
  SGLbool locPushedTF;
  SGLbool locPushedMask;
} aol_typ_symbology_layer;

/* Associated functions */
extern void aol_symbology_layer_init(aol_typ_symbology_layer *pContext);
extern void aol_symbology_layer_predraw(aol_typ_symbology_layer *pContext);
extern void aol_symbology_layer_draw(aol_typ_symbology_layer *pContext, SGLint32 pPriority);

#endif /* AOL_SYMBOLOGY_LAYER_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:52:35
 *********************************************************/

