/*********************************************************
 **
 ** File  aol_texture_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:52:35
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects_es1\AllObjects.sgfx
 *********************************************************/

#ifndef AOL_TEXTURE_TABLE_H
#define AOL_TEXTURE_TABLE_H

#include "sgl_types.h"

/* Textures definition */

#define aol_texture_table_size 8UL

extern void aol_texture_table(void);

#endif /* AOL_TEXTURE_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:52:35
 *********************************************************/

