/*********************************************************
 **
 ** File  aol_line_width_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:55:24
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.sgfx
 *********************************************************/

#ifndef AOL_LINE_WIDTH_TABLE_H
#define AOL_LINE_WIDTH_TABLE_H

#include "sgl_types.h"

/* Line width table definition */

#define aol_line_width_table_size 7UL

extern const sgl_line_width aol_line_width_table[aol_line_width_table_size];

#endif /* AOL_LINE_WIDTH_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:55:24
 *********************************************************/

