/*********************************************************
 **
 ** File  aol_line_stipple_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:55:24
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd_sc2\PrimaryFlightDisplay.sgfx
 *********************************************************/

#include "aol_line_stipple_table.h"

/* Line stipple table definition */
const sgl_linestipple aol_line_stipple_table[aol_line_stipple_table_size] = 
{
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 0 solid pattern :  */
{ {  12U,  12U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 1 dashed pattern :  */
{ {   8U,   8U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 2 dashed pattern :  */
{ {   1U,   6U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 3 dashed pattern :  */
{ {   1U,   8U,   8U,   8U,   0U,   0U}, {   1U,   0U,   1U,   0U,   0U,   0U},   0U,   4U}  /* 4 dashed pattern :  */
};

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:55:24
 *********************************************************/

