/*********************************************************
 **
 ** File  aol_imported_functions.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:50:31
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sgt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sgfx
 *********************************************************/

#ifndef AOL_IMPORTED_FUNCTIONS_H
#define AOL_IMPORTED_FUNCTIONS_H

#include "sgl_types.h"

/* Imported functions */
extern void ClearErrors(void);
extern void ReadErrors(SGLuint32 *nb_errors, SGLuint32 *last_error_id, SGLuint8 *buffer_status, SGLuint8 (*error_name)[255UL]);
extern void aol_locate(SGLint32 pPointer, SGLfloat *pX, SGLfloat *pY);
extern void aol_pointer(SGLint32 pPointer, SGLbool *pPressed, SGLbool *pReleased, SGLint32 *pButton, SGLfloat *pX, SGLfloat *pY, SGLint32 *pModifiers);
extern void sglDisable(SGLuint8 par_b_mode);
extern void sglEnable(SGLuint8 par_b_mode);
extern void sglSetRenderMode(SGLbool pSmoothMode);
extern void sglVertex2f(SGLfloat par_f_x, SGLfloat par_f_y);

#endif /* AOL_IMPORTED_FUNCTIONS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:50:31
 *********************************************************/

