/*********************************************************
 **
 ** File  aol_font_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:50:30
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sgt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sgfx
 *********************************************************/

#ifndef AOL_FONT_TABLE_H
#define AOL_FONT_TABLE_H

#include "glf.h"

/* Fonts definition */

typedef struct
{
  glf_type_font_table_header tr_header;
  glf_type_font tr_fonts_description[6UL];
  glf_type_map_property tr_maps[1UL];
  glf_type_character_stroke tr_characters0[101UL];
  glf_type_character_stroke tr_characters1[101UL];
  glf_type_character_stroke tr_characters2[101UL];
  glf_type_character_stroke tr_characters3[101UL];
  glf_type_character_stroke tr_characters4[101UL];
  glf_type_character_bitmap2 tr_characters5[475UL];
  /* Font T1 */
  struct {
    /* Char 255 */
    SGLuint32 ui_nb_lines0_255;
    SGLuint16 us_line_type0_255_0;
    SGLuint16 us_nb_vertex0_255_0;
    SGLfloat tf_points0_255_0[8UL];
    /* Char 32 */
    SGLuint32 ui_nb_lines0_32;
    /* Char 34 */
    SGLuint32 ui_nb_lines0_34;
    SGLuint16 us_line_type0_34_0;
    SGLuint16 us_nb_vertex0_34_0;
    SGLfloat tf_points0_34_0[8UL];
    /* Char 37 */
    SGLuint32 ui_nb_lines0_37;
    SGLuint16 us_line_type0_37_0;
    SGLuint16 us_nb_vertex0_37_0;
    SGLfloat tf_points0_37_0[4UL];
    SGLuint16 us_line_type0_37_1;
    SGLuint16 us_nb_vertex0_37_1;
    SGLfloat tf_points0_37_1[12UL];
    SGLuint16 us_line_type0_37_2;
    SGLuint16 us_nb_vertex0_37_2;
    SGLfloat tf_points0_37_2[12UL];
    /* Char 38 */
    SGLuint32 ui_nb_lines0_38;
    SGLuint16 us_line_type0_38_0;
    SGLuint16 us_nb_vertex0_38_0;
    SGLfloat tf_points0_38_0[28UL];
    /* Char 39 */
    SGLuint32 ui_nb_lines0_39;
    SGLuint16 us_line_type0_39_0;
    SGLuint16 us_nb_vertex0_39_0;
    SGLfloat tf_points0_39_0[4UL];
    /* Char 40 */
    SGLuint32 ui_nb_lines0_40;
    SGLuint16 us_line_type0_40_0;
    SGLuint16 us_nb_vertex0_40_0;
    SGLfloat tf_points0_40_0[8UL];
    /* Char 41 */
    SGLuint32 ui_nb_lines0_41;
    SGLuint16 us_line_type0_41_0;
    SGLuint16 us_nb_vertex0_41_0;
    SGLfloat tf_points0_41_0[8UL];
    /* Char 42 */
    SGLuint32 ui_nb_lines0_42;
    SGLuint16 us_line_type0_42_0;
    SGLuint16 us_nb_vertex0_42_0;
    SGLfloat tf_points0_42_0[12UL];
    /* Char 43 */
    SGLuint32 ui_nb_lines0_43;
    SGLuint16 us_line_type0_43_0;
    SGLuint16 us_nb_vertex0_43_0;
    SGLfloat tf_points0_43_0[8UL];
    /* Char 44 */
    SGLuint32 ui_nb_lines0_44;
    SGLuint16 us_line_type0_44_0;
    SGLuint16 us_nb_vertex0_44_0;
    SGLfloat tf_points0_44_0[4UL];
    /* Char 45 */
    SGLuint32 ui_nb_lines0_45;
    SGLuint16 us_line_type0_45_0;
    SGLuint16 us_nb_vertex0_45_0;
    SGLfloat tf_points0_45_0[4UL];
    /* Char 46 */
    SGLuint32 ui_nb_lines0_46;
    SGLuint16 us_line_type0_46_0;
    SGLuint16 us_nb_vertex0_46_0;
    SGLfloat tf_points0_46_0[8UL];
    /* Char 47 */
    SGLuint32 ui_nb_lines0_47;
    SGLuint16 us_line_type0_47_0;
    SGLuint16 us_nb_vertex0_47_0;
    SGLfloat tf_points0_47_0[4UL];
    /* Char 48 */
    SGLuint32 ui_nb_lines0_48;
    SGLuint16 us_line_type0_48_0;
    SGLuint16 us_nb_vertex0_48_0;
    SGLfloat tf_points0_48_0[24UL];
    /* Char 49 */
    SGLuint32 ui_nb_lines0_49;
    SGLuint16 us_line_type0_49_0;
    SGLuint16 us_nb_vertex0_49_0;
    SGLfloat tf_points0_49_0[4UL];
    SGLuint16 us_line_type0_49_1;
    SGLuint16 us_nb_vertex0_49_1;
    SGLfloat tf_points0_49_1[6UL];
    /* Char 50 */
    SGLuint32 ui_nb_lines0_50;
    SGLuint16 us_line_type0_50_0;
    SGLuint16 us_nb_vertex0_50_0;
    SGLfloat tf_points0_50_0[22UL];
    /* Char 51 */
    SGLuint32 ui_nb_lines0_51;
    SGLuint16 us_line_type0_51_0;
    SGLuint16 us_nb_vertex0_51_0;
    SGLfloat tf_points0_51_0[30UL];
    /* Char 52 */
    SGLuint32 ui_nb_lines0_52;
    SGLuint16 us_line_type0_52_0;
    SGLuint16 us_nb_vertex0_52_0;
    SGLfloat tf_points0_52_0[8UL];
    /* Char 53 */
    SGLuint32 ui_nb_lines0_53;
    SGLuint16 us_line_type0_53_0;
    SGLuint16 us_nb_vertex0_53_0;
    SGLfloat tf_points0_53_0[22UL];
    /* Char 54 */
    SGLuint32 ui_nb_lines0_54;
    SGLuint16 us_line_type0_54_0;
    SGLuint16 us_nb_vertex0_54_0;
    SGLfloat tf_points0_54_0[32UL];
    /* Char 55 */
    SGLuint32 ui_nb_lines0_55;
    SGLuint16 us_line_type0_55_0;
    SGLuint16 us_nb_vertex0_55_0;
    SGLfloat tf_points0_55_0[8UL];
    /* Char 56 */
    SGLuint32 ui_nb_lines0_56;
    SGLuint16 us_line_type0_56_0;
    SGLuint16 us_nb_vertex0_56_0;
    SGLfloat tf_points0_56_0[44UL];
    /* Char 57 */
    SGLuint32 ui_nb_lines0_57;
    SGLuint16 us_line_type0_57_0;
    SGLuint16 us_nb_vertex0_57_0;
    SGLfloat tf_points0_57_0[32UL];
    /* Char 58 */
    SGLuint32 ui_nb_lines0_58;
    SGLuint16 us_line_type0_58_0;
    SGLuint16 us_nb_vertex0_58_0;
    SGLfloat tf_points0_58_0[8UL];
    SGLuint16 us_line_type0_58_1;
    SGLuint16 us_nb_vertex0_58_1;
    SGLfloat tf_points0_58_1[8UL];
    /* Char 59 */
    SGLuint32 ui_nb_lines0_59;
    SGLuint16 us_line_type0_59_0;
    SGLuint16 us_nb_vertex0_59_0;
    SGLfloat tf_points0_59_0[8UL];
    SGLuint16 us_line_type0_59_1;
    SGLuint16 us_nb_vertex0_59_1;
    SGLfloat tf_points0_59_1[12UL];
    /* Char 60 */
    SGLuint32 ui_nb_lines0_60;
    SGLuint16 us_line_type0_60_0;
    SGLuint16 us_nb_vertex0_60_0;
    SGLfloat tf_points0_60_0[6UL];
    /* Char 61 */
    SGLuint32 ui_nb_lines0_61;
    SGLuint16 us_line_type0_61_0;
    SGLuint16 us_nb_vertex0_61_0;
    SGLfloat tf_points0_61_0[8UL];
    /* Char 62 */
    SGLuint32 ui_nb_lines0_62;
    SGLuint16 us_line_type0_62_0;
    SGLuint16 us_nb_vertex0_62_0;
    SGLfloat tf_points0_62_0[6UL];
    /* Char 63 */
    SGLuint32 ui_nb_lines0_63;
    SGLuint16 us_line_type0_63_0;
    SGLuint16 us_nb_vertex0_63_0;
    SGLfloat tf_points0_63_0[22UL];
    SGLuint16 us_line_type0_63_1;
    SGLuint16 us_nb_vertex0_63_1;
    SGLfloat tf_points0_63_1[8UL];
    /* Char 64 */
    SGLuint32 ui_nb_lines0_64;
    SGLuint16 us_line_type0_64_0;
    SGLuint16 us_nb_vertex0_64_0;
    SGLfloat tf_points0_64_0[40UL];
    /* Char 65 */
    SGLuint32 ui_nb_lines0_65;
    SGLuint16 us_line_type0_65_0;
    SGLuint16 us_nb_vertex0_65_0;
    SGLfloat tf_points0_65_0[10UL];
    SGLuint16 us_line_type0_65_1;
    SGLuint16 us_nb_vertex0_65_1;
    SGLfloat tf_points0_65_1[4UL];
    /* Char 66 */
    SGLuint32 ui_nb_lines0_66;
    SGLuint16 us_line_type0_66_0;
    SGLuint16 us_nb_vertex0_66_0;
    SGLfloat tf_points0_66_0[30UL];
    /* Char 67 */
    SGLuint32 ui_nb_lines0_67;
    SGLuint16 us_line_type0_67_0;
    SGLuint16 us_nb_vertex0_67_0;
    SGLfloat tf_points0_67_0[24UL];
    /* Char 68 */
    SGLuint32 ui_nb_lines0_68;
    SGLuint16 us_line_type0_68_0;
    SGLuint16 us_nb_vertex0_68_0;
    SGLfloat tf_points0_68_0[16UL];
    /* Char 69 */
    SGLuint32 ui_nb_lines0_69;
    SGLuint16 us_line_type0_69_0;
    SGLuint16 us_nb_vertex0_69_0;
    SGLfloat tf_points0_69_0[4UL];
    SGLuint16 us_line_type0_69_1;
    SGLuint16 us_nb_vertex0_69_1;
    SGLfloat tf_points0_69_1[8UL];
    /* Char 70 */
    SGLuint32 ui_nb_lines0_70;
    SGLuint16 us_line_type0_70_0;
    SGLuint16 us_nb_vertex0_70_0;
    SGLfloat tf_points0_70_0[4UL];
    SGLuint16 us_line_type0_70_1;
    SGLuint16 us_nb_vertex0_70_1;
    SGLfloat tf_points0_70_1[6UL];
    /* Char 71 */
    SGLuint32 ui_nb_lines0_71;
    SGLuint16 us_line_type0_71_0;
    SGLuint16 us_nb_vertex0_71_0;
    SGLfloat tf_points0_71_0[28UL];
    /* Char 72 */
    SGLuint32 ui_nb_lines0_72;
    SGLuint16 us_line_type0_72_0;
    SGLuint16 us_nb_vertex0_72_0;
    SGLfloat tf_points0_72_0[12UL];
    /* Char 73 */
    SGLuint32 ui_nb_lines0_73;
    SGLuint16 us_line_type0_73_0;
    SGLuint16 us_nb_vertex0_73_0;
    SGLfloat tf_points0_73_0[12UL];
    /* Char 74 */
    SGLuint32 ui_nb_lines0_74;
    SGLuint16 us_line_type0_74_0;
    SGLuint16 us_nb_vertex0_74_0;
    SGLfloat tf_points0_74_0[14UL];
    SGLuint16 us_line_type0_74_1;
    SGLuint16 us_nb_vertex0_74_1;
    SGLfloat tf_points0_74_1[4UL];
    /* Char 75 */
    SGLuint32 ui_nb_lines0_75;
    SGLuint16 us_line_type0_75_0;
    SGLuint16 us_nb_vertex0_75_0;
    SGLfloat tf_points0_75_0[12UL];
    /* Char 76 */
    SGLuint32 ui_nb_lines0_76;
    SGLuint16 us_line_type0_76_0;
    SGLuint16 us_nb_vertex0_76_0;
    SGLfloat tf_points0_76_0[6UL];
    /* Char 77 */
    SGLuint32 ui_nb_lines0_77;
    SGLuint16 us_line_type0_77_0;
    SGLuint16 us_nb_vertex0_77_0;
    SGLfloat tf_points0_77_0[10UL];
    /* Char 78 */
    SGLuint32 ui_nb_lines0_78;
    SGLuint16 us_line_type0_78_0;
    SGLuint16 us_nb_vertex0_78_0;
    SGLfloat tf_points0_78_0[8UL];
    /* Char 79 */
    SGLuint32 ui_nb_lines0_79;
    SGLuint16 us_line_type0_79_0;
    SGLuint16 us_nb_vertex0_79_0;
    SGLfloat tf_points0_79_0[32UL];
    /* Char 80 */
    SGLuint32 ui_nb_lines0_80;
    SGLuint16 us_line_type0_80_0;
    SGLuint16 us_nb_vertex0_80_0;
    SGLfloat tf_points0_80_0[18UL];
    /* Char 81 */
    SGLuint32 ui_nb_lines0_81;
    SGLuint16 us_line_type0_81_0;
    SGLuint16 us_nb_vertex0_81_0;
    SGLfloat tf_points0_81_0[4UL];
    SGLuint16 us_line_type0_81_1;
    SGLuint16 us_nb_vertex0_81_1;
    SGLfloat tf_points0_81_1[24UL];
    /* Char 82 */
    SGLuint32 ui_nb_lines0_82;
    SGLuint16 us_line_type0_82_0;
    SGLuint16 us_nb_vertex0_82_0;
    SGLfloat tf_points0_82_0[18UL];
    SGLuint16 us_line_type0_82_1;
    SGLuint16 us_nb_vertex0_82_1;
    SGLfloat tf_points0_82_1[4UL];
    /* Char 83 */
    SGLuint32 ui_nb_lines0_83;
    SGLuint16 us_line_type0_83_0;
    SGLuint16 us_nb_vertex0_83_0;
    SGLfloat tf_points0_83_0[32UL];
    /* Char 84 */
    SGLuint32 ui_nb_lines0_84;
    SGLuint16 us_line_type0_84_0;
    SGLuint16 us_nb_vertex0_84_0;
    SGLfloat tf_points0_84_0[8UL];
    /* Char 85 */
    SGLuint32 ui_nb_lines0_85;
    SGLuint16 us_line_type0_85_0;
    SGLuint16 us_nb_vertex0_85_0;
    SGLfloat tf_points0_85_0[16UL];
    /* Char 86 */
    SGLuint32 ui_nb_lines0_86;
    SGLuint16 us_line_type0_86_0;
    SGLuint16 us_nb_vertex0_86_0;
    SGLfloat tf_points0_86_0[10UL];
    /* Char 87 */
    SGLuint32 ui_nb_lines0_87;
    SGLuint16 us_line_type0_87_0;
    SGLuint16 us_nb_vertex0_87_0;
    SGLfloat tf_points0_87_0[10UL];
    /* Char 88 */
    SGLuint32 ui_nb_lines0_88;
    SGLuint16 us_line_type0_88_0;
    SGLuint16 us_nb_vertex0_88_0;
    SGLfloat tf_points0_88_0[8UL];
    SGLuint16 us_line_type0_88_1;
    SGLuint16 us_nb_vertex0_88_1;
    SGLfloat tf_points0_88_1[8UL];
    /* Char 89 */
    SGLuint32 ui_nb_lines0_89;
    SGLuint16 us_line_type0_89_0;
    SGLuint16 us_nb_vertex0_89_0;
    SGLfloat tf_points0_89_0[8UL];
    SGLuint16 us_line_type0_89_1;
    SGLuint16 us_nb_vertex0_89_1;
    SGLfloat tf_points0_89_1[6UL];
    /* Char 90 */
    SGLuint32 ui_nb_lines0_90;
    SGLuint16 us_line_type0_90_0;
    SGLuint16 us_nb_vertex0_90_0;
    SGLfloat tf_points0_90_0[8UL];
    /* Char 91 */
    SGLuint32 ui_nb_lines0_91;
    SGLuint16 us_line_type0_91_0;
    SGLuint16 us_nb_vertex0_91_0;
    SGLfloat tf_points0_91_0[12UL];
    /* Char 92 */
    SGLuint32 ui_nb_lines0_92;
    SGLuint16 us_line_type0_92_0;
    SGLuint16 us_nb_vertex0_92_0;
    SGLfloat tf_points0_92_0[4UL];
    /* Char 93 */
    SGLuint32 ui_nb_lines0_93;
    SGLuint16 us_line_type0_93_0;
    SGLuint16 us_nb_vertex0_93_0;
    SGLfloat tf_points0_93_0[12UL];
    /* Char 95 */
    SGLuint32 ui_nb_lines0_95;
    SGLuint16 us_line_type0_95_0;
    SGLuint16 us_nb_vertex0_95_0;
    SGLfloat tf_points0_95_0[4UL];
    /* Char 97 */
    SGLuint32 ui_nb_lines0_97;
    SGLuint16 us_line_type0_97_0;
    SGLuint16 us_nb_vertex0_97_0;
    SGLfloat tf_points0_97_0[10UL];
    SGLuint16 us_line_type0_97_1;
    SGLuint16 us_nb_vertex0_97_1;
    SGLfloat tf_points0_97_1[4UL];
    /* Char 98 */
    SGLuint32 ui_nb_lines0_98;
    SGLuint16 us_line_type0_98_0;
    SGLuint16 us_nb_vertex0_98_0;
    SGLfloat tf_points0_98_0[30UL];
    /* Char 99 */
    SGLuint32 ui_nb_lines0_99;
    SGLuint16 us_line_type0_99_0;
    SGLuint16 us_nb_vertex0_99_0;
    SGLfloat tf_points0_99_0[24UL];
    /* Char 100 */
    SGLuint32 ui_nb_lines0_100;
    SGLuint16 us_line_type0_100_0;
    SGLuint16 us_nb_vertex0_100_0;
    SGLfloat tf_points0_100_0[16UL];
    /* Char 101 */
    SGLuint32 ui_nb_lines0_101;
    SGLuint16 us_line_type0_101_0;
    SGLuint16 us_nb_vertex0_101_0;
    SGLfloat tf_points0_101_0[4UL];
    SGLuint16 us_line_type0_101_1;
    SGLuint16 us_nb_vertex0_101_1;
    SGLfloat tf_points0_101_1[8UL];
    /* Char 102 */
    SGLuint32 ui_nb_lines0_102;
    SGLuint16 us_line_type0_102_0;
    SGLuint16 us_nb_vertex0_102_0;
    SGLfloat tf_points0_102_0[4UL];
    SGLuint16 us_line_type0_102_1;
    SGLuint16 us_nb_vertex0_102_1;
    SGLfloat tf_points0_102_1[6UL];
    /* Char 103 */
    SGLuint32 ui_nb_lines0_103;
    SGLuint16 us_line_type0_103_0;
    SGLuint16 us_nb_vertex0_103_0;
    SGLfloat tf_points0_103_0[28UL];
    /* Char 104 */
    SGLuint32 ui_nb_lines0_104;
    SGLuint16 us_line_type0_104_0;
    SGLuint16 us_nb_vertex0_104_0;
    SGLfloat tf_points0_104_0[12UL];
    /* Char 105 */
    SGLuint32 ui_nb_lines0_105;
    SGLuint16 us_line_type0_105_0;
    SGLuint16 us_nb_vertex0_105_0;
    SGLfloat tf_points0_105_0[12UL];
    /* Char 106 */
    SGLuint32 ui_nb_lines0_106;
    SGLuint16 us_line_type0_106_0;
    SGLuint16 us_nb_vertex0_106_0;
    SGLfloat tf_points0_106_0[14UL];
    SGLuint16 us_line_type0_106_1;
    SGLuint16 us_nb_vertex0_106_1;
    SGLfloat tf_points0_106_1[4UL];
    /* Char 107 */
    SGLuint32 ui_nb_lines0_107;
    SGLuint16 us_line_type0_107_0;
    SGLuint16 us_nb_vertex0_107_0;
    SGLfloat tf_points0_107_0[12UL];
    /* Char 108 */
    SGLuint32 ui_nb_lines0_108;
    SGLuint16 us_line_type0_108_0;
    SGLuint16 us_nb_vertex0_108_0;
    SGLfloat tf_points0_108_0[6UL];
    /* Char 109 */
    SGLuint32 ui_nb_lines0_109;
    SGLuint16 us_line_type0_109_0;
    SGLuint16 us_nb_vertex0_109_0;
    SGLfloat tf_points0_109_0[10UL];
    /* Char 110 */
    SGLuint32 ui_nb_lines0_110;
    SGLuint16 us_line_type0_110_0;
    SGLuint16 us_nb_vertex0_110_0;
    SGLfloat tf_points0_110_0[8UL];
    /* Char 111 */
    SGLuint32 ui_nb_lines0_111;
    SGLuint16 us_line_type0_111_0;
    SGLuint16 us_nb_vertex0_111_0;
    SGLfloat tf_points0_111_0[32UL];
    /* Char 112 */
    SGLuint32 ui_nb_lines0_112;
    SGLuint16 us_line_type0_112_0;
    SGLuint16 us_nb_vertex0_112_0;
    SGLfloat tf_points0_112_0[18UL];
    /* Char 113 */
    SGLuint32 ui_nb_lines0_113;
    SGLuint16 us_line_type0_113_0;
    SGLuint16 us_nb_vertex0_113_0;
    SGLfloat tf_points0_113_0[4UL];
    SGLuint16 us_line_type0_113_1;
    SGLuint16 us_nb_vertex0_113_1;
    SGLfloat tf_points0_113_1[24UL];
    /* Char 114 */
    SGLuint32 ui_nb_lines0_114;
    SGLuint16 us_line_type0_114_0;
    SGLuint16 us_nb_vertex0_114_0;
    SGLfloat tf_points0_114_0[18UL];
    SGLuint16 us_line_type0_114_1;
    SGLuint16 us_nb_vertex0_114_1;
    SGLfloat tf_points0_114_1[4UL];
    /* Char 115 */
    SGLuint32 ui_nb_lines0_115;
    SGLuint16 us_line_type0_115_0;
    SGLuint16 us_nb_vertex0_115_0;
    SGLfloat tf_points0_115_0[32UL];
    /* Char 116 */
    SGLuint32 ui_nb_lines0_116;
    SGLuint16 us_line_type0_116_0;
    SGLuint16 us_nb_vertex0_116_0;
    SGLfloat tf_points0_116_0[8UL];
    /* Char 117 */
    SGLuint32 ui_nb_lines0_117;
    SGLuint16 us_line_type0_117_0;
    SGLuint16 us_nb_vertex0_117_0;
    SGLfloat tf_points0_117_0[16UL];
    /* Char 118 */
    SGLuint32 ui_nb_lines0_118;
    SGLuint16 us_line_type0_118_0;
    SGLuint16 us_nb_vertex0_118_0;
    SGLfloat tf_points0_118_0[10UL];
    /* Char 119 */
    SGLuint32 ui_nb_lines0_119;
    SGLuint16 us_line_type0_119_0;
    SGLuint16 us_nb_vertex0_119_0;
    SGLfloat tf_points0_119_0[10UL];
    /* Char 120 */
    SGLuint32 ui_nb_lines0_120;
    SGLuint16 us_line_type0_120_0;
    SGLuint16 us_nb_vertex0_120_0;
    SGLfloat tf_points0_120_0[8UL];
    SGLuint16 us_line_type0_120_1;
    SGLuint16 us_nb_vertex0_120_1;
    SGLfloat tf_points0_120_1[8UL];
    /* Char 121 */
    SGLuint32 ui_nb_lines0_121;
    SGLuint16 us_line_type0_121_0;
    SGLuint16 us_nb_vertex0_121_0;
    SGLfloat tf_points0_121_0[8UL];
    SGLuint16 us_line_type0_121_1;
    SGLuint16 us_nb_vertex0_121_1;
    SGLfloat tf_points0_121_1[6UL];
    /* Char 122 */
    SGLuint32 ui_nb_lines0_122;
    SGLuint16 us_line_type0_122_0;
    SGLuint16 us_nb_vertex0_122_0;
    SGLfloat tf_points0_122_0[8UL];
    /* Char 124 */
    SGLuint32 ui_nb_lines0_124;
    SGLuint16 us_line_type0_124_0;
    SGLuint16 us_nb_vertex0_124_0;
    SGLfloat tf_points0_124_0[4UL];
    /* Char 128 */
    SGLuint32 ui_nb_lines0_128;
    SGLuint16 us_line_type0_128_0;
    SGLuint16 us_nb_vertex0_128_0;
    SGLfloat tf_points0_128_0[6UL];
    /* Char 129 */
    SGLuint32 ui_nb_lines0_129;
    SGLuint16 us_line_type0_129_0;
    SGLuint16 us_nb_vertex0_129_0;
    SGLfloat tf_points0_129_0[12UL];
    /* Char 130 */
    SGLuint32 ui_nb_lines0_130;
    SGLuint16 us_line_type0_130_0;
    SGLuint16 us_nb_vertex0_130_0;
    SGLfloat tf_points0_130_0[8UL];
    /* Char 131 */
    SGLuint32 ui_nb_lines0_131;
    SGLuint16 us_line_type0_131_0;
    SGLuint16 us_nb_vertex0_131_0;
    SGLfloat tf_points0_131_0[8UL];
    /* Char 132 */
    SGLuint32 ui_nb_lines0_132;
    SGLuint16 us_line_type0_132_0;
    SGLuint16 us_nb_vertex0_132_0;
    SGLfloat tf_points0_132_0[4UL];
    SGLuint16 us_line_type0_132_1;
    SGLuint16 us_nb_vertex0_132_1;
    SGLfloat tf_points0_132_1[6UL];
    /* Char 133 */
    SGLuint32 ui_nb_lines0_133;
    SGLuint16 us_line_type0_133_0;
    SGLuint16 us_nb_vertex0_133_0;
    SGLfloat tf_points0_133_0[4UL];
    SGLuint16 us_line_type0_133_1;
    SGLuint16 us_nb_vertex0_133_1;
    SGLfloat tf_points0_133_1[6UL];
    /* Char 134 */
    SGLuint32 ui_nb_lines0_134;
    SGLuint16 us_line_type0_134_0;
    SGLuint16 us_nb_vertex0_134_0;
    SGLfloat tf_points0_134_0[4UL];
    SGLuint16 us_line_type0_134_1;
    SGLuint16 us_nb_vertex0_134_1;
    SGLfloat tf_points0_134_1[6UL];
    /* Char 135 */
    SGLuint32 ui_nb_lines0_135;
    SGLuint16 us_line_type0_135_0;
    SGLuint16 us_nb_vertex0_135_0;
    SGLfloat tf_points0_135_0[4UL];
    SGLuint16 us_line_type0_135_1;
    SGLuint16 us_nb_vertex0_135_1;
    SGLfloat tf_points0_135_1[6UL];
    /* Char 136 */
    SGLuint32 ui_nb_lines0_136;
    /* Char 160 */
    SGLuint32 ui_nb_lines0_160;
    SGLuint16 us_line_type0_160_0;
    SGLuint16 us_nb_vertex0_160_0;
    SGLfloat tf_points0_160_0[8UL];
    /* Char 161 */
    SGLuint32 ui_nb_lines0_161;
    SGLuint16 us_line_type0_161_0;
    SGLuint16 us_nb_vertex0_161_0;
    SGLfloat tf_points0_161_0[8UL];
    SGLuint16 us_line_type0_161_1;
    SGLuint16 us_nb_vertex0_161_1;
    SGLfloat tf_points0_161_1[12UL];
    /* Char 162 */
    SGLuint32 ui_nb_lines0_162;
    SGLuint16 us_line_type0_162_0;
    SGLuint16 us_nb_vertex0_162_0;
    SGLfloat tf_points0_162_0[12UL];
    /* Char 176 */
    SGLuint32 ui_nb_lines0_176;
    SGLuint16 us_line_type0_176_0;
    SGLuint16 us_nb_vertex0_176_0;
    SGLfloat tf_points0_176_0[12UL];
  } strokes0;
  /* Font T2 */
  struct {
    /* Char 255 */
    SGLuint32 ui_nb_lines1_255;
    SGLuint16 us_line_type1_255_0;
    SGLuint16 us_nb_vertex1_255_0;
    SGLfloat tf_points1_255_0[8UL];
    /* Char 32 */
    SGLuint32 ui_nb_lines1_32;
    /* Char 34 */
    SGLuint32 ui_nb_lines1_34;
    SGLuint16 us_line_type1_34_0;
    SGLuint16 us_nb_vertex1_34_0;
    SGLfloat tf_points1_34_0[8UL];
    /* Char 37 */
    SGLuint32 ui_nb_lines1_37;
    SGLuint16 us_line_type1_37_0;
    SGLuint16 us_nb_vertex1_37_0;
    SGLfloat tf_points1_37_0[4UL];
    SGLuint16 us_line_type1_37_1;
    SGLuint16 us_nb_vertex1_37_1;
    SGLfloat tf_points1_37_1[12UL];
    SGLuint16 us_line_type1_37_2;
    SGLuint16 us_nb_vertex1_37_2;
    SGLfloat tf_points1_37_2[12UL];
    /* Char 38 */
    SGLuint32 ui_nb_lines1_38;
    SGLuint16 us_line_type1_38_0;
    SGLuint16 us_nb_vertex1_38_0;
    SGLfloat tf_points1_38_0[28UL];
    /* Char 39 */
    SGLuint32 ui_nb_lines1_39;
    SGLuint16 us_line_type1_39_0;
    SGLuint16 us_nb_vertex1_39_0;
    SGLfloat tf_points1_39_0[4UL];
    /* Char 40 */
    SGLuint32 ui_nb_lines1_40;
    SGLuint16 us_line_type1_40_0;
    SGLuint16 us_nb_vertex1_40_0;
    SGLfloat tf_points1_40_0[8UL];
    /* Char 41 */
    SGLuint32 ui_nb_lines1_41;
    SGLuint16 us_line_type1_41_0;
    SGLuint16 us_nb_vertex1_41_0;
    SGLfloat tf_points1_41_0[8UL];
    /* Char 42 */
    SGLuint32 ui_nb_lines1_42;
    SGLuint16 us_line_type1_42_0;
    SGLuint16 us_nb_vertex1_42_0;
    SGLfloat tf_points1_42_0[12UL];
    /* Char 43 */
    SGLuint32 ui_nb_lines1_43;
    SGLuint16 us_line_type1_43_0;
    SGLuint16 us_nb_vertex1_43_0;
    SGLfloat tf_points1_43_0[8UL];
    /* Char 44 */
    SGLuint32 ui_nb_lines1_44;
    SGLuint16 us_line_type1_44_0;
    SGLuint16 us_nb_vertex1_44_0;
    SGLfloat tf_points1_44_0[4UL];
    /* Char 45 */
    SGLuint32 ui_nb_lines1_45;
    SGLuint16 us_line_type1_45_0;
    SGLuint16 us_nb_vertex1_45_0;
    SGLfloat tf_points1_45_0[4UL];
    /* Char 46 */
    SGLuint32 ui_nb_lines1_46;
    SGLuint16 us_line_type1_46_0;
    SGLuint16 us_nb_vertex1_46_0;
    SGLfloat tf_points1_46_0[8UL];
    /* Char 47 */
    SGLuint32 ui_nb_lines1_47;
    SGLuint16 us_line_type1_47_0;
    SGLuint16 us_nb_vertex1_47_0;
    SGLfloat tf_points1_47_0[4UL];
    /* Char 48 */
    SGLuint32 ui_nb_lines1_48;
    SGLuint16 us_line_type1_48_0;
    SGLuint16 us_nb_vertex1_48_0;
    SGLfloat tf_points1_48_0[24UL];
    /* Char 49 */
    SGLuint32 ui_nb_lines1_49;
    SGLuint16 us_line_type1_49_0;
    SGLuint16 us_nb_vertex1_49_0;
    SGLfloat tf_points1_49_0[4UL];
    SGLuint16 us_line_type1_49_1;
    SGLuint16 us_nb_vertex1_49_1;
    SGLfloat tf_points1_49_1[6UL];
    /* Char 50 */
    SGLuint32 ui_nb_lines1_50;
    SGLuint16 us_line_type1_50_0;
    SGLuint16 us_nb_vertex1_50_0;
    SGLfloat tf_points1_50_0[22UL];
    /* Char 51 */
    SGLuint32 ui_nb_lines1_51;
    SGLuint16 us_line_type1_51_0;
    SGLuint16 us_nb_vertex1_51_0;
    SGLfloat tf_points1_51_0[30UL];
    /* Char 52 */
    SGLuint32 ui_nb_lines1_52;
    SGLuint16 us_line_type1_52_0;
    SGLuint16 us_nb_vertex1_52_0;
    SGLfloat tf_points1_52_0[8UL];
    /* Char 53 */
    SGLuint32 ui_nb_lines1_53;
    SGLuint16 us_line_type1_53_0;
    SGLuint16 us_nb_vertex1_53_0;
    SGLfloat tf_points1_53_0[22UL];
    /* Char 54 */
    SGLuint32 ui_nb_lines1_54;
    SGLuint16 us_line_type1_54_0;
    SGLuint16 us_nb_vertex1_54_0;
    SGLfloat tf_points1_54_0[32UL];
    /* Char 55 */
    SGLuint32 ui_nb_lines1_55;
    SGLuint16 us_line_type1_55_0;
    SGLuint16 us_nb_vertex1_55_0;
    SGLfloat tf_points1_55_0[8UL];
    /* Char 56 */
    SGLuint32 ui_nb_lines1_56;
    SGLuint16 us_line_type1_56_0;
    SGLuint16 us_nb_vertex1_56_0;
    SGLfloat tf_points1_56_0[44UL];
    /* Char 57 */
    SGLuint32 ui_nb_lines1_57;
    SGLuint16 us_line_type1_57_0;
    SGLuint16 us_nb_vertex1_57_0;
    SGLfloat tf_points1_57_0[32UL];
    /* Char 58 */
    SGLuint32 ui_nb_lines1_58;
    SGLuint16 us_line_type1_58_0;
    SGLuint16 us_nb_vertex1_58_0;
    SGLfloat tf_points1_58_0[8UL];
    SGLuint16 us_line_type1_58_1;
    SGLuint16 us_nb_vertex1_58_1;
    SGLfloat tf_points1_58_1[8UL];
    /* Char 59 */
    SGLuint32 ui_nb_lines1_59;
    SGLuint16 us_line_type1_59_0;
    SGLuint16 us_nb_vertex1_59_0;
    SGLfloat tf_points1_59_0[8UL];
    SGLuint16 us_line_type1_59_1;
    SGLuint16 us_nb_vertex1_59_1;
    SGLfloat tf_points1_59_1[12UL];
    /* Char 60 */
    SGLuint32 ui_nb_lines1_60;
    SGLuint16 us_line_type1_60_0;
    SGLuint16 us_nb_vertex1_60_0;
    SGLfloat tf_points1_60_0[6UL];
    /* Char 61 */
    SGLuint32 ui_nb_lines1_61;
    SGLuint16 us_line_type1_61_0;
    SGLuint16 us_nb_vertex1_61_0;
    SGLfloat tf_points1_61_0[8UL];
    /* Char 62 */
    SGLuint32 ui_nb_lines1_62;
    SGLuint16 us_line_type1_62_0;
    SGLuint16 us_nb_vertex1_62_0;
    SGLfloat tf_points1_62_0[6UL];
    /* Char 63 */
    SGLuint32 ui_nb_lines1_63;
    SGLuint16 us_line_type1_63_0;
    SGLuint16 us_nb_vertex1_63_0;
    SGLfloat tf_points1_63_0[20UL];
    SGLuint16 us_line_type1_63_1;
    SGLuint16 us_nb_vertex1_63_1;
    SGLfloat tf_points1_63_1[8UL];
    /* Char 64 */
    SGLuint32 ui_nb_lines1_64;
    SGLuint16 us_line_type1_64_0;
    SGLuint16 us_nb_vertex1_64_0;
    SGLfloat tf_points1_64_0[40UL];
    /* Char 65 */
    SGLuint32 ui_nb_lines1_65;
    SGLuint16 us_line_type1_65_0;
    SGLuint16 us_nb_vertex1_65_0;
    SGLfloat tf_points1_65_0[10UL];
    SGLuint16 us_line_type1_65_1;
    SGLuint16 us_nb_vertex1_65_1;
    SGLfloat tf_points1_65_1[4UL];
    /* Char 66 */
    SGLuint32 ui_nb_lines1_66;
    SGLuint16 us_line_type1_66_0;
    SGLuint16 us_nb_vertex1_66_0;
    SGLfloat tf_points1_66_0[30UL];
    /* Char 67 */
    SGLuint32 ui_nb_lines1_67;
    SGLuint16 us_line_type1_67_0;
    SGLuint16 us_nb_vertex1_67_0;
    SGLfloat tf_points1_67_0[24UL];
    /* Char 68 */
    SGLuint32 ui_nb_lines1_68;
    SGLuint16 us_line_type1_68_0;
    SGLuint16 us_nb_vertex1_68_0;
    SGLfloat tf_points1_68_0[16UL];
    /* Char 69 */
    SGLuint32 ui_nb_lines1_69;
    SGLuint16 us_line_type1_69_0;
    SGLuint16 us_nb_vertex1_69_0;
    SGLfloat tf_points1_69_0[4UL];
    SGLuint16 us_line_type1_69_1;
    SGLuint16 us_nb_vertex1_69_1;
    SGLfloat tf_points1_69_1[8UL];
    /* Char 70 */
    SGLuint32 ui_nb_lines1_70;
    SGLuint16 us_line_type1_70_0;
    SGLuint16 us_nb_vertex1_70_0;
    SGLfloat tf_points1_70_0[4UL];
    SGLuint16 us_line_type1_70_1;
    SGLuint16 us_nb_vertex1_70_1;
    SGLfloat tf_points1_70_1[6UL];
    /* Char 71 */
    SGLuint32 ui_nb_lines1_71;
    SGLuint16 us_line_type1_71_0;
    SGLuint16 us_nb_vertex1_71_0;
    SGLfloat tf_points1_71_0[28UL];
    /* Char 72 */
    SGLuint32 ui_nb_lines1_72;
    SGLuint16 us_line_type1_72_0;
    SGLuint16 us_nb_vertex1_72_0;
    SGLfloat tf_points1_72_0[12UL];
    /* Char 73 */
    SGLuint32 ui_nb_lines1_73;
    SGLuint16 us_line_type1_73_0;
    SGLuint16 us_nb_vertex1_73_0;
    SGLfloat tf_points1_73_0[12UL];
    /* Char 74 */
    SGLuint32 ui_nb_lines1_74;
    SGLuint16 us_line_type1_74_0;
    SGLuint16 us_nb_vertex1_74_0;
    SGLfloat tf_points1_74_0[14UL];
    SGLuint16 us_line_type1_74_1;
    SGLuint16 us_nb_vertex1_74_1;
    SGLfloat tf_points1_74_1[4UL];
    /* Char 75 */
    SGLuint32 ui_nb_lines1_75;
    SGLuint16 us_line_type1_75_0;
    SGLuint16 us_nb_vertex1_75_0;
    SGLfloat tf_points1_75_0[12UL];
    /* Char 76 */
    SGLuint32 ui_nb_lines1_76;
    SGLuint16 us_line_type1_76_0;
    SGLuint16 us_nb_vertex1_76_0;
    SGLfloat tf_points1_76_0[6UL];
    /* Char 77 */
    SGLuint32 ui_nb_lines1_77;
    SGLuint16 us_line_type1_77_0;
    SGLuint16 us_nb_vertex1_77_0;
    SGLfloat tf_points1_77_0[10UL];
    /* Char 78 */
    SGLuint32 ui_nb_lines1_78;
    SGLuint16 us_line_type1_78_0;
    SGLuint16 us_nb_vertex1_78_0;
    SGLfloat tf_points1_78_0[8UL];
    /* Char 79 */
    SGLuint32 ui_nb_lines1_79;
    SGLuint16 us_line_type1_79_0;
    SGLuint16 us_nb_vertex1_79_0;
    SGLfloat tf_points1_79_0[32UL];
    /* Char 80 */
    SGLuint32 ui_nb_lines1_80;
    SGLuint16 us_line_type1_80_0;
    SGLuint16 us_nb_vertex1_80_0;
    SGLfloat tf_points1_80_0[18UL];
    /* Char 81 */
    SGLuint32 ui_nb_lines1_81;
    SGLuint16 us_line_type1_81_0;
    SGLuint16 us_nb_vertex1_81_0;
    SGLfloat tf_points1_81_0[4UL];
    SGLuint16 us_line_type1_81_1;
    SGLuint16 us_nb_vertex1_81_1;
    SGLfloat tf_points1_81_1[24UL];
    /* Char 82 */
    SGLuint32 ui_nb_lines1_82;
    SGLuint16 us_line_type1_82_0;
    SGLuint16 us_nb_vertex1_82_0;
    SGLfloat tf_points1_82_0[18UL];
    SGLuint16 us_line_type1_82_1;
    SGLuint16 us_nb_vertex1_82_1;
    SGLfloat tf_points1_82_1[4UL];
    /* Char 83 */
    SGLuint32 ui_nb_lines1_83;
    SGLuint16 us_line_type1_83_0;
    SGLuint16 us_nb_vertex1_83_0;
    SGLfloat tf_points1_83_0[32UL];
    /* Char 84 */
    SGLuint32 ui_nb_lines1_84;
    SGLuint16 us_line_type1_84_0;
    SGLuint16 us_nb_vertex1_84_0;
    SGLfloat tf_points1_84_0[8UL];
    /* Char 85 */
    SGLuint32 ui_nb_lines1_85;
    SGLuint16 us_line_type1_85_0;
    SGLuint16 us_nb_vertex1_85_0;
    SGLfloat tf_points1_85_0[16UL];
    /* Char 86 */
    SGLuint32 ui_nb_lines1_86;
    SGLuint16 us_line_type1_86_0;
    SGLuint16 us_nb_vertex1_86_0;
    SGLfloat tf_points1_86_0[10UL];
    /* Char 87 */
    SGLuint32 ui_nb_lines1_87;
    SGLuint16 us_line_type1_87_0;
    SGLuint16 us_nb_vertex1_87_0;
    SGLfloat tf_points1_87_0[10UL];
    /* Char 88 */
    SGLuint32 ui_nb_lines1_88;
    SGLuint16 us_line_type1_88_0;
    SGLuint16 us_nb_vertex1_88_0;
    SGLfloat tf_points1_88_0[8UL];
    SGLuint16 us_line_type1_88_1;
    SGLuint16 us_nb_vertex1_88_1;
    SGLfloat tf_points1_88_1[8UL];
    /* Char 89 */
    SGLuint32 ui_nb_lines1_89;
    SGLuint16 us_line_type1_89_0;
    SGLuint16 us_nb_vertex1_89_0;
    SGLfloat tf_points1_89_0[8UL];
    SGLuint16 us_line_type1_89_1;
    SGLuint16 us_nb_vertex1_89_1;
    SGLfloat tf_points1_89_1[6UL];
    /* Char 90 */
    SGLuint32 ui_nb_lines1_90;
    SGLuint16 us_line_type1_90_0;
    SGLuint16 us_nb_vertex1_90_0;
    SGLfloat tf_points1_90_0[8UL];
    /* Char 91 */
    SGLuint32 ui_nb_lines1_91;
    SGLuint16 us_line_type1_91_0;
    SGLuint16 us_nb_vertex1_91_0;
    SGLfloat tf_points1_91_0[12UL];
    /* Char 92 */
    SGLuint32 ui_nb_lines1_92;
    SGLuint16 us_line_type1_92_0;
    SGLuint16 us_nb_vertex1_92_0;
    SGLfloat tf_points1_92_0[4UL];
    /* Char 93 */
    SGLuint32 ui_nb_lines1_93;
    SGLuint16 us_line_type1_93_0;
    SGLuint16 us_nb_vertex1_93_0;
    SGLfloat tf_points1_93_0[12UL];
    /* Char 95 */
    SGLuint32 ui_nb_lines1_95;
    SGLuint16 us_line_type1_95_0;
    SGLuint16 us_nb_vertex1_95_0;
    SGLfloat tf_points1_95_0[4UL];
    /* Char 97 */
    SGLuint32 ui_nb_lines1_97;
    SGLuint16 us_line_type1_97_0;
    SGLuint16 us_nb_vertex1_97_0;
    SGLfloat tf_points1_97_0[10UL];
    SGLuint16 us_line_type1_97_1;
    SGLuint16 us_nb_vertex1_97_1;
    SGLfloat tf_points1_97_1[4UL];
    /* Char 98 */
    SGLuint32 ui_nb_lines1_98;
    SGLuint16 us_line_type1_98_0;
    SGLuint16 us_nb_vertex1_98_0;
    SGLfloat tf_points1_98_0[30UL];
    /* Char 99 */
    SGLuint32 ui_nb_lines1_99;
    SGLuint16 us_line_type1_99_0;
    SGLuint16 us_nb_vertex1_99_0;
    SGLfloat tf_points1_99_0[24UL];
    /* Char 100 */
    SGLuint32 ui_nb_lines1_100;
    SGLuint16 us_line_type1_100_0;
    SGLuint16 us_nb_vertex1_100_0;
    SGLfloat tf_points1_100_0[16UL];
    /* Char 101 */
    SGLuint32 ui_nb_lines1_101;
    SGLuint16 us_line_type1_101_0;
    SGLuint16 us_nb_vertex1_101_0;
    SGLfloat tf_points1_101_0[4UL];
    SGLuint16 us_line_type1_101_1;
    SGLuint16 us_nb_vertex1_101_1;
    SGLfloat tf_points1_101_1[8UL];
    /* Char 102 */
    SGLuint32 ui_nb_lines1_102;
    SGLuint16 us_line_type1_102_0;
    SGLuint16 us_nb_vertex1_102_0;
    SGLfloat tf_points1_102_0[4UL];
    SGLuint16 us_line_type1_102_1;
    SGLuint16 us_nb_vertex1_102_1;
    SGLfloat tf_points1_102_1[6UL];
    /* Char 103 */
    SGLuint32 ui_nb_lines1_103;
    SGLuint16 us_line_type1_103_0;
    SGLuint16 us_nb_vertex1_103_0;
    SGLfloat tf_points1_103_0[28UL];
    /* Char 104 */
    SGLuint32 ui_nb_lines1_104;
    SGLuint16 us_line_type1_104_0;
    SGLuint16 us_nb_vertex1_104_0;
    SGLfloat tf_points1_104_0[12UL];
    /* Char 105 */
    SGLuint32 ui_nb_lines1_105;
    SGLuint16 us_line_type1_105_0;
    SGLuint16 us_nb_vertex1_105_0;
    SGLfloat tf_points1_105_0[12UL];
    /* Char 106 */
    SGLuint32 ui_nb_lines1_106;
    SGLuint16 us_line_type1_106_0;
    SGLuint16 us_nb_vertex1_106_0;
    SGLfloat tf_points1_106_0[14UL];
    SGLuint16 us_line_type1_106_1;
    SGLuint16 us_nb_vertex1_106_1;
    SGLfloat tf_points1_106_1[4UL];
    /* Char 107 */
    SGLuint32 ui_nb_lines1_107;
    SGLuint16 us_line_type1_107_0;
    SGLuint16 us_nb_vertex1_107_0;
    SGLfloat tf_points1_107_0[12UL];
    /* Char 108 */
    SGLuint32 ui_nb_lines1_108;
    SGLuint16 us_line_type1_108_0;
    SGLuint16 us_nb_vertex1_108_0;
    SGLfloat tf_points1_108_0[6UL];
    /* Char 109 */
    SGLuint32 ui_nb_lines1_109;
    SGLuint16 us_line_type1_109_0;
    SGLuint16 us_nb_vertex1_109_0;
    SGLfloat tf_points1_109_0[10UL];
    /* Char 110 */
    SGLuint32 ui_nb_lines1_110;
    SGLuint16 us_line_type1_110_0;
    SGLuint16 us_nb_vertex1_110_0;
    SGLfloat tf_points1_110_0[8UL];
    /* Char 111 */
    SGLuint32 ui_nb_lines1_111;
    SGLuint16 us_line_type1_111_0;
    SGLuint16 us_nb_vertex1_111_0;
    SGLfloat tf_points1_111_0[32UL];
    /* Char 112 */
    SGLuint32 ui_nb_lines1_112;
    SGLuint16 us_line_type1_112_0;
    SGLuint16 us_nb_vertex1_112_0;
    SGLfloat tf_points1_112_0[18UL];
    /* Char 113 */
    SGLuint32 ui_nb_lines1_113;
    SGLuint16 us_line_type1_113_0;
    SGLuint16 us_nb_vertex1_113_0;
    SGLfloat tf_points1_113_0[4UL];
    SGLuint16 us_line_type1_113_1;
    SGLuint16 us_nb_vertex1_113_1;
    SGLfloat tf_points1_113_1[24UL];
    /* Char 114 */
    SGLuint32 ui_nb_lines1_114;
    SGLuint16 us_line_type1_114_0;
    SGLuint16 us_nb_vertex1_114_0;
    SGLfloat tf_points1_114_0[18UL];
    SGLuint16 us_line_type1_114_1;
    SGLuint16 us_nb_vertex1_114_1;
    SGLfloat tf_points1_114_1[4UL];
    /* Char 115 */
    SGLuint32 ui_nb_lines1_115;
    SGLuint16 us_line_type1_115_0;
    SGLuint16 us_nb_vertex1_115_0;
    SGLfloat tf_points1_115_0[32UL];
    /* Char 116 */
    SGLuint32 ui_nb_lines1_116;
    SGLuint16 us_line_type1_116_0;
    SGLuint16 us_nb_vertex1_116_0;
    SGLfloat tf_points1_116_0[8UL];
    /* Char 117 */
    SGLuint32 ui_nb_lines1_117;
    SGLuint16 us_line_type1_117_0;
    SGLuint16 us_nb_vertex1_117_0;
    SGLfloat tf_points1_117_0[16UL];
    /* Char 118 */
    SGLuint32 ui_nb_lines1_118;
    SGLuint16 us_line_type1_118_0;
    SGLuint16 us_nb_vertex1_118_0;
    SGLfloat tf_points1_118_0[10UL];
    /* Char 119 */
    SGLuint32 ui_nb_lines1_119;
    SGLuint16 us_line_type1_119_0;
    SGLuint16 us_nb_vertex1_119_0;
    SGLfloat tf_points1_119_0[10UL];
    /* Char 120 */
    SGLuint32 ui_nb_lines1_120;
    SGLuint16 us_line_type1_120_0;
    SGLuint16 us_nb_vertex1_120_0;
    SGLfloat tf_points1_120_0[8UL];
    SGLuint16 us_line_type1_120_1;
    SGLuint16 us_nb_vertex1_120_1;
    SGLfloat tf_points1_120_1[8UL];
    /* Char 121 */
    SGLuint32 ui_nb_lines1_121;
    SGLuint16 us_line_type1_121_0;
    SGLuint16 us_nb_vertex1_121_0;
    SGLfloat tf_points1_121_0[8UL];
    SGLuint16 us_line_type1_121_1;
    SGLuint16 us_nb_vertex1_121_1;
    SGLfloat tf_points1_121_1[6UL];
    /* Char 122 */
    SGLuint32 ui_nb_lines1_122;
    SGLuint16 us_line_type1_122_0;
    SGLuint16 us_nb_vertex1_122_0;
    SGLfloat tf_points1_122_0[8UL];
    /* Char 124 */
    SGLuint32 ui_nb_lines1_124;
    SGLuint16 us_line_type1_124_0;
    SGLuint16 us_nb_vertex1_124_0;
    SGLfloat tf_points1_124_0[4UL];
    /* Char 128 */
    SGLuint32 ui_nb_lines1_128;
    SGLuint16 us_line_type1_128_0;
    SGLuint16 us_nb_vertex1_128_0;
    SGLfloat tf_points1_128_0[6UL];
    /* Char 129 */
    SGLuint32 ui_nb_lines1_129;
    SGLuint16 us_line_type1_129_0;
    SGLuint16 us_nb_vertex1_129_0;
    SGLfloat tf_points1_129_0[12UL];
    /* Char 130 */
    SGLuint32 ui_nb_lines1_130;
    SGLuint16 us_line_type1_130_0;
    SGLuint16 us_nb_vertex1_130_0;
    SGLfloat tf_points1_130_0[8UL];
    /* Char 131 */
    SGLuint32 ui_nb_lines1_131;
    SGLuint16 us_line_type1_131_0;
    SGLuint16 us_nb_vertex1_131_0;
    SGLfloat tf_points1_131_0[8UL];
    /* Char 132 */
    SGLuint32 ui_nb_lines1_132;
    SGLuint16 us_line_type1_132_0;
    SGLuint16 us_nb_vertex1_132_0;
    SGLfloat tf_points1_132_0[4UL];
    SGLuint16 us_line_type1_132_1;
    SGLuint16 us_nb_vertex1_132_1;
    SGLfloat tf_points1_132_1[6UL];
    /* Char 133 */
    SGLuint32 ui_nb_lines1_133;
    SGLuint16 us_line_type1_133_0;
    SGLuint16 us_nb_vertex1_133_0;
    SGLfloat tf_points1_133_0[4UL];
    SGLuint16 us_line_type1_133_1;
    SGLuint16 us_nb_vertex1_133_1;
    SGLfloat tf_points1_133_1[6UL];
    /* Char 134 */
    SGLuint32 ui_nb_lines1_134;
    SGLuint16 us_line_type1_134_0;
    SGLuint16 us_nb_vertex1_134_0;
    SGLfloat tf_points1_134_0[4UL];
    SGLuint16 us_line_type1_134_1;
    SGLuint16 us_nb_vertex1_134_1;
    SGLfloat tf_points1_134_1[6UL];
    /* Char 135 */
    SGLuint32 ui_nb_lines1_135;
    SGLuint16 us_line_type1_135_0;
    SGLuint16 us_nb_vertex1_135_0;
    SGLfloat tf_points1_135_0[4UL];
    SGLuint16 us_line_type1_135_1;
    SGLuint16 us_nb_vertex1_135_1;
    SGLfloat tf_points1_135_1[6UL];
    /* Char 136 */
    SGLuint32 ui_nb_lines1_136;
    /* Char 160 */
    SGLuint32 ui_nb_lines1_160;
    SGLuint16 us_line_type1_160_0;
    SGLuint16 us_nb_vertex1_160_0;
    SGLfloat tf_points1_160_0[8UL];
    /* Char 161 */
    SGLuint32 ui_nb_lines1_161;
    SGLuint16 us_line_type1_161_0;
    SGLuint16 us_nb_vertex1_161_0;
    SGLfloat tf_points1_161_0[8UL];
    SGLuint16 us_line_type1_161_1;
    SGLuint16 us_nb_vertex1_161_1;
    SGLfloat tf_points1_161_1[14UL];
    /* Char 162 */
    SGLuint32 ui_nb_lines1_162;
    SGLuint16 us_line_type1_162_0;
    SGLuint16 us_nb_vertex1_162_0;
    SGLfloat tf_points1_162_0[14UL];
    /* Char 176 */
    SGLuint32 ui_nb_lines1_176;
    SGLuint16 us_line_type1_176_0;
    SGLuint16 us_nb_vertex1_176_0;
    SGLfloat tf_points1_176_0[12UL];
  } strokes1;
  /* Font T3 */
  struct {
    /* Char 255 */
    SGLuint32 ui_nb_lines2_255;
    SGLuint16 us_line_type2_255_0;
    SGLuint16 us_nb_vertex2_255_0;
    SGLfloat tf_points2_255_0[8UL];
    /* Char 32 */
    SGLuint32 ui_nb_lines2_32;
    /* Char 34 */
    SGLuint32 ui_nb_lines2_34;
    SGLuint16 us_line_type2_34_0;
    SGLuint16 us_nb_vertex2_34_0;
    SGLfloat tf_points2_34_0[8UL];
    /* Char 37 */
    SGLuint32 ui_nb_lines2_37;
    SGLuint16 us_line_type2_37_0;
    SGLuint16 us_nb_vertex2_37_0;
    SGLfloat tf_points2_37_0[4UL];
    SGLuint16 us_line_type2_37_1;
    SGLuint16 us_nb_vertex2_37_1;
    SGLfloat tf_points2_37_1[12UL];
    SGLuint16 us_line_type2_37_2;
    SGLuint16 us_nb_vertex2_37_2;
    SGLfloat tf_points2_37_2[12UL];
    /* Char 38 */
    SGLuint32 ui_nb_lines2_38;
    SGLuint16 us_line_type2_38_0;
    SGLuint16 us_nb_vertex2_38_0;
    SGLfloat tf_points2_38_0[28UL];
    /* Char 39 */
    SGLuint32 ui_nb_lines2_39;
    SGLuint16 us_line_type2_39_0;
    SGLuint16 us_nb_vertex2_39_0;
    SGLfloat tf_points2_39_0[4UL];
    /* Char 40 */
    SGLuint32 ui_nb_lines2_40;
    SGLuint16 us_line_type2_40_0;
    SGLuint16 us_nb_vertex2_40_0;
    SGLfloat tf_points2_40_0[8UL];
    /* Char 41 */
    SGLuint32 ui_nb_lines2_41;
    SGLuint16 us_line_type2_41_0;
    SGLuint16 us_nb_vertex2_41_0;
    SGLfloat tf_points2_41_0[8UL];
    /* Char 42 */
    SGLuint32 ui_nb_lines2_42;
    SGLuint16 us_line_type2_42_0;
    SGLuint16 us_nb_vertex2_42_0;
    SGLfloat tf_points2_42_0[12UL];
    /* Char 43 */
    SGLuint32 ui_nb_lines2_43;
    SGLuint16 us_line_type2_43_0;
    SGLuint16 us_nb_vertex2_43_0;
    SGLfloat tf_points2_43_0[8UL];
    /* Char 44 */
    SGLuint32 ui_nb_lines2_44;
    SGLuint16 us_line_type2_44_0;
    SGLuint16 us_nb_vertex2_44_0;
    SGLfloat tf_points2_44_0[4UL];
    /* Char 45 */
    SGLuint32 ui_nb_lines2_45;
    SGLuint16 us_line_type2_45_0;
    SGLuint16 us_nb_vertex2_45_0;
    SGLfloat tf_points2_45_0[4UL];
    /* Char 46 */
    SGLuint32 ui_nb_lines2_46;
    SGLuint16 us_line_type2_46_0;
    SGLuint16 us_nb_vertex2_46_0;
    SGLfloat tf_points2_46_0[8UL];
    /* Char 47 */
    SGLuint32 ui_nb_lines2_47;
    SGLuint16 us_line_type2_47_0;
    SGLuint16 us_nb_vertex2_47_0;
    SGLfloat tf_points2_47_0[4UL];
    /* Char 48 */
    SGLuint32 ui_nb_lines2_48;
    SGLuint16 us_line_type2_48_0;
    SGLuint16 us_nb_vertex2_48_0;
    SGLfloat tf_points2_48_0[24UL];
    /* Char 49 */
    SGLuint32 ui_nb_lines2_49;
    SGLuint16 us_line_type2_49_0;
    SGLuint16 us_nb_vertex2_49_0;
    SGLfloat tf_points2_49_0[4UL];
    SGLuint16 us_line_type2_49_1;
    SGLuint16 us_nb_vertex2_49_1;
    SGLfloat tf_points2_49_1[6UL];
    /* Char 50 */
    SGLuint32 ui_nb_lines2_50;
    SGLuint16 us_line_type2_50_0;
    SGLuint16 us_nb_vertex2_50_0;
    SGLfloat tf_points2_50_0[22UL];
    /* Char 51 */
    SGLuint32 ui_nb_lines2_51;
    SGLuint16 us_line_type2_51_0;
    SGLuint16 us_nb_vertex2_51_0;
    SGLfloat tf_points2_51_0[30UL];
    /* Char 52 */
    SGLuint32 ui_nb_lines2_52;
    SGLuint16 us_line_type2_52_0;
    SGLuint16 us_nb_vertex2_52_0;
    SGLfloat tf_points2_52_0[8UL];
    /* Char 53 */
    SGLuint32 ui_nb_lines2_53;
    SGLuint16 us_line_type2_53_0;
    SGLuint16 us_nb_vertex2_53_0;
    SGLfloat tf_points2_53_0[22UL];
    /* Char 54 */
    SGLuint32 ui_nb_lines2_54;
    SGLuint16 us_line_type2_54_0;
    SGLuint16 us_nb_vertex2_54_0;
    SGLfloat tf_points2_54_0[32UL];
    /* Char 55 */
    SGLuint32 ui_nb_lines2_55;
    SGLuint16 us_line_type2_55_0;
    SGLuint16 us_nb_vertex2_55_0;
    SGLfloat tf_points2_55_0[8UL];
    /* Char 56 */
    SGLuint32 ui_nb_lines2_56;
    SGLuint16 us_line_type2_56_0;
    SGLuint16 us_nb_vertex2_56_0;
    SGLfloat tf_points2_56_0[44UL];
    /* Char 57 */
    SGLuint32 ui_nb_lines2_57;
    SGLuint16 us_line_type2_57_0;
    SGLuint16 us_nb_vertex2_57_0;
    SGLfloat tf_points2_57_0[32UL];
    /* Char 58 */
    SGLuint32 ui_nb_lines2_58;
    SGLuint16 us_line_type2_58_0;
    SGLuint16 us_nb_vertex2_58_0;
    SGLfloat tf_points2_58_0[8UL];
    SGLuint16 us_line_type2_58_1;
    SGLuint16 us_nb_vertex2_58_1;
    SGLfloat tf_points2_58_1[8UL];
    /* Char 59 */
    SGLuint32 ui_nb_lines2_59;
    SGLuint16 us_line_type2_59_0;
    SGLuint16 us_nb_vertex2_59_0;
    SGLfloat tf_points2_59_0[8UL];
    SGLuint16 us_line_type2_59_1;
    SGLuint16 us_nb_vertex2_59_1;
    SGLfloat tf_points2_59_1[12UL];
    /* Char 60 */
    SGLuint32 ui_nb_lines2_60;
    SGLuint16 us_line_type2_60_0;
    SGLuint16 us_nb_vertex2_60_0;
    SGLfloat tf_points2_60_0[6UL];
    /* Char 61 */
    SGLuint32 ui_nb_lines2_61;
    SGLuint16 us_line_type2_61_0;
    SGLuint16 us_nb_vertex2_61_0;
    SGLfloat tf_points2_61_0[8UL];
    /* Char 62 */
    SGLuint32 ui_nb_lines2_62;
    SGLuint16 us_line_type2_62_0;
    SGLuint16 us_nb_vertex2_62_0;
    SGLfloat tf_points2_62_0[6UL];
    /* Char 63 */
    SGLuint32 ui_nb_lines2_63;
    SGLuint16 us_line_type2_63_0;
    SGLuint16 us_nb_vertex2_63_0;
    SGLfloat tf_points2_63_0[20UL];
    SGLuint16 us_line_type2_63_1;
    SGLuint16 us_nb_vertex2_63_1;
    SGLfloat tf_points2_63_1[8UL];
    /* Char 64 */
    SGLuint32 ui_nb_lines2_64;
    SGLuint16 us_line_type2_64_0;
    SGLuint16 us_nb_vertex2_64_0;
    SGLfloat tf_points2_64_0[42UL];
    /* Char 65 */
    SGLuint32 ui_nb_lines2_65;
    SGLuint16 us_line_type2_65_0;
    SGLuint16 us_nb_vertex2_65_0;
    SGLfloat tf_points2_65_0[10UL];
    SGLuint16 us_line_type2_65_1;
    SGLuint16 us_nb_vertex2_65_1;
    SGLfloat tf_points2_65_1[4UL];
    /* Char 66 */
    SGLuint32 ui_nb_lines2_66;
    SGLuint16 us_line_type2_66_0;
    SGLuint16 us_nb_vertex2_66_0;
    SGLfloat tf_points2_66_0[30UL];
    /* Char 67 */
    SGLuint32 ui_nb_lines2_67;
    SGLuint16 us_line_type2_67_0;
    SGLuint16 us_nb_vertex2_67_0;
    SGLfloat tf_points2_67_0[24UL];
    /* Char 68 */
    SGLuint32 ui_nb_lines2_68;
    SGLuint16 us_line_type2_68_0;
    SGLuint16 us_nb_vertex2_68_0;
    SGLfloat tf_points2_68_0[16UL];
    /* Char 69 */
    SGLuint32 ui_nb_lines2_69;
    SGLuint16 us_line_type2_69_0;
    SGLuint16 us_nb_vertex2_69_0;
    SGLfloat tf_points2_69_0[4UL];
    SGLuint16 us_line_type2_69_1;
    SGLuint16 us_nb_vertex2_69_1;
    SGLfloat tf_points2_69_1[8UL];
    /* Char 70 */
    SGLuint32 ui_nb_lines2_70;
    SGLuint16 us_line_type2_70_0;
    SGLuint16 us_nb_vertex2_70_0;
    SGLfloat tf_points2_70_0[4UL];
    SGLuint16 us_line_type2_70_1;
    SGLuint16 us_nb_vertex2_70_1;
    SGLfloat tf_points2_70_1[6UL];
    /* Char 71 */
    SGLuint32 ui_nb_lines2_71;
    SGLuint16 us_line_type2_71_0;
    SGLuint16 us_nb_vertex2_71_0;
    SGLfloat tf_points2_71_0[28UL];
    /* Char 72 */
    SGLuint32 ui_nb_lines2_72;
    SGLuint16 us_line_type2_72_0;
    SGLuint16 us_nb_vertex2_72_0;
    SGLfloat tf_points2_72_0[12UL];
    /* Char 73 */
    SGLuint32 ui_nb_lines2_73;
    SGLuint16 us_line_type2_73_0;
    SGLuint16 us_nb_vertex2_73_0;
    SGLfloat tf_points2_73_0[12UL];
    /* Char 74 */
    SGLuint32 ui_nb_lines2_74;
    SGLuint16 us_line_type2_74_0;
    SGLuint16 us_nb_vertex2_74_0;
    SGLfloat tf_points2_74_0[14UL];
    SGLuint16 us_line_type2_74_1;
    SGLuint16 us_nb_vertex2_74_1;
    SGLfloat tf_points2_74_1[4UL];
    /* Char 75 */
    SGLuint32 ui_nb_lines2_75;
    SGLuint16 us_line_type2_75_0;
    SGLuint16 us_nb_vertex2_75_0;
    SGLfloat tf_points2_75_0[12UL];
    /* Char 76 */
    SGLuint32 ui_nb_lines2_76;
    SGLuint16 us_line_type2_76_0;
    SGLuint16 us_nb_vertex2_76_0;
    SGLfloat tf_points2_76_0[6UL];
    /* Char 77 */
    SGLuint32 ui_nb_lines2_77;
    SGLuint16 us_line_type2_77_0;
    SGLuint16 us_nb_vertex2_77_0;
    SGLfloat tf_points2_77_0[10UL];
    /* Char 78 */
    SGLuint32 ui_nb_lines2_78;
    SGLuint16 us_line_type2_78_0;
    SGLuint16 us_nb_vertex2_78_0;
    SGLfloat tf_points2_78_0[8UL];
    /* Char 79 */
    SGLuint32 ui_nb_lines2_79;
    SGLuint16 us_line_type2_79_0;
    SGLuint16 us_nb_vertex2_79_0;
    SGLfloat tf_points2_79_0[32UL];
    /* Char 80 */
    SGLuint32 ui_nb_lines2_80;
    SGLuint16 us_line_type2_80_0;
    SGLuint16 us_nb_vertex2_80_0;
    SGLfloat tf_points2_80_0[18UL];
    /* Char 81 */
    SGLuint32 ui_nb_lines2_81;
    SGLuint16 us_line_type2_81_0;
    SGLuint16 us_nb_vertex2_81_0;
    SGLfloat tf_points2_81_0[4UL];
    SGLuint16 us_line_type2_81_1;
    SGLuint16 us_nb_vertex2_81_1;
    SGLfloat tf_points2_81_1[24UL];
    /* Char 82 */
    SGLuint32 ui_nb_lines2_82;
    SGLuint16 us_line_type2_82_0;
    SGLuint16 us_nb_vertex2_82_0;
    SGLfloat tf_points2_82_0[18UL];
    SGLuint16 us_line_type2_82_1;
    SGLuint16 us_nb_vertex2_82_1;
    SGLfloat tf_points2_82_1[4UL];
    /* Char 83 */
    SGLuint32 ui_nb_lines2_83;
    SGLuint16 us_line_type2_83_0;
    SGLuint16 us_nb_vertex2_83_0;
    SGLfloat tf_points2_83_0[32UL];
    /* Char 84 */
    SGLuint32 ui_nb_lines2_84;
    SGLuint16 us_line_type2_84_0;
    SGLuint16 us_nb_vertex2_84_0;
    SGLfloat tf_points2_84_0[8UL];
    /* Char 85 */
    SGLuint32 ui_nb_lines2_85;
    SGLuint16 us_line_type2_85_0;
    SGLuint16 us_nb_vertex2_85_0;
    SGLfloat tf_points2_85_0[16UL];
    /* Char 86 */
    SGLuint32 ui_nb_lines2_86;
    SGLuint16 us_line_type2_86_0;
    SGLuint16 us_nb_vertex2_86_0;
    SGLfloat tf_points2_86_0[10UL];
    /* Char 87 */
    SGLuint32 ui_nb_lines2_87;
    SGLuint16 us_line_type2_87_0;
    SGLuint16 us_nb_vertex2_87_0;
    SGLfloat tf_points2_87_0[10UL];
    /* Char 88 */
    SGLuint32 ui_nb_lines2_88;
    SGLuint16 us_line_type2_88_0;
    SGLuint16 us_nb_vertex2_88_0;
    SGLfloat tf_points2_88_0[8UL];
    SGLuint16 us_line_type2_88_1;
    SGLuint16 us_nb_vertex2_88_1;
    SGLfloat tf_points2_88_1[8UL];
    /* Char 89 */
    SGLuint32 ui_nb_lines2_89;
    SGLuint16 us_line_type2_89_0;
    SGLuint16 us_nb_vertex2_89_0;
    SGLfloat tf_points2_89_0[8UL];
    SGLuint16 us_line_type2_89_1;
    SGLuint16 us_nb_vertex2_89_1;
    SGLfloat tf_points2_89_1[6UL];
    /* Char 90 */
    SGLuint32 ui_nb_lines2_90;
    SGLuint16 us_line_type2_90_0;
    SGLuint16 us_nb_vertex2_90_0;
    SGLfloat tf_points2_90_0[8UL];
    /* Char 91 */
    SGLuint32 ui_nb_lines2_91;
    SGLuint16 us_line_type2_91_0;
    SGLuint16 us_nb_vertex2_91_0;
    SGLfloat tf_points2_91_0[12UL];
    /* Char 92 */
    SGLuint32 ui_nb_lines2_92;
    SGLuint16 us_line_type2_92_0;
    SGLuint16 us_nb_vertex2_92_0;
    SGLfloat tf_points2_92_0[4UL];
    /* Char 93 */
    SGLuint32 ui_nb_lines2_93;
    SGLuint16 us_line_type2_93_0;
    SGLuint16 us_nb_vertex2_93_0;
    SGLfloat tf_points2_93_0[12UL];
    /* Char 95 */
    SGLuint32 ui_nb_lines2_95;
    SGLuint16 us_line_type2_95_0;
    SGLuint16 us_nb_vertex2_95_0;
    SGLfloat tf_points2_95_0[4UL];
    /* Char 97 */
    SGLuint32 ui_nb_lines2_97;
    SGLuint16 us_line_type2_97_0;
    SGLuint16 us_nb_vertex2_97_0;
    SGLfloat tf_points2_97_0[10UL];
    SGLuint16 us_line_type2_97_1;
    SGLuint16 us_nb_vertex2_97_1;
    SGLfloat tf_points2_97_1[4UL];
    /* Char 98 */
    SGLuint32 ui_nb_lines2_98;
    SGLuint16 us_line_type2_98_0;
    SGLuint16 us_nb_vertex2_98_0;
    SGLfloat tf_points2_98_0[30UL];
    /* Char 99 */
    SGLuint32 ui_nb_lines2_99;
    SGLuint16 us_line_type2_99_0;
    SGLuint16 us_nb_vertex2_99_0;
    SGLfloat tf_points2_99_0[24UL];
    /* Char 100 */
    SGLuint32 ui_nb_lines2_100;
    SGLuint16 us_line_type2_100_0;
    SGLuint16 us_nb_vertex2_100_0;
    SGLfloat tf_points2_100_0[16UL];
    /* Char 101 */
    SGLuint32 ui_nb_lines2_101;
    SGLuint16 us_line_type2_101_0;
    SGLuint16 us_nb_vertex2_101_0;
    SGLfloat tf_points2_101_0[4UL];
    SGLuint16 us_line_type2_101_1;
    SGLuint16 us_nb_vertex2_101_1;
    SGLfloat tf_points2_101_1[8UL];
    /* Char 102 */
    SGLuint32 ui_nb_lines2_102;
    SGLuint16 us_line_type2_102_0;
    SGLuint16 us_nb_vertex2_102_0;
    SGLfloat tf_points2_102_0[4UL];
    SGLuint16 us_line_type2_102_1;
    SGLuint16 us_nb_vertex2_102_1;
    SGLfloat tf_points2_102_1[6UL];
    /* Char 103 */
    SGLuint32 ui_nb_lines2_103;
    SGLuint16 us_line_type2_103_0;
    SGLuint16 us_nb_vertex2_103_0;
    SGLfloat tf_points2_103_0[28UL];
    /* Char 104 */
    SGLuint32 ui_nb_lines2_104;
    SGLuint16 us_line_type2_104_0;
    SGLuint16 us_nb_vertex2_104_0;
    SGLfloat tf_points2_104_0[12UL];
    /* Char 105 */
    SGLuint32 ui_nb_lines2_105;
    SGLuint16 us_line_type2_105_0;
    SGLuint16 us_nb_vertex2_105_0;
    SGLfloat tf_points2_105_0[12UL];
    /* Char 106 */
    SGLuint32 ui_nb_lines2_106;
    SGLuint16 us_line_type2_106_0;
    SGLuint16 us_nb_vertex2_106_0;
    SGLfloat tf_points2_106_0[14UL];
    SGLuint16 us_line_type2_106_1;
    SGLuint16 us_nb_vertex2_106_1;
    SGLfloat tf_points2_106_1[4UL];
    /* Char 107 */
    SGLuint32 ui_nb_lines2_107;
    SGLuint16 us_line_type2_107_0;
    SGLuint16 us_nb_vertex2_107_0;
    SGLfloat tf_points2_107_0[12UL];
    /* Char 108 */
    SGLuint32 ui_nb_lines2_108;
    SGLuint16 us_line_type2_108_0;
    SGLuint16 us_nb_vertex2_108_0;
    SGLfloat tf_points2_108_0[6UL];
    /* Char 109 */
    SGLuint32 ui_nb_lines2_109;
    SGLuint16 us_line_type2_109_0;
    SGLuint16 us_nb_vertex2_109_0;
    SGLfloat tf_points2_109_0[10UL];
    /* Char 110 */
    SGLuint32 ui_nb_lines2_110;
    SGLuint16 us_line_type2_110_0;
    SGLuint16 us_nb_vertex2_110_0;
    SGLfloat tf_points2_110_0[8UL];
    /* Char 111 */
    SGLuint32 ui_nb_lines2_111;
    SGLuint16 us_line_type2_111_0;
    SGLuint16 us_nb_vertex2_111_0;
    SGLfloat tf_points2_111_0[32UL];
    /* Char 112 */
    SGLuint32 ui_nb_lines2_112;
    SGLuint16 us_line_type2_112_0;
    SGLuint16 us_nb_vertex2_112_0;
    SGLfloat tf_points2_112_0[18UL];
    /* Char 113 */
    SGLuint32 ui_nb_lines2_113;
    SGLuint16 us_line_type2_113_0;
    SGLuint16 us_nb_vertex2_113_0;
    SGLfloat tf_points2_113_0[4UL];
    SGLuint16 us_line_type2_113_1;
    SGLuint16 us_nb_vertex2_113_1;
    SGLfloat tf_points2_113_1[24UL];
    /* Char 114 */
    SGLuint32 ui_nb_lines2_114;
    SGLuint16 us_line_type2_114_0;
    SGLuint16 us_nb_vertex2_114_0;
    SGLfloat tf_points2_114_0[18UL];
    SGLuint16 us_line_type2_114_1;
    SGLuint16 us_nb_vertex2_114_1;
    SGLfloat tf_points2_114_1[4UL];
    /* Char 115 */
    SGLuint32 ui_nb_lines2_115;
    SGLuint16 us_line_type2_115_0;
    SGLuint16 us_nb_vertex2_115_0;
    SGLfloat tf_points2_115_0[32UL];
    /* Char 116 */
    SGLuint32 ui_nb_lines2_116;
    SGLuint16 us_line_type2_116_0;
    SGLuint16 us_nb_vertex2_116_0;
    SGLfloat tf_points2_116_0[8UL];
    /* Char 117 */
    SGLuint32 ui_nb_lines2_117;
    SGLuint16 us_line_type2_117_0;
    SGLuint16 us_nb_vertex2_117_0;
    SGLfloat tf_points2_117_0[16UL];
    /* Char 118 */
    SGLuint32 ui_nb_lines2_118;
    SGLuint16 us_line_type2_118_0;
    SGLuint16 us_nb_vertex2_118_0;
    SGLfloat tf_points2_118_0[10UL];
    /* Char 119 */
    SGLuint32 ui_nb_lines2_119;
    SGLuint16 us_line_type2_119_0;
    SGLuint16 us_nb_vertex2_119_0;
    SGLfloat tf_points2_119_0[10UL];
    /* Char 120 */
    SGLuint32 ui_nb_lines2_120;
    SGLuint16 us_line_type2_120_0;
    SGLuint16 us_nb_vertex2_120_0;
    SGLfloat tf_points2_120_0[8UL];
    SGLuint16 us_line_type2_120_1;
    SGLuint16 us_nb_vertex2_120_1;
    SGLfloat tf_points2_120_1[8UL];
    /* Char 121 */
    SGLuint32 ui_nb_lines2_121;
    SGLuint16 us_line_type2_121_0;
    SGLuint16 us_nb_vertex2_121_0;
    SGLfloat tf_points2_121_0[8UL];
    SGLuint16 us_line_type2_121_1;
    SGLuint16 us_nb_vertex2_121_1;
    SGLfloat tf_points2_121_1[6UL];
    /* Char 122 */
    SGLuint32 ui_nb_lines2_122;
    SGLuint16 us_line_type2_122_0;
    SGLuint16 us_nb_vertex2_122_0;
    SGLfloat tf_points2_122_0[8UL];
    /* Char 124 */
    SGLuint32 ui_nb_lines2_124;
    SGLuint16 us_line_type2_124_0;
    SGLuint16 us_nb_vertex2_124_0;
    SGLfloat tf_points2_124_0[4UL];
    /* Char 128 */
    SGLuint32 ui_nb_lines2_128;
    SGLuint16 us_line_type2_128_0;
    SGLuint16 us_nb_vertex2_128_0;
    SGLfloat tf_points2_128_0[6UL];
    /* Char 129 */
    SGLuint32 ui_nb_lines2_129;
    SGLuint16 us_line_type2_129_0;
    SGLuint16 us_nb_vertex2_129_0;
    SGLfloat tf_points2_129_0[12UL];
    /* Char 130 */
    SGLuint32 ui_nb_lines2_130;
    SGLuint16 us_line_type2_130_0;
    SGLuint16 us_nb_vertex2_130_0;
    SGLfloat tf_points2_130_0[8UL];
    /* Char 131 */
    SGLuint32 ui_nb_lines2_131;
    SGLuint16 us_line_type2_131_0;
    SGLuint16 us_nb_vertex2_131_0;
    SGLfloat tf_points2_131_0[8UL];
    /* Char 132 */
    SGLuint32 ui_nb_lines2_132;
    SGLuint16 us_line_type2_132_0;
    SGLuint16 us_nb_vertex2_132_0;
    SGLfloat tf_points2_132_0[4UL];
    SGLuint16 us_line_type2_132_1;
    SGLuint16 us_nb_vertex2_132_1;
    SGLfloat tf_points2_132_1[6UL];
    /* Char 133 */
    SGLuint32 ui_nb_lines2_133;
    SGLuint16 us_line_type2_133_0;
    SGLuint16 us_nb_vertex2_133_0;
    SGLfloat tf_points2_133_0[4UL];
    SGLuint16 us_line_type2_133_1;
    SGLuint16 us_nb_vertex2_133_1;
    SGLfloat tf_points2_133_1[6UL];
    /* Char 134 */
    SGLuint32 ui_nb_lines2_134;
    SGLuint16 us_line_type2_134_0;
    SGLuint16 us_nb_vertex2_134_0;
    SGLfloat tf_points2_134_0[4UL];
    SGLuint16 us_line_type2_134_1;
    SGLuint16 us_nb_vertex2_134_1;
    SGLfloat tf_points2_134_1[6UL];
    /* Char 135 */
    SGLuint32 ui_nb_lines2_135;
    SGLuint16 us_line_type2_135_0;
    SGLuint16 us_nb_vertex2_135_0;
    SGLfloat tf_points2_135_0[4UL];
    SGLuint16 us_line_type2_135_1;
    SGLuint16 us_nb_vertex2_135_1;
    SGLfloat tf_points2_135_1[6UL];
    /* Char 136 */
    SGLuint32 ui_nb_lines2_136;
    /* Char 160 */
    SGLuint32 ui_nb_lines2_160;
    SGLuint16 us_line_type2_160_0;
    SGLuint16 us_nb_vertex2_160_0;
    SGLfloat tf_points2_160_0[8UL];
    /* Char 161 */
    SGLuint32 ui_nb_lines2_161;
    SGLuint16 us_line_type2_161_0;
    SGLuint16 us_nb_vertex2_161_0;
    SGLfloat tf_points2_161_0[8UL];
    SGLuint16 us_line_type2_161_1;
    SGLuint16 us_nb_vertex2_161_1;
    SGLfloat tf_points2_161_1[14UL];
    /* Char 162 */
    SGLuint32 ui_nb_lines2_162;
    SGLuint16 us_line_type2_162_0;
    SGLuint16 us_nb_vertex2_162_0;
    SGLfloat tf_points2_162_0[14UL];
    /* Char 176 */
    SGLuint32 ui_nb_lines2_176;
    SGLuint16 us_line_type2_176_0;
    SGLuint16 us_nb_vertex2_176_0;
    SGLfloat tf_points2_176_0[12UL];
  } strokes2;
  /* Font T4 */
  struct {
    /* Char 255 */
    SGLuint32 ui_nb_lines3_255;
    SGLuint16 us_line_type3_255_0;
    SGLuint16 us_nb_vertex3_255_0;
    SGLfloat tf_points3_255_0[8UL];
    /* Char 32 */
    SGLuint32 ui_nb_lines3_32;
    /* Char 34 */
    SGLuint32 ui_nb_lines3_34;
    SGLuint16 us_line_type3_34_0;
    SGLuint16 us_nb_vertex3_34_0;
    SGLfloat tf_points3_34_0[8UL];
    /* Char 37 */
    SGLuint32 ui_nb_lines3_37;
    SGLuint16 us_line_type3_37_0;
    SGLuint16 us_nb_vertex3_37_0;
    SGLfloat tf_points3_37_0[4UL];
    SGLuint16 us_line_type3_37_1;
    SGLuint16 us_nb_vertex3_37_1;
    SGLfloat tf_points3_37_1[12UL];
    SGLuint16 us_line_type3_37_2;
    SGLuint16 us_nb_vertex3_37_2;
    SGLfloat tf_points3_37_2[12UL];
    /* Char 38 */
    SGLuint32 ui_nb_lines3_38;
    SGLuint16 us_line_type3_38_0;
    SGLuint16 us_nb_vertex3_38_0;
    SGLfloat tf_points3_38_0[28UL];
    /* Char 39 */
    SGLuint32 ui_nb_lines3_39;
    SGLuint16 us_line_type3_39_0;
    SGLuint16 us_nb_vertex3_39_0;
    SGLfloat tf_points3_39_0[4UL];
    /* Char 40 */
    SGLuint32 ui_nb_lines3_40;
    SGLuint16 us_line_type3_40_0;
    SGLuint16 us_nb_vertex3_40_0;
    SGLfloat tf_points3_40_0[8UL];
    /* Char 41 */
    SGLuint32 ui_nb_lines3_41;
    SGLuint16 us_line_type3_41_0;
    SGLuint16 us_nb_vertex3_41_0;
    SGLfloat tf_points3_41_0[8UL];
    /* Char 42 */
    SGLuint32 ui_nb_lines3_42;
    SGLuint16 us_line_type3_42_0;
    SGLuint16 us_nb_vertex3_42_0;
    SGLfloat tf_points3_42_0[12UL];
    /* Char 43 */
    SGLuint32 ui_nb_lines3_43;
    SGLuint16 us_line_type3_43_0;
    SGLuint16 us_nb_vertex3_43_0;
    SGLfloat tf_points3_43_0[8UL];
    /* Char 44 */
    SGLuint32 ui_nb_lines3_44;
    SGLuint16 us_line_type3_44_0;
    SGLuint16 us_nb_vertex3_44_0;
    SGLfloat tf_points3_44_0[4UL];
    /* Char 45 */
    SGLuint32 ui_nb_lines3_45;
    SGLuint16 us_line_type3_45_0;
    SGLuint16 us_nb_vertex3_45_0;
    SGLfloat tf_points3_45_0[4UL];
    /* Char 46 */
    SGLuint32 ui_nb_lines3_46;
    SGLuint16 us_line_type3_46_0;
    SGLuint16 us_nb_vertex3_46_0;
    SGLfloat tf_points3_46_0[8UL];
    /* Char 47 */
    SGLuint32 ui_nb_lines3_47;
    SGLuint16 us_line_type3_47_0;
    SGLuint16 us_nb_vertex3_47_0;
    SGLfloat tf_points3_47_0[4UL];
    /* Char 48 */
    SGLuint32 ui_nb_lines3_48;
    SGLuint16 us_line_type3_48_0;
    SGLuint16 us_nb_vertex3_48_0;
    SGLfloat tf_points3_48_0[24UL];
    /* Char 49 */
    SGLuint32 ui_nb_lines3_49;
    SGLuint16 us_line_type3_49_0;
    SGLuint16 us_nb_vertex3_49_0;
    SGLfloat tf_points3_49_0[4UL];
    SGLuint16 us_line_type3_49_1;
    SGLuint16 us_nb_vertex3_49_1;
    SGLfloat tf_points3_49_1[6UL];
    /* Char 50 */
    SGLuint32 ui_nb_lines3_50;
    SGLuint16 us_line_type3_50_0;
    SGLuint16 us_nb_vertex3_50_0;
    SGLfloat tf_points3_50_0[22UL];
    /* Char 51 */
    SGLuint32 ui_nb_lines3_51;
    SGLuint16 us_line_type3_51_0;
    SGLuint16 us_nb_vertex3_51_0;
    SGLfloat tf_points3_51_0[30UL];
    /* Char 52 */
    SGLuint32 ui_nb_lines3_52;
    SGLuint16 us_line_type3_52_0;
    SGLuint16 us_nb_vertex3_52_0;
    SGLfloat tf_points3_52_0[8UL];
    /* Char 53 */
    SGLuint32 ui_nb_lines3_53;
    SGLuint16 us_line_type3_53_0;
    SGLuint16 us_nb_vertex3_53_0;
    SGLfloat tf_points3_53_0[22UL];
    /* Char 54 */
    SGLuint32 ui_nb_lines3_54;
    SGLuint16 us_line_type3_54_0;
    SGLuint16 us_nb_vertex3_54_0;
    SGLfloat tf_points3_54_0[32UL];
    /* Char 55 */
    SGLuint32 ui_nb_lines3_55;
    SGLuint16 us_line_type3_55_0;
    SGLuint16 us_nb_vertex3_55_0;
    SGLfloat tf_points3_55_0[8UL];
    /* Char 56 */
    SGLuint32 ui_nb_lines3_56;
    SGLuint16 us_line_type3_56_0;
    SGLuint16 us_nb_vertex3_56_0;
    SGLfloat tf_points3_56_0[44UL];
    /* Char 57 */
    SGLuint32 ui_nb_lines3_57;
    SGLuint16 us_line_type3_57_0;
    SGLuint16 us_nb_vertex3_57_0;
    SGLfloat tf_points3_57_0[32UL];
    /* Char 58 */
    SGLuint32 ui_nb_lines3_58;
    SGLuint16 us_line_type3_58_0;
    SGLuint16 us_nb_vertex3_58_0;
    SGLfloat tf_points3_58_0[8UL];
    SGLuint16 us_line_type3_58_1;
    SGLuint16 us_nb_vertex3_58_1;
    SGLfloat tf_points3_58_1[8UL];
    /* Char 59 */
    SGLuint32 ui_nb_lines3_59;
    SGLuint16 us_line_type3_59_0;
    SGLuint16 us_nb_vertex3_59_0;
    SGLfloat tf_points3_59_0[8UL];
    SGLuint16 us_line_type3_59_1;
    SGLuint16 us_nb_vertex3_59_1;
    SGLfloat tf_points3_59_1[12UL];
    /* Char 60 */
    SGLuint32 ui_nb_lines3_60;
    SGLuint16 us_line_type3_60_0;
    SGLuint16 us_nb_vertex3_60_0;
    SGLfloat tf_points3_60_0[6UL];
    /* Char 61 */
    SGLuint32 ui_nb_lines3_61;
    SGLuint16 us_line_type3_61_0;
    SGLuint16 us_nb_vertex3_61_0;
    SGLfloat tf_points3_61_0[8UL];
    /* Char 62 */
    SGLuint32 ui_nb_lines3_62;
    SGLuint16 us_line_type3_62_0;
    SGLuint16 us_nb_vertex3_62_0;
    SGLfloat tf_points3_62_0[6UL];
    /* Char 63 */
    SGLuint32 ui_nb_lines3_63;
    SGLuint16 us_line_type3_63_0;
    SGLuint16 us_nb_vertex3_63_0;
    SGLfloat tf_points3_63_0[20UL];
    SGLuint16 us_line_type3_63_1;
    SGLuint16 us_nb_vertex3_63_1;
    SGLfloat tf_points3_63_1[8UL];
    /* Char 64 */
    SGLuint32 ui_nb_lines3_64;
    SGLuint16 us_line_type3_64_0;
    SGLuint16 us_nb_vertex3_64_0;
    SGLfloat tf_points3_64_0[42UL];
    /* Char 65 */
    SGLuint32 ui_nb_lines3_65;
    SGLuint16 us_line_type3_65_0;
    SGLuint16 us_nb_vertex3_65_0;
    SGLfloat tf_points3_65_0[10UL];
    SGLuint16 us_line_type3_65_1;
    SGLuint16 us_nb_vertex3_65_1;
    SGLfloat tf_points3_65_1[4UL];
    /* Char 66 */
    SGLuint32 ui_nb_lines3_66;
    SGLuint16 us_line_type3_66_0;
    SGLuint16 us_nb_vertex3_66_0;
    SGLfloat tf_points3_66_0[30UL];
    /* Char 67 */
    SGLuint32 ui_nb_lines3_67;
    SGLuint16 us_line_type3_67_0;
    SGLuint16 us_nb_vertex3_67_0;
    SGLfloat tf_points3_67_0[24UL];
    /* Char 68 */
    SGLuint32 ui_nb_lines3_68;
    SGLuint16 us_line_type3_68_0;
    SGLuint16 us_nb_vertex3_68_0;
    SGLfloat tf_points3_68_0[16UL];
    /* Char 69 */
    SGLuint32 ui_nb_lines3_69;
    SGLuint16 us_line_type3_69_0;
    SGLuint16 us_nb_vertex3_69_0;
    SGLfloat tf_points3_69_0[4UL];
    SGLuint16 us_line_type3_69_1;
    SGLuint16 us_nb_vertex3_69_1;
    SGLfloat tf_points3_69_1[8UL];
    /* Char 70 */
    SGLuint32 ui_nb_lines3_70;
    SGLuint16 us_line_type3_70_0;
    SGLuint16 us_nb_vertex3_70_0;
    SGLfloat tf_points3_70_0[4UL];
    SGLuint16 us_line_type3_70_1;
    SGLuint16 us_nb_vertex3_70_1;
    SGLfloat tf_points3_70_1[6UL];
    /* Char 71 */
    SGLuint32 ui_nb_lines3_71;
    SGLuint16 us_line_type3_71_0;
    SGLuint16 us_nb_vertex3_71_0;
    SGLfloat tf_points3_71_0[28UL];
    /* Char 72 */
    SGLuint32 ui_nb_lines3_72;
    SGLuint16 us_line_type3_72_0;
    SGLuint16 us_nb_vertex3_72_0;
    SGLfloat tf_points3_72_0[12UL];
    /* Char 73 */
    SGLuint32 ui_nb_lines3_73;
    SGLuint16 us_line_type3_73_0;
    SGLuint16 us_nb_vertex3_73_0;
    SGLfloat tf_points3_73_0[12UL];
    /* Char 74 */
    SGLuint32 ui_nb_lines3_74;
    SGLuint16 us_line_type3_74_0;
    SGLuint16 us_nb_vertex3_74_0;
    SGLfloat tf_points3_74_0[14UL];
    SGLuint16 us_line_type3_74_1;
    SGLuint16 us_nb_vertex3_74_1;
    SGLfloat tf_points3_74_1[4UL];
    /* Char 75 */
    SGLuint32 ui_nb_lines3_75;
    SGLuint16 us_line_type3_75_0;
    SGLuint16 us_nb_vertex3_75_0;
    SGLfloat tf_points3_75_0[12UL];
    /* Char 76 */
    SGLuint32 ui_nb_lines3_76;
    SGLuint16 us_line_type3_76_0;
    SGLuint16 us_nb_vertex3_76_0;
    SGLfloat tf_points3_76_0[6UL];
    /* Char 77 */
    SGLuint32 ui_nb_lines3_77;
    SGLuint16 us_line_type3_77_0;
    SGLuint16 us_nb_vertex3_77_0;
    SGLfloat tf_points3_77_0[10UL];
    /* Char 78 */
    SGLuint32 ui_nb_lines3_78;
    SGLuint16 us_line_type3_78_0;
    SGLuint16 us_nb_vertex3_78_0;
    SGLfloat tf_points3_78_0[8UL];
    /* Char 79 */
    SGLuint32 ui_nb_lines3_79;
    SGLuint16 us_line_type3_79_0;
    SGLuint16 us_nb_vertex3_79_0;
    SGLfloat tf_points3_79_0[32UL];
    /* Char 80 */
    SGLuint32 ui_nb_lines3_80;
    SGLuint16 us_line_type3_80_0;
    SGLuint16 us_nb_vertex3_80_0;
    SGLfloat tf_points3_80_0[18UL];
    /* Char 81 */
    SGLuint32 ui_nb_lines3_81;
    SGLuint16 us_line_type3_81_0;
    SGLuint16 us_nb_vertex3_81_0;
    SGLfloat tf_points3_81_0[4UL];
    SGLuint16 us_line_type3_81_1;
    SGLuint16 us_nb_vertex3_81_1;
    SGLfloat tf_points3_81_1[24UL];
    /* Char 82 */
    SGLuint32 ui_nb_lines3_82;
    SGLuint16 us_line_type3_82_0;
    SGLuint16 us_nb_vertex3_82_0;
    SGLfloat tf_points3_82_0[18UL];
    SGLuint16 us_line_type3_82_1;
    SGLuint16 us_nb_vertex3_82_1;
    SGLfloat tf_points3_82_1[4UL];
    /* Char 83 */
    SGLuint32 ui_nb_lines3_83;
    SGLuint16 us_line_type3_83_0;
    SGLuint16 us_nb_vertex3_83_0;
    SGLfloat tf_points3_83_0[32UL];
    /* Char 84 */
    SGLuint32 ui_nb_lines3_84;
    SGLuint16 us_line_type3_84_0;
    SGLuint16 us_nb_vertex3_84_0;
    SGLfloat tf_points3_84_0[8UL];
    /* Char 85 */
    SGLuint32 ui_nb_lines3_85;
    SGLuint16 us_line_type3_85_0;
    SGLuint16 us_nb_vertex3_85_0;
    SGLfloat tf_points3_85_0[16UL];
    /* Char 86 */
    SGLuint32 ui_nb_lines3_86;
    SGLuint16 us_line_type3_86_0;
    SGLuint16 us_nb_vertex3_86_0;
    SGLfloat tf_points3_86_0[10UL];
    /* Char 87 */
    SGLuint32 ui_nb_lines3_87;
    SGLuint16 us_line_type3_87_0;
    SGLuint16 us_nb_vertex3_87_0;
    SGLfloat tf_points3_87_0[10UL];
    /* Char 88 */
    SGLuint32 ui_nb_lines3_88;
    SGLuint16 us_line_type3_88_0;
    SGLuint16 us_nb_vertex3_88_0;
    SGLfloat tf_points3_88_0[8UL];
    SGLuint16 us_line_type3_88_1;
    SGLuint16 us_nb_vertex3_88_1;
    SGLfloat tf_points3_88_1[8UL];
    /* Char 89 */
    SGLuint32 ui_nb_lines3_89;
    SGLuint16 us_line_type3_89_0;
    SGLuint16 us_nb_vertex3_89_0;
    SGLfloat tf_points3_89_0[8UL];
    SGLuint16 us_line_type3_89_1;
    SGLuint16 us_nb_vertex3_89_1;
    SGLfloat tf_points3_89_1[6UL];
    /* Char 90 */
    SGLuint32 ui_nb_lines3_90;
    SGLuint16 us_line_type3_90_0;
    SGLuint16 us_nb_vertex3_90_0;
    SGLfloat tf_points3_90_0[8UL];
    /* Char 91 */
    SGLuint32 ui_nb_lines3_91;
    SGLuint16 us_line_type3_91_0;
    SGLuint16 us_nb_vertex3_91_0;
    SGLfloat tf_points3_91_0[12UL];
    /* Char 92 */
    SGLuint32 ui_nb_lines3_92;
    SGLuint16 us_line_type3_92_0;
    SGLuint16 us_nb_vertex3_92_0;
    SGLfloat tf_points3_92_0[4UL];
    /* Char 93 */
    SGLuint32 ui_nb_lines3_93;
    SGLuint16 us_line_type3_93_0;
    SGLuint16 us_nb_vertex3_93_0;
    SGLfloat tf_points3_93_0[12UL];
    /* Char 95 */
    SGLuint32 ui_nb_lines3_95;
    SGLuint16 us_line_type3_95_0;
    SGLuint16 us_nb_vertex3_95_0;
    SGLfloat tf_points3_95_0[4UL];
    /* Char 97 */
    SGLuint32 ui_nb_lines3_97;
    SGLuint16 us_line_type3_97_0;
    SGLuint16 us_nb_vertex3_97_0;
    SGLfloat tf_points3_97_0[10UL];
    SGLuint16 us_line_type3_97_1;
    SGLuint16 us_nb_vertex3_97_1;
    SGLfloat tf_points3_97_1[4UL];
    /* Char 98 */
    SGLuint32 ui_nb_lines3_98;
    SGLuint16 us_line_type3_98_0;
    SGLuint16 us_nb_vertex3_98_0;
    SGLfloat tf_points3_98_0[30UL];
    /* Char 99 */
    SGLuint32 ui_nb_lines3_99;
    SGLuint16 us_line_type3_99_0;
    SGLuint16 us_nb_vertex3_99_0;
    SGLfloat tf_points3_99_0[24UL];
    /* Char 100 */
    SGLuint32 ui_nb_lines3_100;
    SGLuint16 us_line_type3_100_0;
    SGLuint16 us_nb_vertex3_100_0;
    SGLfloat tf_points3_100_0[16UL];
    /* Char 101 */
    SGLuint32 ui_nb_lines3_101;
    SGLuint16 us_line_type3_101_0;
    SGLuint16 us_nb_vertex3_101_0;
    SGLfloat tf_points3_101_0[4UL];
    SGLuint16 us_line_type3_101_1;
    SGLuint16 us_nb_vertex3_101_1;
    SGLfloat tf_points3_101_1[8UL];
    /* Char 102 */
    SGLuint32 ui_nb_lines3_102;
    SGLuint16 us_line_type3_102_0;
    SGLuint16 us_nb_vertex3_102_0;
    SGLfloat tf_points3_102_0[4UL];
    SGLuint16 us_line_type3_102_1;
    SGLuint16 us_nb_vertex3_102_1;
    SGLfloat tf_points3_102_1[6UL];
    /* Char 103 */
    SGLuint32 ui_nb_lines3_103;
    SGLuint16 us_line_type3_103_0;
    SGLuint16 us_nb_vertex3_103_0;
    SGLfloat tf_points3_103_0[28UL];
    /* Char 104 */
    SGLuint32 ui_nb_lines3_104;
    SGLuint16 us_line_type3_104_0;
    SGLuint16 us_nb_vertex3_104_0;
    SGLfloat tf_points3_104_0[12UL];
    /* Char 105 */
    SGLuint32 ui_nb_lines3_105;
    SGLuint16 us_line_type3_105_0;
    SGLuint16 us_nb_vertex3_105_0;
    SGLfloat tf_points3_105_0[12UL];
    /* Char 106 */
    SGLuint32 ui_nb_lines3_106;
    SGLuint16 us_line_type3_106_0;
    SGLuint16 us_nb_vertex3_106_0;
    SGLfloat tf_points3_106_0[14UL];
    SGLuint16 us_line_type3_106_1;
    SGLuint16 us_nb_vertex3_106_1;
    SGLfloat tf_points3_106_1[4UL];
    /* Char 107 */
    SGLuint32 ui_nb_lines3_107;
    SGLuint16 us_line_type3_107_0;
    SGLuint16 us_nb_vertex3_107_0;
    SGLfloat tf_points3_107_0[12UL];
    /* Char 108 */
    SGLuint32 ui_nb_lines3_108;
    SGLuint16 us_line_type3_108_0;
    SGLuint16 us_nb_vertex3_108_0;
    SGLfloat tf_points3_108_0[6UL];
    /* Char 109 */
    SGLuint32 ui_nb_lines3_109;
    SGLuint16 us_line_type3_109_0;
    SGLuint16 us_nb_vertex3_109_0;
    SGLfloat tf_points3_109_0[10UL];
    /* Char 110 */
    SGLuint32 ui_nb_lines3_110;
    SGLuint16 us_line_type3_110_0;
    SGLuint16 us_nb_vertex3_110_0;
    SGLfloat tf_points3_110_0[8UL];
    /* Char 111 */
    SGLuint32 ui_nb_lines3_111;
    SGLuint16 us_line_type3_111_0;
    SGLuint16 us_nb_vertex3_111_0;
    SGLfloat tf_points3_111_0[32UL];
    /* Char 112 */
    SGLuint32 ui_nb_lines3_112;
    SGLuint16 us_line_type3_112_0;
    SGLuint16 us_nb_vertex3_112_0;
    SGLfloat tf_points3_112_0[18UL];
    /* Char 113 */
    SGLuint32 ui_nb_lines3_113;
    SGLuint16 us_line_type3_113_0;
    SGLuint16 us_nb_vertex3_113_0;
    SGLfloat tf_points3_113_0[4UL];
    SGLuint16 us_line_type3_113_1;
    SGLuint16 us_nb_vertex3_113_1;
    SGLfloat tf_points3_113_1[24UL];
    /* Char 114 */
    SGLuint32 ui_nb_lines3_114;
    SGLuint16 us_line_type3_114_0;
    SGLuint16 us_nb_vertex3_114_0;
    SGLfloat tf_points3_114_0[18UL];
    SGLuint16 us_line_type3_114_1;
    SGLuint16 us_nb_vertex3_114_1;
    SGLfloat tf_points3_114_1[4UL];
    /* Char 115 */
    SGLuint32 ui_nb_lines3_115;
    SGLuint16 us_line_type3_115_0;
    SGLuint16 us_nb_vertex3_115_0;
    SGLfloat tf_points3_115_0[32UL];
    /* Char 116 */
    SGLuint32 ui_nb_lines3_116;
    SGLuint16 us_line_type3_116_0;
    SGLuint16 us_nb_vertex3_116_0;
    SGLfloat tf_points3_116_0[8UL];
    /* Char 117 */
    SGLuint32 ui_nb_lines3_117;
    SGLuint16 us_line_type3_117_0;
    SGLuint16 us_nb_vertex3_117_0;
    SGLfloat tf_points3_117_0[16UL];
    /* Char 118 */
    SGLuint32 ui_nb_lines3_118;
    SGLuint16 us_line_type3_118_0;
    SGLuint16 us_nb_vertex3_118_0;
    SGLfloat tf_points3_118_0[10UL];
    /* Char 119 */
    SGLuint32 ui_nb_lines3_119;
    SGLuint16 us_line_type3_119_0;
    SGLuint16 us_nb_vertex3_119_0;
    SGLfloat tf_points3_119_0[10UL];
    /* Char 120 */
    SGLuint32 ui_nb_lines3_120;
    SGLuint16 us_line_type3_120_0;
    SGLuint16 us_nb_vertex3_120_0;
    SGLfloat tf_points3_120_0[8UL];
    SGLuint16 us_line_type3_120_1;
    SGLuint16 us_nb_vertex3_120_1;
    SGLfloat tf_points3_120_1[8UL];
    /* Char 121 */
    SGLuint32 ui_nb_lines3_121;
    SGLuint16 us_line_type3_121_0;
    SGLuint16 us_nb_vertex3_121_0;
    SGLfloat tf_points3_121_0[8UL];
    SGLuint16 us_line_type3_121_1;
    SGLuint16 us_nb_vertex3_121_1;
    SGLfloat tf_points3_121_1[6UL];
    /* Char 122 */
    SGLuint32 ui_nb_lines3_122;
    SGLuint16 us_line_type3_122_0;
    SGLuint16 us_nb_vertex3_122_0;
    SGLfloat tf_points3_122_0[8UL];
    /* Char 124 */
    SGLuint32 ui_nb_lines3_124;
    SGLuint16 us_line_type3_124_0;
    SGLuint16 us_nb_vertex3_124_0;
    SGLfloat tf_points3_124_0[4UL];
    /* Char 128 */
    SGLuint32 ui_nb_lines3_128;
    SGLuint16 us_line_type3_128_0;
    SGLuint16 us_nb_vertex3_128_0;
    SGLfloat tf_points3_128_0[6UL];
    /* Char 129 */
    SGLuint32 ui_nb_lines3_129;
    SGLuint16 us_line_type3_129_0;
    SGLuint16 us_nb_vertex3_129_0;
    SGLfloat tf_points3_129_0[12UL];
    /* Char 130 */
    SGLuint32 ui_nb_lines3_130;
    SGLuint16 us_line_type3_130_0;
    SGLuint16 us_nb_vertex3_130_0;
    SGLfloat tf_points3_130_0[8UL];
    /* Char 131 */
    SGLuint32 ui_nb_lines3_131;
    SGLuint16 us_line_type3_131_0;
    SGLuint16 us_nb_vertex3_131_0;
    SGLfloat tf_points3_131_0[8UL];
    /* Char 132 */
    SGLuint32 ui_nb_lines3_132;
    SGLuint16 us_line_type3_132_0;
    SGLuint16 us_nb_vertex3_132_0;
    SGLfloat tf_points3_132_0[4UL];
    SGLuint16 us_line_type3_132_1;
    SGLuint16 us_nb_vertex3_132_1;
    SGLfloat tf_points3_132_1[6UL];
    /* Char 133 */
    SGLuint32 ui_nb_lines3_133;
    SGLuint16 us_line_type3_133_0;
    SGLuint16 us_nb_vertex3_133_0;
    SGLfloat tf_points3_133_0[4UL];
    SGLuint16 us_line_type3_133_1;
    SGLuint16 us_nb_vertex3_133_1;
    SGLfloat tf_points3_133_1[6UL];
    /* Char 134 */
    SGLuint32 ui_nb_lines3_134;
    SGLuint16 us_line_type3_134_0;
    SGLuint16 us_nb_vertex3_134_0;
    SGLfloat tf_points3_134_0[4UL];
    SGLuint16 us_line_type3_134_1;
    SGLuint16 us_nb_vertex3_134_1;
    SGLfloat tf_points3_134_1[6UL];
    /* Char 135 */
    SGLuint32 ui_nb_lines3_135;
    SGLuint16 us_line_type3_135_0;
    SGLuint16 us_nb_vertex3_135_0;
    SGLfloat tf_points3_135_0[4UL];
    SGLuint16 us_line_type3_135_1;
    SGLuint16 us_nb_vertex3_135_1;
    SGLfloat tf_points3_135_1[6UL];
    /* Char 136 */
    SGLuint32 ui_nb_lines3_136;
    /* Char 160 */
    SGLuint32 ui_nb_lines3_160;
    SGLuint16 us_line_type3_160_0;
    SGLuint16 us_nb_vertex3_160_0;
    SGLfloat tf_points3_160_0[8UL];
    /* Char 161 */
    SGLuint32 ui_nb_lines3_161;
    SGLuint16 us_line_type3_161_0;
    SGLuint16 us_nb_vertex3_161_0;
    SGLfloat tf_points3_161_0[8UL];
    SGLuint16 us_line_type3_161_1;
    SGLuint16 us_nb_vertex3_161_1;
    SGLfloat tf_points3_161_1[14UL];
    /* Char 162 */
    SGLuint32 ui_nb_lines3_162;
    SGLuint16 us_line_type3_162_0;
    SGLuint16 us_nb_vertex3_162_0;
    SGLfloat tf_points3_162_0[14UL];
    /* Char 176 */
    SGLuint32 ui_nb_lines3_176;
    SGLuint16 us_line_type3_176_0;
    SGLuint16 us_nb_vertex3_176_0;
    SGLfloat tf_points3_176_0[12UL];
  } strokes3;
  /* Font T5 */
  struct {
    /* Char 255 */
    SGLuint32 ui_nb_lines4_255;
    SGLuint16 us_line_type4_255_0;
    SGLuint16 us_nb_vertex4_255_0;
    SGLfloat tf_points4_255_0[8UL];
    /* Char 32 */
    SGLuint32 ui_nb_lines4_32;
    /* Char 34 */
    SGLuint32 ui_nb_lines4_34;
    SGLuint16 us_line_type4_34_0;
    SGLuint16 us_nb_vertex4_34_0;
    SGLfloat tf_points4_34_0[8UL];
    /* Char 37 */
    SGLuint32 ui_nb_lines4_37;
    SGLuint16 us_line_type4_37_0;
    SGLuint16 us_nb_vertex4_37_0;
    SGLfloat tf_points4_37_0[4UL];
    SGLuint16 us_line_type4_37_1;
    SGLuint16 us_nb_vertex4_37_1;
    SGLfloat tf_points4_37_1[12UL];
    SGLuint16 us_line_type4_37_2;
    SGLuint16 us_nb_vertex4_37_2;
    SGLfloat tf_points4_37_2[12UL];
    /* Char 38 */
    SGLuint32 ui_nb_lines4_38;
    SGLuint16 us_line_type4_38_0;
    SGLuint16 us_nb_vertex4_38_0;
    SGLfloat tf_points4_38_0[28UL];
    /* Char 39 */
    SGLuint32 ui_nb_lines4_39;
    SGLuint16 us_line_type4_39_0;
    SGLuint16 us_nb_vertex4_39_0;
    SGLfloat tf_points4_39_0[4UL];
    /* Char 40 */
    SGLuint32 ui_nb_lines4_40;
    SGLuint16 us_line_type4_40_0;
    SGLuint16 us_nb_vertex4_40_0;
    SGLfloat tf_points4_40_0[8UL];
    /* Char 41 */
    SGLuint32 ui_nb_lines4_41;
    SGLuint16 us_line_type4_41_0;
    SGLuint16 us_nb_vertex4_41_0;
    SGLfloat tf_points4_41_0[8UL];
    /* Char 42 */
    SGLuint32 ui_nb_lines4_42;
    SGLuint16 us_line_type4_42_0;
    SGLuint16 us_nb_vertex4_42_0;
    SGLfloat tf_points4_42_0[12UL];
    /* Char 43 */
    SGLuint32 ui_nb_lines4_43;
    SGLuint16 us_line_type4_43_0;
    SGLuint16 us_nb_vertex4_43_0;
    SGLfloat tf_points4_43_0[8UL];
    /* Char 44 */
    SGLuint32 ui_nb_lines4_44;
    SGLuint16 us_line_type4_44_0;
    SGLuint16 us_nb_vertex4_44_0;
    SGLfloat tf_points4_44_0[4UL];
    /* Char 45 */
    SGLuint32 ui_nb_lines4_45;
    SGLuint16 us_line_type4_45_0;
    SGLuint16 us_nb_vertex4_45_0;
    SGLfloat tf_points4_45_0[4UL];
    /* Char 46 */
    SGLuint32 ui_nb_lines4_46;
    SGLuint16 us_line_type4_46_0;
    SGLuint16 us_nb_vertex4_46_0;
    SGLfloat tf_points4_46_0[8UL];
    /* Char 47 */
    SGLuint32 ui_nb_lines4_47;
    SGLuint16 us_line_type4_47_0;
    SGLuint16 us_nb_vertex4_47_0;
    SGLfloat tf_points4_47_0[4UL];
    /* Char 48 */
    SGLuint32 ui_nb_lines4_48;
    SGLuint16 us_line_type4_48_0;
    SGLuint16 us_nb_vertex4_48_0;
    SGLfloat tf_points4_48_0[24UL];
    /* Char 49 */
    SGLuint32 ui_nb_lines4_49;
    SGLuint16 us_line_type4_49_0;
    SGLuint16 us_nb_vertex4_49_0;
    SGLfloat tf_points4_49_0[4UL];
    SGLuint16 us_line_type4_49_1;
    SGLuint16 us_nb_vertex4_49_1;
    SGLfloat tf_points4_49_1[6UL];
    /* Char 50 */
    SGLuint32 ui_nb_lines4_50;
    SGLuint16 us_line_type4_50_0;
    SGLuint16 us_nb_vertex4_50_0;
    SGLfloat tf_points4_50_0[22UL];
    /* Char 51 */
    SGLuint32 ui_nb_lines4_51;
    SGLuint16 us_line_type4_51_0;
    SGLuint16 us_nb_vertex4_51_0;
    SGLfloat tf_points4_51_0[30UL];
    /* Char 52 */
    SGLuint32 ui_nb_lines4_52;
    SGLuint16 us_line_type4_52_0;
    SGLuint16 us_nb_vertex4_52_0;
    SGLfloat tf_points4_52_0[8UL];
    /* Char 53 */
    SGLuint32 ui_nb_lines4_53;
    SGLuint16 us_line_type4_53_0;
    SGLuint16 us_nb_vertex4_53_0;
    SGLfloat tf_points4_53_0[22UL];
    /* Char 54 */
    SGLuint32 ui_nb_lines4_54;
    SGLuint16 us_line_type4_54_0;
    SGLuint16 us_nb_vertex4_54_0;
    SGLfloat tf_points4_54_0[32UL];
    /* Char 55 */
    SGLuint32 ui_nb_lines4_55;
    SGLuint16 us_line_type4_55_0;
    SGLuint16 us_nb_vertex4_55_0;
    SGLfloat tf_points4_55_0[8UL];
    /* Char 56 */
    SGLuint32 ui_nb_lines4_56;
    SGLuint16 us_line_type4_56_0;
    SGLuint16 us_nb_vertex4_56_0;
    SGLfloat tf_points4_56_0[44UL];
    /* Char 57 */
    SGLuint32 ui_nb_lines4_57;
    SGLuint16 us_line_type4_57_0;
    SGLuint16 us_nb_vertex4_57_0;
    SGLfloat tf_points4_57_0[32UL];
    /* Char 58 */
    SGLuint32 ui_nb_lines4_58;
    SGLuint16 us_line_type4_58_0;
    SGLuint16 us_nb_vertex4_58_0;
    SGLfloat tf_points4_58_0[8UL];
    SGLuint16 us_line_type4_58_1;
    SGLuint16 us_nb_vertex4_58_1;
    SGLfloat tf_points4_58_1[8UL];
    /* Char 59 */
    SGLuint32 ui_nb_lines4_59;
    SGLuint16 us_line_type4_59_0;
    SGLuint16 us_nb_vertex4_59_0;
    SGLfloat tf_points4_59_0[8UL];
    SGLuint16 us_line_type4_59_1;
    SGLuint16 us_nb_vertex4_59_1;
    SGLfloat tf_points4_59_1[12UL];
    /* Char 60 */
    SGLuint32 ui_nb_lines4_60;
    SGLuint16 us_line_type4_60_0;
    SGLuint16 us_nb_vertex4_60_0;
    SGLfloat tf_points4_60_0[6UL];
    /* Char 61 */
    SGLuint32 ui_nb_lines4_61;
    SGLuint16 us_line_type4_61_0;
    SGLuint16 us_nb_vertex4_61_0;
    SGLfloat tf_points4_61_0[8UL];
    /* Char 62 */
    SGLuint32 ui_nb_lines4_62;
    SGLuint16 us_line_type4_62_0;
    SGLuint16 us_nb_vertex4_62_0;
    SGLfloat tf_points4_62_0[6UL];
    /* Char 63 */
    SGLuint32 ui_nb_lines4_63;
    SGLuint16 us_line_type4_63_0;
    SGLuint16 us_nb_vertex4_63_0;
    SGLfloat tf_points4_63_0[22UL];
    SGLuint16 us_line_type4_63_1;
    SGLuint16 us_nb_vertex4_63_1;
    SGLfloat tf_points4_63_1[8UL];
    /* Char 64 */
    SGLuint32 ui_nb_lines4_64;
    SGLuint16 us_line_type4_64_0;
    SGLuint16 us_nb_vertex4_64_0;
    SGLfloat tf_points4_64_0[40UL];
    /* Char 65 */
    SGLuint32 ui_nb_lines4_65;
    SGLuint16 us_line_type4_65_0;
    SGLuint16 us_nb_vertex4_65_0;
    SGLfloat tf_points4_65_0[10UL];
    SGLuint16 us_line_type4_65_1;
    SGLuint16 us_nb_vertex4_65_1;
    SGLfloat tf_points4_65_1[4UL];
    /* Char 66 */
    SGLuint32 ui_nb_lines4_66;
    SGLuint16 us_line_type4_66_0;
    SGLuint16 us_nb_vertex4_66_0;
    SGLfloat tf_points4_66_0[30UL];
    /* Char 67 */
    SGLuint32 ui_nb_lines4_67;
    SGLuint16 us_line_type4_67_0;
    SGLuint16 us_nb_vertex4_67_0;
    SGLfloat tf_points4_67_0[24UL];
    /* Char 68 */
    SGLuint32 ui_nb_lines4_68;
    SGLuint16 us_line_type4_68_0;
    SGLuint16 us_nb_vertex4_68_0;
    SGLfloat tf_points4_68_0[16UL];
    /* Char 69 */
    SGLuint32 ui_nb_lines4_69;
    SGLuint16 us_line_type4_69_0;
    SGLuint16 us_nb_vertex4_69_0;
    SGLfloat tf_points4_69_0[4UL];
    SGLuint16 us_line_type4_69_1;
    SGLuint16 us_nb_vertex4_69_1;
    SGLfloat tf_points4_69_1[8UL];
    /* Char 70 */
    SGLuint32 ui_nb_lines4_70;
    SGLuint16 us_line_type4_70_0;
    SGLuint16 us_nb_vertex4_70_0;
    SGLfloat tf_points4_70_0[4UL];
    SGLuint16 us_line_type4_70_1;
    SGLuint16 us_nb_vertex4_70_1;
    SGLfloat tf_points4_70_1[6UL];
    /* Char 71 */
    SGLuint32 ui_nb_lines4_71;
    SGLuint16 us_line_type4_71_0;
    SGLuint16 us_nb_vertex4_71_0;
    SGLfloat tf_points4_71_0[28UL];
    /* Char 72 */
    SGLuint32 ui_nb_lines4_72;
    SGLuint16 us_line_type4_72_0;
    SGLuint16 us_nb_vertex4_72_0;
    SGLfloat tf_points4_72_0[12UL];
    /* Char 73 */
    SGLuint32 ui_nb_lines4_73;
    SGLuint16 us_line_type4_73_0;
    SGLuint16 us_nb_vertex4_73_0;
    SGLfloat tf_points4_73_0[12UL];
    /* Char 74 */
    SGLuint32 ui_nb_lines4_74;
    SGLuint16 us_line_type4_74_0;
    SGLuint16 us_nb_vertex4_74_0;
    SGLfloat tf_points4_74_0[14UL];
    SGLuint16 us_line_type4_74_1;
    SGLuint16 us_nb_vertex4_74_1;
    SGLfloat tf_points4_74_1[4UL];
    /* Char 75 */
    SGLuint32 ui_nb_lines4_75;
    SGLuint16 us_line_type4_75_0;
    SGLuint16 us_nb_vertex4_75_0;
    SGLfloat tf_points4_75_0[12UL];
    /* Char 76 */
    SGLuint32 ui_nb_lines4_76;
    SGLuint16 us_line_type4_76_0;
    SGLuint16 us_nb_vertex4_76_0;
    SGLfloat tf_points4_76_0[6UL];
    /* Char 77 */
    SGLuint32 ui_nb_lines4_77;
    SGLuint16 us_line_type4_77_0;
    SGLuint16 us_nb_vertex4_77_0;
    SGLfloat tf_points4_77_0[10UL];
    /* Char 78 */
    SGLuint32 ui_nb_lines4_78;
    SGLuint16 us_line_type4_78_0;
    SGLuint16 us_nb_vertex4_78_0;
    SGLfloat tf_points4_78_0[8UL];
    /* Char 79 */
    SGLuint32 ui_nb_lines4_79;
    SGLuint16 us_line_type4_79_0;
    SGLuint16 us_nb_vertex4_79_0;
    SGLfloat tf_points4_79_0[32UL];
    /* Char 80 */
    SGLuint32 ui_nb_lines4_80;
    SGLuint16 us_line_type4_80_0;
    SGLuint16 us_nb_vertex4_80_0;
    SGLfloat tf_points4_80_0[18UL];
    /* Char 81 */
    SGLuint32 ui_nb_lines4_81;
    SGLuint16 us_line_type4_81_0;
    SGLuint16 us_nb_vertex4_81_0;
    SGLfloat tf_points4_81_0[4UL];
    SGLuint16 us_line_type4_81_1;
    SGLuint16 us_nb_vertex4_81_1;
    SGLfloat tf_points4_81_1[24UL];
    /* Char 82 */
    SGLuint32 ui_nb_lines4_82;
    SGLuint16 us_line_type4_82_0;
    SGLuint16 us_nb_vertex4_82_0;
    SGLfloat tf_points4_82_0[18UL];
    SGLuint16 us_line_type4_82_1;
    SGLuint16 us_nb_vertex4_82_1;
    SGLfloat tf_points4_82_1[4UL];
    /* Char 83 */
    SGLuint32 ui_nb_lines4_83;
    SGLuint16 us_line_type4_83_0;
    SGLuint16 us_nb_vertex4_83_0;
    SGLfloat tf_points4_83_0[32UL];
    /* Char 84 */
    SGLuint32 ui_nb_lines4_84;
    SGLuint16 us_line_type4_84_0;
    SGLuint16 us_nb_vertex4_84_0;
    SGLfloat tf_points4_84_0[8UL];
    /* Char 85 */
    SGLuint32 ui_nb_lines4_85;
    SGLuint16 us_line_type4_85_0;
    SGLuint16 us_nb_vertex4_85_0;
    SGLfloat tf_points4_85_0[16UL];
    /* Char 86 */
    SGLuint32 ui_nb_lines4_86;
    SGLuint16 us_line_type4_86_0;
    SGLuint16 us_nb_vertex4_86_0;
    SGLfloat tf_points4_86_0[10UL];
    /* Char 87 */
    SGLuint32 ui_nb_lines4_87;
    SGLuint16 us_line_type4_87_0;
    SGLuint16 us_nb_vertex4_87_0;
    SGLfloat tf_points4_87_0[10UL];
    /* Char 88 */
    SGLuint32 ui_nb_lines4_88;
    SGLuint16 us_line_type4_88_0;
    SGLuint16 us_nb_vertex4_88_0;
    SGLfloat tf_points4_88_0[8UL];
    SGLuint16 us_line_type4_88_1;
    SGLuint16 us_nb_vertex4_88_1;
    SGLfloat tf_points4_88_1[8UL];
    /* Char 89 */
    SGLuint32 ui_nb_lines4_89;
    SGLuint16 us_line_type4_89_0;
    SGLuint16 us_nb_vertex4_89_0;
    SGLfloat tf_points4_89_0[8UL];
    SGLuint16 us_line_type4_89_1;
    SGLuint16 us_nb_vertex4_89_1;
    SGLfloat tf_points4_89_1[6UL];
    /* Char 90 */
    SGLuint32 ui_nb_lines4_90;
    SGLuint16 us_line_type4_90_0;
    SGLuint16 us_nb_vertex4_90_0;
    SGLfloat tf_points4_90_0[8UL];
    /* Char 91 */
    SGLuint32 ui_nb_lines4_91;
    SGLuint16 us_line_type4_91_0;
    SGLuint16 us_nb_vertex4_91_0;
    SGLfloat tf_points4_91_0[12UL];
    /* Char 92 */
    SGLuint32 ui_nb_lines4_92;
    SGLuint16 us_line_type4_92_0;
    SGLuint16 us_nb_vertex4_92_0;
    SGLfloat tf_points4_92_0[4UL];
    /* Char 93 */
    SGLuint32 ui_nb_lines4_93;
    SGLuint16 us_line_type4_93_0;
    SGLuint16 us_nb_vertex4_93_0;
    SGLfloat tf_points4_93_0[12UL];
    /* Char 95 */
    SGLuint32 ui_nb_lines4_95;
    SGLuint16 us_line_type4_95_0;
    SGLuint16 us_nb_vertex4_95_0;
    SGLfloat tf_points4_95_0[4UL];
    /* Char 97 */
    SGLuint32 ui_nb_lines4_97;
    SGLuint16 us_line_type4_97_0;
    SGLuint16 us_nb_vertex4_97_0;
    SGLfloat tf_points4_97_0[10UL];
    SGLuint16 us_line_type4_97_1;
    SGLuint16 us_nb_vertex4_97_1;
    SGLfloat tf_points4_97_1[4UL];
    /* Char 98 */
    SGLuint32 ui_nb_lines4_98;
    SGLuint16 us_line_type4_98_0;
    SGLuint16 us_nb_vertex4_98_0;
    SGLfloat tf_points4_98_0[30UL];
    /* Char 99 */
    SGLuint32 ui_nb_lines4_99;
    SGLuint16 us_line_type4_99_0;
    SGLuint16 us_nb_vertex4_99_0;
    SGLfloat tf_points4_99_0[24UL];
    /* Char 100 */
    SGLuint32 ui_nb_lines4_100;
    SGLuint16 us_line_type4_100_0;
    SGLuint16 us_nb_vertex4_100_0;
    SGLfloat tf_points4_100_0[16UL];
    /* Char 101 */
    SGLuint32 ui_nb_lines4_101;
    SGLuint16 us_line_type4_101_0;
    SGLuint16 us_nb_vertex4_101_0;
    SGLfloat tf_points4_101_0[4UL];
    SGLuint16 us_line_type4_101_1;
    SGLuint16 us_nb_vertex4_101_1;
    SGLfloat tf_points4_101_1[8UL];
    /* Char 102 */
    SGLuint32 ui_nb_lines4_102;
    SGLuint16 us_line_type4_102_0;
    SGLuint16 us_nb_vertex4_102_0;
    SGLfloat tf_points4_102_0[4UL];
    SGLuint16 us_line_type4_102_1;
    SGLuint16 us_nb_vertex4_102_1;
    SGLfloat tf_points4_102_1[6UL];
    /* Char 103 */
    SGLuint32 ui_nb_lines4_103;
    SGLuint16 us_line_type4_103_0;
    SGLuint16 us_nb_vertex4_103_0;
    SGLfloat tf_points4_103_0[28UL];
    /* Char 104 */
    SGLuint32 ui_nb_lines4_104;
    SGLuint16 us_line_type4_104_0;
    SGLuint16 us_nb_vertex4_104_0;
    SGLfloat tf_points4_104_0[12UL];
    /* Char 105 */
    SGLuint32 ui_nb_lines4_105;
    SGLuint16 us_line_type4_105_0;
    SGLuint16 us_nb_vertex4_105_0;
    SGLfloat tf_points4_105_0[12UL];
    /* Char 106 */
    SGLuint32 ui_nb_lines4_106;
    SGLuint16 us_line_type4_106_0;
    SGLuint16 us_nb_vertex4_106_0;
    SGLfloat tf_points4_106_0[14UL];
    SGLuint16 us_line_type4_106_1;
    SGLuint16 us_nb_vertex4_106_1;
    SGLfloat tf_points4_106_1[4UL];
    /* Char 107 */
    SGLuint32 ui_nb_lines4_107;
    SGLuint16 us_line_type4_107_0;
    SGLuint16 us_nb_vertex4_107_0;
    SGLfloat tf_points4_107_0[12UL];
    /* Char 108 */
    SGLuint32 ui_nb_lines4_108;
    SGLuint16 us_line_type4_108_0;
    SGLuint16 us_nb_vertex4_108_0;
    SGLfloat tf_points4_108_0[6UL];
    /* Char 109 */
    SGLuint32 ui_nb_lines4_109;
    SGLuint16 us_line_type4_109_0;
    SGLuint16 us_nb_vertex4_109_0;
    SGLfloat tf_points4_109_0[10UL];
    /* Char 110 */
    SGLuint32 ui_nb_lines4_110;
    SGLuint16 us_line_type4_110_0;
    SGLuint16 us_nb_vertex4_110_0;
    SGLfloat tf_points4_110_0[8UL];
    /* Char 111 */
    SGLuint32 ui_nb_lines4_111;
    SGLuint16 us_line_type4_111_0;
    SGLuint16 us_nb_vertex4_111_0;
    SGLfloat tf_points4_111_0[32UL];
    /* Char 112 */
    SGLuint32 ui_nb_lines4_112;
    SGLuint16 us_line_type4_112_0;
    SGLuint16 us_nb_vertex4_112_0;
    SGLfloat tf_points4_112_0[18UL];
    /* Char 113 */
    SGLuint32 ui_nb_lines4_113;
    SGLuint16 us_line_type4_113_0;
    SGLuint16 us_nb_vertex4_113_0;
    SGLfloat tf_points4_113_0[4UL];
    SGLuint16 us_line_type4_113_1;
    SGLuint16 us_nb_vertex4_113_1;
    SGLfloat tf_points4_113_1[24UL];
    /* Char 114 */
    SGLuint32 ui_nb_lines4_114;
    SGLuint16 us_line_type4_114_0;
    SGLuint16 us_nb_vertex4_114_0;
    SGLfloat tf_points4_114_0[18UL];
    SGLuint16 us_line_type4_114_1;
    SGLuint16 us_nb_vertex4_114_1;
    SGLfloat tf_points4_114_1[4UL];
    /* Char 115 */
    SGLuint32 ui_nb_lines4_115;
    SGLuint16 us_line_type4_115_0;
    SGLuint16 us_nb_vertex4_115_0;
    SGLfloat tf_points4_115_0[32UL];
    /* Char 116 */
    SGLuint32 ui_nb_lines4_116;
    SGLuint16 us_line_type4_116_0;
    SGLuint16 us_nb_vertex4_116_0;
    SGLfloat tf_points4_116_0[8UL];
    /* Char 117 */
    SGLuint32 ui_nb_lines4_117;
    SGLuint16 us_line_type4_117_0;
    SGLuint16 us_nb_vertex4_117_0;
    SGLfloat tf_points4_117_0[16UL];
    /* Char 118 */
    SGLuint32 ui_nb_lines4_118;
    SGLuint16 us_line_type4_118_0;
    SGLuint16 us_nb_vertex4_118_0;
    SGLfloat tf_points4_118_0[10UL];
    /* Char 119 */
    SGLuint32 ui_nb_lines4_119;
    SGLuint16 us_line_type4_119_0;
    SGLuint16 us_nb_vertex4_119_0;
    SGLfloat tf_points4_119_0[10UL];
    /* Char 120 */
    SGLuint32 ui_nb_lines4_120;
    SGLuint16 us_line_type4_120_0;
    SGLuint16 us_nb_vertex4_120_0;
    SGLfloat tf_points4_120_0[8UL];
    SGLuint16 us_line_type4_120_1;
    SGLuint16 us_nb_vertex4_120_1;
    SGLfloat tf_points4_120_1[8UL];
    /* Char 121 */
    SGLuint32 ui_nb_lines4_121;
    SGLuint16 us_line_type4_121_0;
    SGLuint16 us_nb_vertex4_121_0;
    SGLfloat tf_points4_121_0[8UL];
    SGLuint16 us_line_type4_121_1;
    SGLuint16 us_nb_vertex4_121_1;
    SGLfloat tf_points4_121_1[6UL];
    /* Char 122 */
    SGLuint32 ui_nb_lines4_122;
    SGLuint16 us_line_type4_122_0;
    SGLuint16 us_nb_vertex4_122_0;
    SGLfloat tf_points4_122_0[8UL];
    /* Char 124 */
    SGLuint32 ui_nb_lines4_124;
    SGLuint16 us_line_type4_124_0;
    SGLuint16 us_nb_vertex4_124_0;
    SGLfloat tf_points4_124_0[4UL];
    /* Char 128 */
    SGLuint32 ui_nb_lines4_128;
    SGLuint16 us_line_type4_128_0;
    SGLuint16 us_nb_vertex4_128_0;
    SGLfloat tf_points4_128_0[6UL];
    /* Char 129 */
    SGLuint32 ui_nb_lines4_129;
    SGLuint16 us_line_type4_129_0;
    SGLuint16 us_nb_vertex4_129_0;
    SGLfloat tf_points4_129_0[12UL];
    /* Char 130 */
    SGLuint32 ui_nb_lines4_130;
    SGLuint16 us_line_type4_130_0;
    SGLuint16 us_nb_vertex4_130_0;
    SGLfloat tf_points4_130_0[8UL];
    /* Char 131 */
    SGLuint32 ui_nb_lines4_131;
    SGLuint16 us_line_type4_131_0;
    SGLuint16 us_nb_vertex4_131_0;
    SGLfloat tf_points4_131_0[8UL];
    /* Char 132 */
    SGLuint32 ui_nb_lines4_132;
    SGLuint16 us_line_type4_132_0;
    SGLuint16 us_nb_vertex4_132_0;
    SGLfloat tf_points4_132_0[4UL];
    SGLuint16 us_line_type4_132_1;
    SGLuint16 us_nb_vertex4_132_1;
    SGLfloat tf_points4_132_1[6UL];
    /* Char 133 */
    SGLuint32 ui_nb_lines4_133;
    SGLuint16 us_line_type4_133_0;
    SGLuint16 us_nb_vertex4_133_0;
    SGLfloat tf_points4_133_0[4UL];
    SGLuint16 us_line_type4_133_1;
    SGLuint16 us_nb_vertex4_133_1;
    SGLfloat tf_points4_133_1[6UL];
    /* Char 134 */
    SGLuint32 ui_nb_lines4_134;
    SGLuint16 us_line_type4_134_0;
    SGLuint16 us_nb_vertex4_134_0;
    SGLfloat tf_points4_134_0[4UL];
    SGLuint16 us_line_type4_134_1;
    SGLuint16 us_nb_vertex4_134_1;
    SGLfloat tf_points4_134_1[6UL];
    /* Char 135 */
    SGLuint32 ui_nb_lines4_135;
    SGLuint16 us_line_type4_135_0;
    SGLuint16 us_nb_vertex4_135_0;
    SGLfloat tf_points4_135_0[4UL];
    SGLuint16 us_line_type4_135_1;
    SGLuint16 us_nb_vertex4_135_1;
    SGLfloat tf_points4_135_1[6UL];
    /* Char 136 */
    SGLuint32 ui_nb_lines4_136;
    /* Char 160 */
    SGLuint32 ui_nb_lines4_160;
    SGLuint16 us_line_type4_160_0;
    SGLuint16 us_nb_vertex4_160_0;
    SGLfloat tf_points4_160_0[8UL];
    /* Char 161 */
    SGLuint32 ui_nb_lines4_161;
    SGLuint16 us_line_type4_161_0;
    SGLuint16 us_nb_vertex4_161_0;
    SGLfloat tf_points4_161_0[8UL];
    SGLuint16 us_line_type4_161_1;
    SGLuint16 us_nb_vertex4_161_1;
    SGLfloat tf_points4_161_1[12UL];
    /* Char 162 */
    SGLuint32 ui_nb_lines4_162;
    SGLuint16 us_line_type4_162_0;
    SGLuint16 us_nb_vertex4_162_0;
    SGLfloat tf_points4_162_0[12UL];
    /* Char 176 */
    SGLuint32 ui_nb_lines4_176;
    SGLuint16 us_line_type4_176_0;
    SGLuint16 us_nb_vertex4_176_0;
    SGLfloat tf_points4_176_0[12UL];
  } strokes4;
} aol_font_table_type;

extern SGLuint8 aol_font_table_texture0[107407UL];

extern const aol_font_table_type aol_font_table;

#endif /* AOL_FONT_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:50:30
 *********************************************************/

