/*********************************************************
 **
 ** File  aol_symbology_layer.h
 **
 ** Specification File:  D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:50:30
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sgt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\AllObjects\AllObjects.sgfx
 *********************************************************/

#ifndef AOL_SYMBOLOGY_LAYER_H
#define AOL_SYMBOLOGY_LAYER_H

#include "sgl_types.h"
#include "kcg_assign.h"


/* Accessors */
#ifndef aol_symbology_layer_G_CircAngle
#define aol_symbology_layer_G_CircAngle(_C_) (_C_)->CircAngle
#define aol_symbology_layer_S_CircAngle(_C_,_V_) (_C_)->CircAngle = (_V_)
#endif /* aol_symbology_layer_G_CircAngle */
#ifndef aol_symbology_layer_G_CircInside
#define aol_symbology_layer_G_CircInside(_C_) (_C_)->CircInside
#define aol_symbology_layer_S_CircInside(_C_,_V_) (_C_)->CircInside = (_V_)
#endif /* aol_symbology_layer_G_CircInside */
#ifndef aol_symbology_layer_G_CircPercent
#define aol_symbology_layer_G_CircPercent(_C_) (_C_)->CircPercent
#define aol_symbology_layer_S_CircPercent(_C_,_V_) (_C_)->CircPercent = (_V_)
#endif /* aol_symbology_layer_G_CircPercent */
#ifndef aol_symbology_layer_G_RectHeightPercent
#define aol_symbology_layer_G_RectHeightPercent(_C_) (_C_)->RectHeightPercent
#define aol_symbology_layer_S_RectHeightPercent(_C_,_V_) (_C_)->RectHeightPercent = (_V_)
#endif /* aol_symbology_layer_G_RectHeightPercent */
#ifndef aol_symbology_layer_G_RectInside
#define aol_symbology_layer_G_RectInside(_C_) (_C_)->RectInside
#define aol_symbology_layer_S_RectInside(_C_,_V_) (_C_)->RectInside = (_V_)
#endif /* aol_symbology_layer_G_RectInside */
#ifndef aol_symbology_layer_G_RectWidthPercent
#define aol_symbology_layer_G_RectWidthPercent(_C_) (_C_)->RectWidthPercent
#define aol_symbology_layer_S_RectWidthPercent(_C_,_V_) (_C_)->RectWidthPercent = (_V_)
#endif /* aol_symbology_layer_G_RectWidthPercent */
#ifndef aol_symbology_layer_G_ShapeInside
#define aol_symbology_layer_G_ShapeInside(_C_) (_C_)->ShapeInside
#define aol_symbology_layer_S_ShapeInside(_C_,_V_) (_C_)->ShapeInside = (_V_)
#endif /* aol_symbology_layer_G_ShapeInside */
#ifndef aol_symbology_layer_G_Click
#define aol_symbology_layer_G_Click(_C_) (_C_)->Click
#define aol_symbology_layer_S_Click(_C_,_V_) (_C_)->Click = (_V_)
#endif /* aol_symbology_layer_G_Click */
#ifndef aol_symbology_layer_G_Pressed
#define aol_symbology_layer_G_Pressed(_C_) (_C_)->Pressed
#define aol_symbology_layer_S_Pressed(_C_,_V_) (_C_)->Pressed = (_V_)
#endif /* aol_symbology_layer_G_Pressed */
#ifndef aol_symbology_layer_G_RectErrorInside
#define aol_symbology_layer_G_RectErrorInside(_C_) (_C_)->RectErrorInside
#define aol_symbology_layer_S_RectErrorInside(_C_,_V_) (_C_)->RectErrorInside = (_V_)
#endif /* aol_symbology_layer_G_RectErrorInside */
#ifndef aol_symbology_layer_G_locPushedError
#define aol_symbology_layer_G_locPushedError(_C_) (_C_)->locPushedError
#define aol_symbology_layer_S_locPushedError(_C_,_V_) (_C_)->locPushedError = (_V_)
#endif /* aol_symbology_layer_G_locPushedError */
#ifndef aol_symbology_layer_G_RectClearErrorInside
#define aol_symbology_layer_G_RectClearErrorInside(_C_) (_C_)->RectClearErrorInside
#define aol_symbology_layer_S_RectClearErrorInside(_C_,_V_) (_C_)->RectClearErrorInside = (_V_)
#endif /* aol_symbology_layer_G_RectClearErrorInside */
#ifndef aol_symbology_layer_G_locPushedClearError
#define aol_symbology_layer_G_locPushedClearError(_C_) (_C_)->locPushedClearError
#define aol_symbology_layer_S_locPushedClearError(_C_,_V_) (_C_)->locPushedClearError = (_V_)
#endif /* aol_symbology_layer_G_locPushedClearError */
#ifndef aol_symbology_layer_G_locBufferStatus
#define aol_symbology_layer_G_locBufferStatus(_C_) (_C_)->locBufferStatus
#define aol_symbology_layer_S_locBufferStatus(_C_,_V_) (_C_)->locBufferStatus = (_V_)
#endif /* aol_symbology_layer_G_locBufferStatus */
#ifndef aol_symbology_layer_G_locNbErrors
#define aol_symbology_layer_G_locNbErrors(_C_) (_C_)->locNbErrors
#define aol_symbology_layer_S_locNbErrors(_C_,_V_) (_C_)->locNbErrors = (_V_)
#endif /* aol_symbology_layer_G_locNbErrors */
#ifndef aol_symbology_layer_G_locLastErrorId
#define aol_symbology_layer_G_locLastErrorId(_C_) (_C_)->locLastErrorId
#define aol_symbology_layer_S_locLastErrorId(_C_,_V_) (_C_)->locLastErrorId = (_V_)
#endif /* aol_symbology_layer_G_locLastErrorId */
#ifndef aol_symbology_layer_G_RectErrorEnableInside
#define aol_symbology_layer_G_RectErrorEnableInside(_C_) (_C_)->RectErrorEnableInside
#define aol_symbology_layer_S_RectErrorEnableInside(_C_,_V_) (_C_)->RectErrorEnableInside = (_V_)
#endif /* aol_symbology_layer_G_RectErrorEnableInside */
#ifndef aol_symbology_layer_G_locPushedErrorEnable
#define aol_symbology_layer_G_locPushedErrorEnable(_C_) (_C_)->locPushedErrorEnable
#define aol_symbology_layer_S_locPushedErrorEnable(_C_,_V_) (_C_)->locPushedErrorEnable = (_V_)
#endif /* aol_symbology_layer_G_locPushedErrorEnable */
#ifndef aol_symbology_layer_G_errorName
#define aol_symbology_layer_G_errorName(_C_) (_C_)->errorName
#define aol_symbology_layer_S_errorName(_C_,_V_) kcg_assign((_C_)->errorName, (_V_), sizeof(SGLuint8[255UL]))
#endif /* aol_symbology_layer_G_errorName */
#ifndef aol_symbology_layer_G_locRedDepth
#define aol_symbology_layer_G_locRedDepth(_C_) (_C_)->locRedDepth
#define aol_symbology_layer_S_locRedDepth(_C_,_V_) (_C_)->locRedDepth = (_V_)
#endif /* aol_symbology_layer_G_locRedDepth */
#ifndef aol_symbology_layer_G_locGreenDepth
#define aol_symbology_layer_G_locGreenDepth(_C_) (_C_)->locGreenDepth
#define aol_symbology_layer_S_locGreenDepth(_C_,_V_) (_C_)->locGreenDepth = (_V_)
#endif /* aol_symbology_layer_G_locGreenDepth */
#ifndef aol_symbology_layer_G_GreenDepthPlusIn
#define aol_symbology_layer_G_GreenDepthPlusIn(_C_) (_C_)->GreenDepthPlusIn
#define aol_symbology_layer_S_GreenDepthPlusIn(_C_,_V_) (_C_)->GreenDepthPlusIn = (_V_)
#endif /* aol_symbology_layer_G_GreenDepthPlusIn */
#ifndef aol_symbology_layer_G_GreenDepthMinusIn
#define aol_symbology_layer_G_GreenDepthMinusIn(_C_) (_C_)->GreenDepthMinusIn
#define aol_symbology_layer_S_GreenDepthMinusIn(_C_,_V_) (_C_)->GreenDepthMinusIn = (_V_)
#endif /* aol_symbology_layer_G_GreenDepthMinusIn */
#ifndef aol_symbology_layer_G_RedDepthPlusIn
#define aol_symbology_layer_G_RedDepthPlusIn(_C_) (_C_)->RedDepthPlusIn
#define aol_symbology_layer_S_RedDepthPlusIn(_C_,_V_) (_C_)->RedDepthPlusIn = (_V_)
#endif /* aol_symbology_layer_G_RedDepthPlusIn */
#ifndef aol_symbology_layer_G_RedDepthMinusIn
#define aol_symbology_layer_G_RedDepthMinusIn(_C_) (_C_)->RedDepthMinusIn
#define aol_symbology_layer_S_RedDepthMinusIn(_C_,_V_) (_C_)->RedDepthMinusIn = (_V_)
#endif /* aol_symbology_layer_G_RedDepthMinusIn */
#ifndef aol_symbology_layer_G_PinkDepthPlusIn
#define aol_symbology_layer_G_PinkDepthPlusIn(_C_) (_C_)->PinkDepthPlusIn
#define aol_symbology_layer_S_PinkDepthPlusIn(_C_,_V_) (_C_)->PinkDepthPlusIn = (_V_)
#endif /* aol_symbology_layer_G_PinkDepthPlusIn */
#ifndef aol_symbology_layer_G_PinkDepthMinusIn
#define aol_symbology_layer_G_PinkDepthMinusIn(_C_) (_C_)->PinkDepthMinusIn
#define aol_symbology_layer_S_PinkDepthMinusIn(_C_,_V_) (_C_)->PinkDepthMinusIn = (_V_)
#endif /* aol_symbology_layer_G_PinkDepthMinusIn */
#ifndef aol_symbology_layer_G_locPinkDepth
#define aol_symbology_layer_G_locPinkDepth(_C_) (_C_)->locPinkDepth
#define aol_symbology_layer_S_locPinkDepth(_C_,_V_) (_C_)->locPinkDepth = (_V_)
#endif /* aol_symbology_layer_G_locPinkDepth */
#ifndef aol_symbology_layer_G_ChangeHaloLevelIn
#define aol_symbology_layer_G_ChangeHaloLevelIn(_C_) (_C_)->ChangeHaloLevelIn
#define aol_symbology_layer_S_ChangeHaloLevelIn(_C_,_V_) (_C_)->ChangeHaloLevelIn = (_V_)
#endif /* aol_symbology_layer_G_ChangeHaloLevelIn */
#ifndef aol_symbology_layer_G_locEnableHaloLevel
#define aol_symbology_layer_G_locEnableHaloLevel(_C_) (_C_)->locEnableHaloLevel
#define aol_symbology_layer_S_locEnableHaloLevel(_C_,_V_) (_C_)->locEnableHaloLevel = (_V_)
#endif /* aol_symbology_layer_G_locEnableHaloLevel */
#ifndef aol_symbology_layer_G_RectDepthInside
#define aol_symbology_layer_G_RectDepthInside(_C_) (_C_)->RectDepthInside
#define aol_symbology_layer_S_RectDepthInside(_C_,_V_) (_C_)->RectDepthInside = (_V_)
#endif /* aol_symbology_layer_G_RectDepthInside */
#ifndef aol_symbology_layer_G_locDepthTest
#define aol_symbology_layer_G_locDepthTest(_C_) (_C_)->locDepthTest
#define aol_symbology_layer_S_locDepthTest(_C_,_V_) (_C_)->locDepthTest = (_V_)
#endif /* aol_symbology_layer_G_locDepthTest */
#ifndef aol_symbology_layer_G_locPushedDepth
#define aol_symbology_layer_G_locPushedDepth(_C_) (_C_)->locPushedDepth
#define aol_symbology_layer_S_locPushedDepth(_C_,_V_) (_C_)->locPushedDepth = (_V_)
#endif /* aol_symbology_layer_G_locPushedDepth */
#ifndef aol_symbology_layer_G_locMaskIndex
#define aol_symbology_layer_G_locMaskIndex(_C_) (_C_)->locMaskIndex
#define aol_symbology_layer_S_locMaskIndex(_C_,_V_) (_C_)->locMaskIndex = (_V_)
#endif /* aol_symbology_layer_G_locMaskIndex */
#ifndef aol_symbology_layer_G_locVisiShapes
#define aol_symbology_layer_G_locVisiShapes(_C_) (_C_)->locVisiShapes
#define aol_symbology_layer_S_locVisiShapes(_C_,_V_) (_C_)->locVisiShapes = (_V_)
#endif /* aol_symbology_layer_G_locVisiShapes */
#ifndef aol_symbology_layer_G_locSmoothMode
#define aol_symbology_layer_G_locSmoothMode(_C_) (_C_)->locSmoothMode
#define aol_symbology_layer_S_locSmoothMode(_C_,_V_) (_C_)->locSmoothMode = (_V_)
#endif /* aol_symbology_layer_G_locSmoothMode */
#ifndef aol_symbology_layer_G_locPushedRendering
#define aol_symbology_layer_G_locPushedRendering(_C_) (_C_)->locPushedRendering
#define aol_symbology_layer_S_locPushedRendering(_C_,_V_) (_C_)->locPushedRendering = (_V_)
#endif /* aol_symbology_layer_G_locPushedRendering */
#ifndef aol_symbology_layer_G_locPushedTF
#define aol_symbology_layer_G_locPushedTF(_C_) (_C_)->locPushedTF
#define aol_symbology_layer_S_locPushedTF(_C_,_V_) (_C_)->locPushedTF = (_V_)
#endif /* aol_symbology_layer_G_locPushedTF */
#ifndef aol_symbology_layer_G_locPushedMask
#define aol_symbology_layer_G_locPushedMask(_C_) (_C_)->locPushedMask
#define aol_symbology_layer_S_locPushedMask(_C_,_V_) (_C_)->locPushedMask = (_V_)
#endif /* aol_symbology_layer_G_locPushedMask */

/* Context type */
typedef struct aol_typ_symbology_layer_ {
  /* ------------------------- outputs -------------------------- */
  SGLfloat CircAngle;
  SGLbool CircInside;
  SGLfloat CircPercent;
  SGLfloat RectHeightPercent;
  SGLbool RectInside;
  SGLfloat RectWidthPercent;
  SGLbool ShapeInside;
  SGLbool Click;
  SGLbool Pressed;
  SGLbool RectErrorInside;
  SGLbool locPushedError;
  SGLbool RectClearErrorInside;
  SGLbool locPushedClearError;
  SGLuint8 locBufferStatus;
  SGLuint32 locNbErrors;
  SGLuint32 locLastErrorId;
  SGLbool RectErrorEnableInside;
  SGLbool locPushedErrorEnable;
  SGLuint8 errorName[255UL];
  SGLint32 locRedDepth;
  SGLint32 locGreenDepth;
  SGLbool GreenDepthPlusIn;
  SGLbool GreenDepthMinusIn;
  SGLbool RedDepthPlusIn;
  SGLbool RedDepthMinusIn;
  SGLbool PinkDepthPlusIn;
  SGLbool PinkDepthMinusIn;
  SGLint32 locPinkDepth;
  SGLbool ChangeHaloLevelIn;
  SGLbool locEnableHaloLevel;
  SGLbool RectDepthInside;
  SGLbool locDepthTest;
  SGLbool locPushedDepth;
  /* ------------------------- locals --------------------------- */
  SGLint32 locMaskIndex;
  SGLbool locVisiShapes;
  SGLbool locSmoothMode;
  SGLbool locPushedRendering;
  SGLbool locPushedTF;
  SGLbool locPushedMask;
} aol_typ_symbology_layer;

/* Associated functions */
extern void aol_symbology_layer_init(aol_typ_symbology_layer *pContext);
extern void aol_symbology_layer_predraw(aol_typ_symbology_layer *pContext);
extern void aol_symbology_layer_draw(aol_typ_symbology_layer *pContext, SGLint32 pPriority);
extern void aol_symbology_layer_static_sequences(void);

#endif /* AOL_SYMBOLOGY_LAYER_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:50:30
 *********************************************************/

