/*********************************************************
 **
 ** File  aol_texture_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:53:48
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sgfx
 *********************************************************/

#include "sgl.h"
#include "aol_texture_table.h"

/* Textures definition */
void aol_texture_table(void)
{

}

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:53:48
 *********************************************************/

