/*********************************************************
 **
 ** File  aol_symbology_layer.c
 **
 ** Specification File:  D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:53:48
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sgfx
 *********************************************************/

#include "aol_symbology_layer.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_symbology_layer_init(aol_typ_symbology_layer *pContext)
{
  aol_symbology_layer_S_PN_AIRSPEED(pContext, 0.0F);
  aol_symbology_layer_S_PN_ALTI(pContext, 0.0F);
  aol_symbology_layer_S_PN_PITCH_ANGLE(pContext, 0.0F);
  aol_symbology_layer_S_PN_ROLL_ANGLE(pContext, 0.0F);

}

void aol_symbology_layer_predraw(aol_typ_symbology_layer *pContext)
{

}

/* indexes declaration for static sequences */
static SGLuint32 aol_symbology_layer_stc0 = 0UL;
static SGLuint32 aol_symbology_layer_stc1 = 0UL;
static SGLuint32 aol_symbology_layer_stc2 = 0UL;
static SGLuint32 aol_symbology_layer_stc3 = 0UL;
static SGLuint32 aol_symbology_layer_stc4 = 0UL;
static SGLuint32 aol_symbology_layer_stc5 = 0UL;
static SGLuint32 aol_symbology_layer_stc6 = 0UL;
static SGLuint32 aol_symbology_layer_stc7 = 0UL;
static SGLuint32 aol_symbology_layer_stc8 = 0UL;
static SGLuint32 aol_symbology_layer_stc9 = 0UL;
static SGLuint32 aol_symbology_layer_stc10 = 0UL;
static SGLuint32 aol_symbology_layer_stc11 = 0UL;
static SGLuint32 aol_symbology_layer_stc12 = 0UL;
static SGLuint32 aol_symbology_layer_stc13 = 0UL;
static SGLuint32 aol_symbology_layer_stc14 = 0UL;
static SGLuint32 aol_symbology_layer_stc15 = 0UL;
static SGLuint32 aol_symbology_layer_stc16 = 0UL;
static SGLuint32 aol_symbology_layer_stc17 = 0UL;

void aol_symbology_layer_static_sequences(void)
{
  /* Static sequence for Object: SCALE_DAN_F00, Type: container, OID: 27fb21e4-15ae-4a72-8389-ae365552db5c */
  aol_symbology_layer_stc0 = sglBeginStaticSequence(-200.08F, -454.31607F, 203.96199F, 456.7529F);

  /* Object: begin_moving, Type: container, OID: 25b18e1b-a672-4ba6-89a5-833f5e1d7515 */
  {
    sglPushMatrixAndTranslate(1.941F, 0.358F);

    /* Object: PART_4, Type: container, OID: e058e68a-8844-4126-a6f7-0f53fa4af008 */
    {
      sglPushMatrixAndTranslate(-1.941F, -343.674F);

      /* Object: text, Type: text, OID: 7d30c236-5d63-4483-b71d-b4807e7ddae7 */
      {
        static SGLuint8 lArray0_text[255UL] = {54U,48U};
        sglIndexColori(41L);
        sglIndexHaloColori(-1L);
        sglIndexFontLineWidthi(2L);
        sglIndexFonti(1L);
        sglDisable(SGL_LINE_HALOING);
        sglSetTextAlignment(SGL_ALIGN_LEFT, SGL_ALIGN_BOTTOM);
        sgluWriteText(-88.209F, 41.688F, lArray0_text, 255L);
      }

      /* Object: text_1, Type: text, OID: 11a68718-ea3c-4317-a9ba-0cce06cdabf4 */
      {
        static SGLuint8 lArray0_text_1[255UL] = {54U,48U};
        sgluWriteText(61.256F, 41.688F, lArray0_text_1, 255L);
      }

      /* Object: text_2, Type: text, OID: b72fe854-4abd-408d-b04d-146c115ae7d7 */
      {
        static SGLuint8 lArray0_text_2[255UL] = {55U,48U};
        sgluWriteText(-88.209F, -7.357F, lArray0_text_2, 255L);
      }

      /* Object: text_3, Type: text, OID: 2bca70d2-a144-40a7-8aae-e86dcff09de3 */
      {
        static SGLuint8 lArray0_text_3[255UL] = {55U,48U};
        sgluWriteText(61.256F, -7.357F, lArray0_text_3, 255L);
      }

      /* Object: text_4, Type: text, OID: a46c23dc-001f-484a-aac8-880e1fa9263b */
      {
        static SGLuint8 lArray0_text_4[255UL] = {56U,48U};
        sgluWriteText(-88.209F, -56.402F, lArray0_text_4, 255L);
      }

      /* Object: text_5, Type: text, OID: 556b8891-1882-48c0-947a-b58b62da44b8 */
      {
        static SGLuint8 lArray0_text_5[255UL] = {56U,48U};
        sgluWriteText(61.256F, -56.402F, lArray0_text_5, 255L);
      }

      /* Object: text_6, Type: text, OID: b2f89992-4662-4f63-8fd9-0105a0099131 */
      {
        static SGLuint8 lArray0_text_6[255UL] = {57U,48U};
        sgluWriteText(-88.209F, -105.447F, lArray0_text_6, 255L);
      }

      /* Object: text_7, Type: text, OID: a57dc5c3-97a5-417a-aee6-0467cb6a829d */
      {
        static SGLuint8 lArray0_text_7[255UL] = {57U,48U};
        sgluWriteText(61.256F, -105.447F, lArray0_text_7, 255L);
      }

      /* Object: line, Type: line, OID: d0c53d7a-e5b0-4058-8110-b7a31ef0a45f */
      {
        /* outline object part */
        sglIndexLineWidthi(1L);
        sglIndexLineStipplei(0L);
        sglSetLineCaps(SGL_ROUNDED_CAPS);
        sglTransparency8(255L);
        sglBegin(SGL_LINES);
        sglVertex2f(-49.005F, 48.751F);
        sglVertex2f(49.005F, 48.751F);
      }

      /* Object: line_1, Type: line, OID: 0e6c7df2-57a2-49a8-9ed8-33b4f9e41c9c */
      {
        /* outline object part */
        sglVertex2f(-49.005F, 0.226F);
        sglVertex2f(49.005F, 0.226F);
      }

      /* Object: line_2, Type: line, OID: 22ae9313-1e6b-460f-ac96-ce1465a68734 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, -49.261F);
        sglVertex2f(49.005F, -49.261F);
      }

      /* Object: line_3, Type: line, OID: f5dbceed-ec45-4096-8296-fa818d1b0d62 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, -98.267F);
        sglVertex2f(49.005F, -98.267F);
      }

      /* Object: line_4, Type: line, OID: 1c9f8312-eb6d-4a0e-8b5b-363c8705e5c9 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 73.479F);
        sglVertex2f(9.801F, 73.479F);
      }

      /* Object: line_5, Type: line, OID: ebe14eb6-79b0-442f-ae17-847995112221 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 24.473F);
        sglVertex2f(9.801F, 24.473F);
      }

      /* Object: line_6, Type: line, OID: bbcae981-da51-45b4-b7ab-f799af05e3bc */
      {
        /* outline object part */
        sglVertex2f(-9.801F, -24.532F);
        sglVertex2f(9.801F, -24.532F);
      }

      /* Object: line_7, Type: line, OID: 46b19e57-fd6a-480a-bf10-0f963edbc371 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, -73.533F);
        sglVertex2f(9.801F, -73.533F);
      }

      /* Object: line_8, Type: line, OID: fc54d770-0d73-4859-906a-4d2d1158d069 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 122.672F);
        sglVertex2f(9.801F, 122.672F);
        sglEnd();
      }

      /* Object: text_8, Type: text, OID: 3fa23983-e6cf-43bb-be90-61fca66e0aba */
      {
        static SGLuint8 lArray0_text_8[255UL] = {53U,48U};
        sgluWriteText(-88.209F, 90.733F, lArray0_text_8, 255L);
      }

      /* Object: text_9, Type: text, OID: 5534a9d9-6e50-4092-8015-2a3019abea7d */
      {
        static SGLuint8 lArray0_text_9[255UL] = {53U,48U};
        sgluWriteText(61.256F, 90.733F, lArray0_text_9, 255L);
      }

      /* Object: line_9, Type: line, OID: c57997d1-9cd4-4315-a325-6c74ed96221b */
      {
        /* outline object part */
        sglBegin(SGL_LINES);
        sglVertex2f(-49.005F, 97.757F);
        sglVertex2f(49.005F, 97.757F);
        sglEnd();
      }
      sglPopMatrixAndTranslate();
    }

    /* Object: PART_1, Type: container, OID: 965467ed-23ca-4977-9ad4-971bbb631d37 */
    {
      sglPushMatrixAndTranslate(-1.941F, 342.958F);

      /* Object: text_10, Type: text, OID: a8bc9018-6435-4321-9af3-aa434c4d1bf5 */
      {
        static SGLuint8 lArray0_text_10[255UL] = {56U,48U};
        sgluWriteText(-88.209F, 41.688F, lArray0_text_10, 255L);
      }

      /* Object: text_11, Type: text, OID: 6d2d7aab-c990-410a-88d2-8ecab107ed01 */
      {
        static SGLuint8 lArray0_text_11[255UL] = {53U,48U};
        sgluWriteText(-88.209F, -105.447F, lArray0_text_11, 255L);
      }

      /* Object: text_12, Type: text, OID: ba79ec32-7c29-4d65-8201-8630154268bb */
      {
        static SGLuint8 lArray0_text_12[255UL] = {57U,48U};
        sgluWriteText(-88.209F, 90.733F, lArray0_text_12, 255L);
      }

      /* Object: text_13, Type: text, OID: 57193f83-aa94-4782-9cdd-cba78adb1457 */
      {
        static SGLuint8 lArray0_text_13[255UL] = {57U,48U};
        sgluWriteText(61.256F, 90.733F, lArray0_text_13, 255L);
      }

      /* Object: text_14, Type: text, OID: 934cd307-8df5-497c-a3b0-51af60a04b59 */
      {
        static SGLuint8 lArray0_text_14[255UL] = {56U,48U};
        sgluWriteText(61.256F, 41.688F, lArray0_text_14, 255L);
      }

      /* Object: text_15, Type: text, OID: fb10fcb3-f9c7-423d-9b80-537e76907f4e */
      {
        static SGLuint8 lArray0_text_15[255UL] = {55U,48U};
        sgluWriteText(-88.209F, -7.357F, lArray0_text_15, 255L);
      }

      /* Object: text_16, Type: text, OID: f15a8108-4758-4056-8b2d-83a0f73e3d1c */
      {
        static SGLuint8 lArray0_text_16[255UL] = {55U,48U};
        sgluWriteText(61.256F, -7.357F, lArray0_text_16, 255L);
      }

      /* Object: text_17, Type: text, OID: b5e56c35-05e8-413a-ad7a-f7ef2bd460e3 */
      {
        static SGLuint8 lArray0_text_17[255UL] = {54U,48U};
        sgluWriteText(-88.209F, -56.402F, lArray0_text_17, 255L);
      }

      /* Object: text_18, Type: text, OID: 91c77318-324b-4994-9944-7e713a0094a4 */
      {
        static SGLuint8 lArray0_text_18[255UL] = {54U,48U};
        sgluWriteText(61.256F, -56.402F, lArray0_text_18, 255L);
      }

      /* Object: text_19, Type: text, OID: 306d0e9d-33c5-4b51-b475-86e1fc4719dd */
      {
        static SGLuint8 lArray0_text_19[255UL] = {53U,48U};
        sgluWriteText(61.256F, -105.447F, lArray0_text_19, 255L);
      }

      /* Object: line_10, Type: line, OID: 64de44cd-aaa8-486b-9928-21c19528904f */
      {
        /* outline object part */
        sglBegin(SGL_LINES);
        sglVertex2f(-49.005F, -97.31F);
        sglVertex2f(49.005F, -97.31F);
      }

      /* Object: line_11, Type: line, OID: 563d8a67-eacf-47cb-a948-a02595fdc397 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, -122.789F);
        sglVertex2f(9.801F, -122.789F);
      }

      /* Object: line_12, Type: line, OID: 09ed723d-1ee4-41bd-9e85-f3b3cae39d14 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, -48.437F);
        sglVertex2f(49.005F, -48.437F);
      }

      /* Object: line_13, Type: line, OID: e36e972a-9cb2-4279-8c0f-cf8fb53f4375 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, 0.868F);
        sglVertex2f(49.005F, 0.868F);
      }

      /* Object: line_14, Type: line, OID: 93bbd183-6849-4f95-897c-7b4f3f2b2373 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, 48.403F);
        sglVertex2f(49.005F, 48.403F);
      }

      /* Object: line_15, Type: line, OID: 812dbedc-eb9f-4ff9-9566-1e8bbb40f9c2 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, 98.924F);
        sglVertex2f(49.005F, 98.924F);
      }

      /* Object: line_16, Type: line, OID: 22edde27-10d4-4acd-8c59-efe6b7303330 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, -72.391F);
        sglVertex2f(9.801F, -72.391F);
      }

      /* Object: line_17, Type: line, OID: 410596f8-806f-4141-9478-32a5c2841424 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, -24.743F);
        sglVertex2f(9.801F, -24.743F);
      }

      /* Object: line_18, Type: line, OID: a37a53d1-e624-4887-a812-fa7379a9c9c9 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 25.116F);
        sglVertex2f(9.801F, 25.116F);
      }

      /* Object: line_19, Type: line, OID: 646fe8ec-bc07-49b1-af0f-e6388db901d7 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 74.416F);
        sglVertex2f(9.801F, 74.416F);
        sglEnd();
      }
      sglPopMatrixAndTranslate();
    }

    /* Object: PART_3, Type: container, OID: 928700fc-1d7a-44dc-b119-3e9785408a83 */
    {
      sglPushMatrixAndTranslate(-1.941F, -122.971F);

      /* Object: line_20, Type: line, OID: 41218f43-415b-4bff-98e9-fb669cc5772e */
      {
        /* outline object part */
        sglBegin(SGL_LINES);
        sglVertex2f(-9.801F, 98.09F);
        sglVertex2f(9.801F, 98.09F);
      }

      /* Object: line_21, Type: line, OID: 69e6a339-b15c-4447-80f5-71bec8b89b68 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, 73.568F);
        sglVertex2f(49.005F, 73.568F);
      }

      /* Object: line_22, Type: line, OID: e005c02d-ac6e-412a-aaa8-5e0d00efb2d1 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 49.045F);
        sglVertex2f(9.801F, 49.045F);
      }

      /* Object: line_23, Type: line, OID: f48588b1-6011-4733-8a73-dce75eb3781b */
      {
        /* outline object part */
        sglVertex2f(-49.005F, 24.523F);
        sglVertex2f(49.005F, 24.523F);
      }

      /* Object: line_24, Type: line, OID: 87001a25-d122-4543-a682-1ae412658f62 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 0.0F);
        sglVertex2f(9.801F, 0.0F);
      }

      /* Object: line_25, Type: line, OID: 87f1caca-48dc-45a1-8f29-20ebdd28833a */
      {
        /* outline object part */
        sglVertex2f(-49.005F, -24.523F);
        sglVertex2f(49.005F, -24.523F);
        sglEnd();
      }

      /* Object: text_20, Type: text, OID: 269d71e5-dec6-4f2e-9670-2da9d44be7f0 */
      {
        static SGLuint8 lArray0_text_20[255UL] = {49U,48U};
        sgluWriteText(-88.209F, 66.211F, lArray0_text_20, 255L);
      }

      /* Object: text_21, Type: text, OID: 1d4fc16e-4114-4a21-a45e-825a6b1d3155 */
      {
        static SGLuint8 lArray0_text_21[255UL] = {49U,48U};
        sgluWriteText(61.256F, 66.211F, lArray0_text_21, 255L);
      }

      /* Object: text_22, Type: text, OID: 52697591-fdee-4cee-8d74-fad2e32d2414 */
      {
        static SGLuint8 lArray0_text_22[255UL] = {50U,48U};
        sgluWriteText(-88.209F, 17.166F, lArray0_text_22, 255L);
      }

      /* Object: text_23, Type: text, OID: 62232e82-da34-4449-b388-369cb4a2ef10 */
      {
        static SGLuint8 lArray0_text_23[255UL] = {50U,48U};
        sgluWriteText(61.256F, 17.166F, lArray0_text_23, 255L);
      }

      /* Object: text_24, Type: text, OID: 42bf2924-4033-4e6d-8055-5b56b34bc146 */
      {
        static SGLuint8 lArray0_text_24[255UL] = {51U,48U};
        sgluWriteText(-88.209F, -31.879F, lArray0_text_24, 255L);
      }

      /* Object: text_25, Type: text, OID: b96f29fc-3d72-40cb-92ae-ddfe5963451b */
      {
        static SGLuint8 lArray0_text_25[255UL] = {51U,48U};
        sgluWriteText(61.256F, -31.879F, lArray0_text_25, 255L);
      }

      /* Object: text_26, Type: text, OID: fd60a5dd-945e-4335-9a67-3e553bf0db4e */
      {
        static SGLuint8 lArray0_text_26[255UL] = {52U,48U};
        sgluWriteText(-88.209F, -80.924F, lArray0_text_26, 255L);
      }

      /* Object: text_27, Type: text, OID: d47d4c8b-f068-441a-90b0-18938c3b9e1b */
      {
        static SGLuint8 lArray0_text_27[255UL] = {52U,48U};
        sgluWriteText(61.256F, -80.924F, lArray0_text_27, 255L);
      }

      /* Object: line_26, Type: line, OID: c66339aa-778f-4f52-b074-3d80a9bdfb1b */
      {
        /* outline object part */
        sglBegin(SGL_LINES);
        sglVertex2f(-9.801F, -48.986F);
        sglVertex2f(9.801F, -48.986F);
      }

      /* Object: line_27, Type: line, OID: ea9b0178-47ee-4877-b401-da3b03d01186 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, -73.734F);
        sglVertex2f(49.005F, -73.734F);
        sglEnd();
      }
      sglPopMatrixAndTranslate();
    }

    /* Object: PART_2, Type: container, OID: 570a1ccf-e560-4d21-aaa3-380ff0a60dd9 */
    {
      sglPushMatrixAndTranslate(-1.941F, 122.255F);

      /* Object: line_28, Type: line, OID: 9dcb8017-adca-4832-b3a0-520bda74abd7 */
      {
        /* outline object part */
        sglBegin(SGL_LINES);
        sglVertex2f(-49.005F, 24.523F);
        sglVertex2f(49.005F, 24.523F);
      }

      /* Object: line_29, Type: line, OID: 71221b69-2da5-40c4-986c-3ca383cc68c8 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 0.0F);
        sglVertex2f(9.801F, 0.0F);
      }

      /* Object: line_30, Type: line, OID: cf403556-3e7d-481a-8a4a-2ea19205bc83 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, -49.045F);
        sglVertex2f(9.801F, -49.045F);
      }

      /* Object: line_31, Type: line, OID: b1edafda-9eff-4b2e-8f38-1ac47b33a758 */
      {
        /* outline object part */
        sglVertex2f(-49.005F, -73.568F);
        sglVertex2f(49.005F, -73.568F);
      }

      /* Object: line_32, Type: line, OID: 55a2f1ff-41b2-41eb-9240-b11c3defdbc2 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, -98.09F);
        sglVertex2f(9.801F, -98.09F);
      }

      /* Object: line_33, Type: line, OID: e2db799e-4db1-4e4b-94a1-ca4d3e44ed0a */
      {
        /* outline object part */
        sglVertex2f(-49.005F, -24.523F);
        sglVertex2f(49.005F, -24.523F);
        sglEnd();
      }

      /* Object: text_28, Type: text, OID: 687a6250-ae35-4195-9b6c-49c701709cff */
      {
        static SGLuint8 lArray0_text_28[255UL] = {52U,48U};
        sgluWriteText(-88.209F, 66.211F, lArray0_text_28, 255L);
      }

      /* Object: text_29, Type: text, OID: f4b991d2-28c4-4920-9515-8191b88b2e5f */
      {
        static SGLuint8 lArray0_text_29[255UL] = {52U,48U};
        sgluWriteText(61.256F, 66.211F, lArray0_text_29, 255L);
      }

      /* Object: text_30, Type: text, OID: 1153a4e9-e98f-4df5-987f-b06d16a9d992 */
      {
        static SGLuint8 lArray0_text_30[255UL] = {51U,48U};
        sgluWriteText(-88.209F, 17.166F, lArray0_text_30, 255L);
      }

      /* Object: text_31, Type: text, OID: 0b3e335e-d777-4c7e-b348-0cfa08f6f0ef */
      {
        static SGLuint8 lArray0_text_31[255UL] = {51U,48U};
        sgluWriteText(61.256F, 17.166F, lArray0_text_31, 255L);
      }

      /* Object: text_32, Type: text, OID: 57a063bd-4eaf-4e1e-b1fa-b5e5fd3547c8 */
      {
        static SGLuint8 lArray0_text_32[255UL] = {50U,48U};
        sgluWriteText(-88.209F, -31.879F, lArray0_text_32, 255L);
      }

      /* Object: text_33, Type: text, OID: 371495fa-3357-4850-9e35-420929eefaed */
      {
        static SGLuint8 lArray0_text_33[255UL] = {50U,48U};
        sgluWriteText(61.256F, -31.879F, lArray0_text_33, 255L);
      }

      /* Object: text_34, Type: text, OID: f3bf19d8-8cd1-4f0e-9dcc-d195aa9d1485 */
      {
        static SGLuint8 lArray0_text_34[255UL] = {49U,48U};
        sgluWriteText(-88.209F, -80.924F, lArray0_text_34, 255L);
      }

      /* Object: text_35, Type: text, OID: 078f0a77-4e2d-4486-88b5-8c08520c89e7 */
      {
        static SGLuint8 lArray0_text_35[255UL] = {49U,48U};
        sgluWriteText(61.256F, -80.924F, lArray0_text_35, 255L);
      }

      /* Object: line_34, Type: line, OID: 98d438ea-e0b6-4855-8582-2c6b129ff024 */
      {
        /* outline object part */
        sglBegin(SGL_LINES);
        sglVertex2f(-49.005F, 74.23F);
        sglVertex2f(49.005F, 74.23F);
      }

      /* Object: line_35, Type: line, OID: 1f04c162-2242-4f10-9e26-27731e81fed4 */
      {
        /* outline object part */
        sglVertex2f(-9.801F, 48.878F);
        sglVertex2f(9.801F, 48.878F);
        sglEnd();
      }
      sglPopMatrixAndTranslate();
    }

    /* Object: HORIZON_LINE, Type: container, OID: 59b3cbb7-bad7-46cf-a9df-e486b5a1d439 */
    {

      /* Object: line_36, Type: line, OID: e72cdbc6-c257-4940-9367-9570dcaa941d */
      {
        /* outline object part */
        sglIndexLineWidthi(2L);
        sglBegin(SGL_LINES);
        sglVertex2f(-196.021F, 0.0F);
        sglVertex2f(196.021F, 0.0F);
        sglEnd();
      }
    }
    sglPopMatrixAndTranslate();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: begin_moving_1, Type: container, OID: c41cd992-a3d1-4a48-9012-091bf5febe73 */
  aol_symbology_layer_stc1 = sglBeginStaticSequence(-35.403F, -20.714F, 35.403F, 20.714F);

  /* Object: line_37, Type: line, OID: 0d154dc2-a17a-4ab1-bcc9-e515094a3411 */
  {
    /* outline object part */
    sglIndexColori(36L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(0.0F, -14.714F);
    sglVertex2f(-29.403F, 14.714F);
  }

  /* Object: line_38, Type: line, OID: f9ccdd34-f2cb-4087-b9c4-8d4f69a99a98 */
  {
    /* outline object part */
    sglVertex2f(-29.403F, 14.714F);
    sglVertex2f(-14.702F, 14.714F);
  }

  /* Object: line_39, Type: line, OID: 2e9b962e-e3c5-468a-8702-aaec13e3ebb2 */
  {
    /* outline object part */
    sglVertex2f(-14.702F, 14.714F);
    sglVertex2f(0.0F, 0.0F);
  }

  /* Object: line_40, Type: line, OID: 8e65ce4a-d2be-4f98-83e0-04440edc33cc */
  {
    /* outline object part */
    sglVertex2f(0.0F, 0.0F);
    sglVertex2f(14.702F, 14.714F);
  }

  /* Object: line_41, Type: line, OID: 12129036-db72-4127-9f5b-7873525a863d */
  {
    /* outline object part */
    sglVertex2f(14.702F, 14.714F);
    sglVertex2f(29.403F, 14.714F);
  }

  /* Object: line_42, Type: line, OID: 76ac3f06-4b98-4ade-9c33-72feec83e678 */
  {
    /* outline object part */
    sglVertex2f(29.403F, 14.714F);
    sglVertex2f(0.0F, -14.714F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: begin_moving_2, Type: container, OID: 43f31cba-c89b-4886-859b-bff0e14d074b */
  aol_symbology_layer_stc2 = sglBeginStaticSequence(-79.508F, -46.462F, 79.508F, 46.462F);

  /* Object: line_43, Type: line, OID: 6bc35e5c-dcee-420e-9baa-fee4596c4226 */
  {
    /* outline object part */
    sglIndexColori(36L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(0.0F, -15.94F);
    sglVertex2f(39.204F, 25.749F);
  }

  /* Object: line_44, Type: line, OID: 4b9417a9-0bf2-495c-9c63-6c25b45861fa */
  {
    /* outline object part */
    sglVertex2f(39.204F, 25.749F);
    sglVertex2f(14.702F, 25.749F);
  }

  /* Object: line_45, Type: line, OID: d3ac263e-0e8b-46d3-80a5-94cbe93944dc */
  {
    /* outline object part */
    sglVertex2f(14.702F, 40.462F);
    sglVertex2f(14.702F, 25.749F);
  }

  /* Object: line_46, Type: line, OID: a851c11b-35e6-46da-8000-6c52703169a2 */
  {
    /* outline object part */
    sglVertex2f(14.702F, 40.462F);
    sglVertex2f(73.508F, 40.462F);
  }

  /* Object: line_47, Type: line, OID: 89c5db14-a61f-43d3-9b62-71af3d6fa441 */
  {
    /* outline object part */
    sglVertex2f(73.508F, 40.462F);
    sglVertex2f(0.0F, -40.462F);
  }

  /* Object: line_48, Type: line, OID: d40278ae-cd62-4943-815d-2449c9705974 */
  {
    /* outline object part */
    sglVertex2f(-14.702F, 40.462F);
    sglVertex2f(-73.508F, 40.462F);
  }

  /* Object: line_49, Type: line, OID: 8a1ddea5-1a8e-4a12-bfab-63a8177f35ec */
  {
    /* outline object part */
    sglVertex2f(-14.702F, 40.462F);
    sglVertex2f(-14.702F, 25.749F);
  }

  /* Object: line_50, Type: line, OID: f3475e50-927a-4ace-90fa-878799b45b4c */
  {
    /* outline object part */
    sglVertex2f(-39.204F, 25.749F);
    sglVertex2f(-14.702F, 25.749F);
  }

  /* Object: line_51, Type: line, OID: a6119284-f451-494c-a526-f7ff98710c59 */
  {
    /* outline object part */
    sglVertex2f(0.0F, -15.94F);
    sglVertex2f(-39.204F, 25.749F);
  }

  /* Object: line_52, Type: line, OID: 95f0ba5c-c4ee-4951-b790-3d2acfe812f4 */
  {
    /* outline object part */
    sglVertex2f(-73.508F, 40.462F);
    sglVertex2f(0.0F, -40.462F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: begin_moving_3, Type: container, OID: 78cf04ed-ca57-409d-87d4-af6171a295e9 */
  aol_symbology_layer_stc3 = sglBeginStaticSequence(-35.403F, -20.714F, 35.403F, 20.714F);

  /* Object: line_53, Type: line, OID: bd4be11b-c843-42b8-8e39-a04e0db07f6c */
  {
    /* outline object part */
    sglIndexColori(36L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(0.0F, 0.0F);
    sglVertex2f(14.702F, -14.714F);
  }

  /* Object: line_54, Type: line, OID: 7c32afa9-32ea-4f0c-b266-5126888ab719 */
  {
    /* outline object part */
    sglVertex2f(14.702F, -14.714F);
    sglVertex2f(29.403F, -14.714F);
  }

  /* Object: line_55, Type: line, OID: cedb2133-b73c-4ed4-b7fc-d21340681323 */
  {
    /* outline object part */
    sglVertex2f(29.403F, -14.714F);
    sglVertex2f(0.0F, 14.714F);
  }

  /* Object: line_56, Type: line, OID: bc64007a-8607-45b9-a6d9-61b1cee2d91f */
  {
    /* outline object part */
    sglVertex2f(-14.702F, -14.714F);
    sglVertex2f(0.0F, 0.0F);
  }

  /* Object: line_57, Type: line, OID: 2a45fc32-3276-45c7-9082-c899ff7e7de3 */
  {
    /* outline object part */
    sglVertex2f(-29.403F, -14.714F);
    sglVertex2f(-14.702F, -14.714F);
  }

  /* Object: line_58, Type: line, OID: 2fda25ee-54d1-4cb5-865b-3d621546a349 */
  {
    /* outline object part */
    sglVertex2f(0.0F, 14.714F);
    sglVertex2f(-29.403F, -14.714F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: begin_moving_4, Type: container, OID: c583e163-9526-4e80-96f2-28106825490b */
  aol_symbology_layer_stc4 = sglBeginStaticSequence(-79.508F, -46.462F, 79.508F, 46.462F);

  /* Object: line_59, Type: line, OID: e06d7814-f51c-43d8-b622-234758486b77 */
  {
    /* outline object part */
    sglIndexColori(36L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(-73.508F, -40.462F);
    sglVertex2f(0.0F, 40.462F);
  }

  /* Object: line_60, Type: line, OID: 5f471187-db46-483d-8daa-b11bcb89a14e */
  {
    /* outline object part */
    sglVertex2f(73.508F, -40.462F);
    sglVertex2f(0.0F, 40.462F);
  }

  /* Object: line_61, Type: line, OID: 3204588c-0fdd-4749-aa9f-f8c3ca6af66d */
  {
    /* outline object part */
    sglVertex2f(14.702F, -40.462F);
    sglVertex2f(73.508F, -40.462F);
  }

  /* Object: line_62, Type: line, OID: c14948d9-1ef1-45d4-bfc3-93f1f66c6fb1 */
  {
    /* outline object part */
    sglVertex2f(-14.702F, -40.462F);
    sglVertex2f(-73.508F, -40.462F);
  }

  /* Object: line_63, Type: line, OID: 3c81ed7c-4aac-469a-9aab-c8fdb7609111 */
  {
    /* outline object part */
    sglVertex2f(-14.702F, -40.462F);
    sglVertex2f(-14.702F, -25.749F);
  }

  /* Object: line_64, Type: line, OID: 6206e74d-4d92-458a-9968-f25b3e0dffeb */
  {
    /* outline object part */
    sglVertex2f(-39.204F, -25.749F);
    sglVertex2f(-14.702F, -25.749F);
  }

  /* Object: line_65, Type: line, OID: 4847e5ce-d571-4df1-b24b-89a32a178f91 */
  {
    /* outline object part */
    sglVertex2f(0.0F, 15.94F);
    sglVertex2f(-39.204F, -25.749F);
  }

  /* Object: line_66, Type: line, OID: 0affa514-ed3d-4a51-bab1-dc5d1b7ecc00 */
  {
    /* outline object part */
    sglVertex2f(0.0F, 15.94F);
    sglVertex2f(39.204F, -25.749F);
  }

  /* Object: line_67, Type: line, OID: 5aa8fc99-44bc-4d2e-a625-8acc266af76d */
  {
    /* outline object part */
    sglVertex2f(39.204F, -25.749F);
    sglVertex2f(14.702F, -25.749F);
  }

  /* Object: line_68, Type: line, OID: ccf729d7-0001-4cf0-878a-fbee4392d6db */
  {
    /* outline object part */
    sglVertex2f(14.702F, -40.462F);
    sglVertex2f(14.702F, -25.749F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: BugReference, Type: container, OID: 91017c9b-4cc7-4582-b9e9-72396866927a */
  aol_symbology_layer_stc5 = sglBeginStaticSequence(-22.471F, -14.828F, 22.466F, 14.828F);

  /* Object: BugRef, Type: shape, OID: f90ed0e1-a15d-4726-b932-432294f1c391 */
  {
    /* color object part */
    sglIndexColori(16L);
    sglDisable(SGL_MODULATE);
    sglEnable(SGL_POLYGON_SMOOTH);
    sglTransparency8(255L);
    sglDisable(SGL_TEXTURE_2D);
    sglDisable(SGL_GRADIENT);
    /* fill object part */
    sglDisable(SGL_TESSELLATION);
    sglBegin(SGL_POLYGON);
    sglVertex2f(-0.196F, 8.828F);
    sglVertex2f(-16.471F, 0.0F);
    sglVertex2f(-0.196F, -8.828F);
    sglVertex2f(16.466F, 0.0F);
    sglEnd();
    /* outline object part */
    sglIndexColori(1L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglBegin(SGL_LINE_LOOP);
    sglVertex2f(-0.196F, 8.828F);
    sglVertex2f(-16.471F, 0.0F);
    sglVertex2f(-0.196F, -8.828F);
    sglVertex2f(16.466F, 0.0F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: lines, Type: container, OID: 385d301b-5209-446c-8df2-f369f88c5797 */
  aol_symbology_layer_stc6 = sglBeginStaticSequence(249.837F, -131.555F, 275.529F, 1312.561F);

  /* Object: line_73, Type: line, OID: befdba6d-3743-4ca8-8681-a730f2767b90 */
  {
    /* outline object part */
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(255.837F, 232.474F);
    sglVertex2f(265.608F, 232.474F);
  }

  /* Object: line_74, Type: line, OID: 2940237b-c52f-406b-b141-8a94f03142b6 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 268.277F);
    sglVertex2f(265.608F, 268.277F);
  }

  /* Object: line_75, Type: line, OID: a2bd0446-a5bd-484e-9cf3-05887d463cc7 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 304.08F);
    sglVertex2f(265.608F, 304.08F);
  }

  /* Object: line_76, Type: line, OID: 0ff99f6d-aa3d-4e9f-b3a5-81df526551f7 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 339.883F);
    sglVertex2f(265.608F, 339.883F);
  }

  /* Object: line_77, Type: line, OID: 448a0a72-edc3-4f04-9065-ef653c9044ea */
  {
    /* outline object part */
    sglVertex2f(255.837F, 375.685F);
    sglVertex2f(265.608F, 375.685F);
  }

  /* Object: line_78, Type: line, OID: ddb59a69-75a9-470a-956d-1491bfd85aa7 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 411.488F);
    sglVertex2f(269.529F, 411.488F);
  }

  /* Object: line_79, Type: line, OID: 30e201ec-0258-4747-b979-612f083f9ee1 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 447.291F);
    sglVertex2f(265.608F, 447.291F);
  }

  /* Object: line_80, Type: line, OID: 32affcf5-da00-4f4f-969f-9d9ef3a70fb9 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 483.094F);
    sglVertex2f(265.608F, 483.094F);
  }

  /* Object: line_81, Type: line, OID: ef6ea511-cdbe-4d99-a7a4-b79e9c07b69e */
  {
    /* outline object part */
    sglVertex2f(255.837F, 518.897F);
    sglVertex2f(265.608F, 518.897F);
  }

  /* Object: line_82, Type: line, OID: e43071ec-ab11-4cf8-93c7-5e8cb71e380a */
  {
    /* outline object part */
    sglVertex2f(255.837F, 554.7F);
    sglVertex2f(265.608F, 554.7F);
  }

  /* Object: line_83, Type: line, OID: 13701f32-fcaf-46dd-b4f0-5a80029e040d */
  {
    /* outline object part */
    sglVertex2f(255.837F, 590.503F);
    sglVertex2f(269.529F, 590.503F);
  }

  /* Object: line_84, Type: line, OID: b8d7bb26-3e7c-4229-ad34-7529c83ddb3d */
  {
    /* outline object part */
    sglVertex2f(255.837F, 626.306F);
    sglVertex2f(265.608F, 626.306F);
  }

  /* Object: line_85, Type: line, OID: ed63b919-807e-4eda-bfb4-79791ce8def5 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 662.109F);
    sglVertex2f(265.608F, 662.109F);
  }

  /* Object: line_86, Type: line, OID: b5d1b0fc-1cf0-4f20-8cc5-870f8f90b673 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 697.912F);
    sglVertex2f(265.608F, 697.912F);
  }

  /* Object: line_87, Type: line, OID: 6de9d5c2-c952-4414-a055-2e87b2e29fcf */
  {
    /* outline object part */
    sglVertex2f(255.837F, 733.715F);
    sglVertex2f(265.608F, 733.715F);
  }

  /* Object: line_88, Type: line, OID: 064dee46-adeb-484e-b0f6-3df5645154f4 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 769.517F);
    sglVertex2f(269.529F, 769.517F);
  }

  /* Object: line_89, Type: line, OID: ec5e4fc3-f5a9-4eb1-b984-f66a0248a977 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 805.32F);
    sglVertex2f(265.608F, 805.32F);
  }

  /* Object: line_90, Type: line, OID: 9992c24a-7d02-4f77-adc2-032b0890bf5f */
  {
    /* outline object part */
    sglVertex2f(255.837F, 841.123F);
    sglVertex2f(265.608F, 841.123F);
  }

  /* Object: line_91, Type: line, OID: 87e0b195-656f-47e8-b392-291a2b4c255a */
  {
    /* outline object part */
    sglVertex2f(255.837F, 876.926F);
    sglVertex2f(265.608F, 876.926F);
  }

  /* Object: line_92, Type: line, OID: bccbd31c-172a-4212-bdb7-6b59be50cdb7 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 912.729F);
    sglVertex2f(265.608F, 912.729F);
  }

  /* Object: line_93, Type: line, OID: f664a7a2-e4e9-4c40-948b-abe1ed3c0a6e */
  {
    /* outline object part */
    sglVertex2f(255.837F, 948.532F);
    sglVertex2f(269.529F, 948.532F);
  }

  /* Object: line_94, Type: line, OID: ba86605a-f454-4e12-8262-e49108004a60 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 984.335F);
    sglVertex2f(265.608F, 984.335F);
  }

  /* Object: line_95, Type: line, OID: 47c53cc0-4992-45b9-8aea-0a7172611a28 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1020.138F);
    sglVertex2f(265.608F, 1020.138F);
  }

  /* Object: line_96, Type: line, OID: e978bfce-4d59-4ad3-afea-0100c0c5973c */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1055.941F);
    sglVertex2f(265.608F, 1055.941F);
  }

  /* Object: line_97, Type: line, OID: 83916efe-4b38-4cfe-9290-7db3bd988de0 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1091.744F);
    sglVertex2f(265.608F, 1091.744F);
  }

  /* Object: line_98, Type: line, OID: ec5f388a-7ef8-4b2d-af80-af56e14489d1 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1127.547F);
    sglVertex2f(269.529F, 1127.547F);
  }

  /* Object: line_99, Type: line, OID: 11f4bda3-622f-4c3a-b72d-91126e68fae2 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1163.35F);
    sglVertex2f(265.608F, 1163.35F);
  }

  /* Object: line_100, Type: line, OID: 4986f992-9157-4875-a82e-46c8a1bd223c */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1199.152F);
    sglVertex2f(265.608F, 1199.152F);
  }

  /* Object: line_101, Type: line, OID: 6a662c71-20af-4bc9-b8e8-ae18ba5b6c97 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1234.955F);
    sglVertex2f(265.608F, 1234.955F);
  }

  /* Object: line_102, Type: line, OID: fa010470-6022-4d87-9165-3e59e7ff9d9b */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1270.758F);
    sglVertex2f(265.608F, 1270.758F);
  }

  /* Object: line_103, Type: line, OID: a392f297-23b1-46cc-ac59-6c642bf71006 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 1306.561F);
    sglVertex2f(269.529F, 1306.561F);
  }

  /* Object: line_104, Type: line, OID: f42b05df-1416-43d6-81c5-b3786a247b0b */
  {
    /* outline object part */
    sglVertex2f(255.837F, 196.671F);
    sglVertex2f(265.608F, 196.671F);
  }

  /* Object: line_105, Type: line, OID: 7527aef7-c6a2-46f8-81ff-50e6387a0a8d */
  {
    /* outline object part */
    sglVertex2f(255.837F, 160.868F);
    sglVertex2f(265.608F, 160.868F);
  }

  /* Object: line_106, Type: line, OID: 8f89e736-f792-42f1-bdab-270f952bd917 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 125.065F);
    sglVertex2f(265.608F, 125.065F);
  }

  /* Object: line_107, Type: line, OID: 19209366-dd9b-4f95-8406-679d52c331c3 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 89.262F);
    sglVertex2f(265.608F, 89.262F);
  }

  /* Object: line_108, Type: line, OID: 06737338-8a2f-4150-aa2a-c2d2a588c701 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 53.459F);
    sglVertex2f(269.529F, 53.459F);
  }

  /* Object: line_109, Type: line, OID: 0d2f80e0-4996-4e51-8f73-434de7ef7d49 */
  {
    /* outline object part */
    sglVertex2f(255.837F, 17.656F);
    sglVertex2f(265.608F, 17.656F);
  }

  /* Object: line_110, Type: line, OID: f73d4e8f-2ffd-4c5b-9a73-4374cff7510f */
  {
    /* outline object part */
    sglVertex2f(255.837F, -18.147F);
    sglVertex2f(265.608F, -18.147F);
  }

  /* Object: line_111, Type: line, OID: e8477c06-4a77-48d6-b24a-a9f8cfcab3b2 */
  {
    /* outline object part */
    sglVertex2f(255.837F, -53.95F);
    sglVertex2f(265.608F, -53.95F);
  }

  /* Object: line_112, Type: line, OID: d7dbfd48-29a0-4170-b067-92d0b71a9f21 */
  {
    /* outline object part */
    sglVertex2f(255.837F, -89.753F);
    sglVertex2f(265.608F, -89.753F);
  }

  /* Object: line_113, Type: line, OID: ac70f569-34e8-447a-8cef-bc4eede48f03 */
  {
    /* outline object part */
    sglVertex2f(255.837F, -125.555F);
    sglVertex2f(269.529F, -125.555F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: texts, Type: container, OID: 6735061e-83bc-41b0-a081-b5a666dd730d */
  aol_symbology_layer_stc7 = sglBeginStaticSequence(286.10153F, -176.07614F, 341.26572F, 1321.0771F);

  /* Object: text_36, Type: text, OID: 0bc64f93-94e5-4b56-8f23-59c11bfcc6d0 */
  {
    static SGLuint8 lArray0_text_36[255UL] = {48U};
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexFontLineWidthi(2L);
    sglIndexFonti(2L);
    sglDisable(SGL_LINE_HALOING);
    sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    sgluWriteText(321.582F, 232.964F, lArray0_text_36, 255L);
  }

  /* Object: text_37, Type: text, OID: 98def996-0086-42ed-b90b-0247db0a67e7 */
  {
    static SGLuint8 lArray0_text_37[255UL] = {45U,53U};
    sgluWriteText(311.585F, 53.798F, lArray0_text_37, 255L);
  }

  /* Object: text_38, Type: text, OID: a24e053b-14bb-4d6f-bde7-85e5cfa32cc2 */
  {
    static SGLuint8 lArray0_text_38[255UL] = {45U,49U,48U};
    sgluWriteText(311.585F, -161.02F, lArray0_text_38, 255L);
  }

  /* Object: text_39, Type: text, OID: 9176ebed-db53-4a88-a2f7-727ef24f9163 */
  {
    static SGLuint8 lArray0_text_39[255UL] = {53U};
    sgluWriteText(321.582F, 411.797F, lArray0_text_39, 255L);
  }

  /* Object: text_40, Type: text, OID: 19beac89-30a3-47d5-9462-0bdd1222c1fd */
  {
    static SGLuint8 lArray0_text_40[255UL] = {49U,48U};
    sgluWriteText(321.582F, 590.63F, lArray0_text_40, 255L);
  }

  /* Object: text_41, Type: text, OID: d2acf49e-9e3d-43c8-81bf-fe8d1f49ddee */
  {
    static SGLuint8 lArray0_text_41[255UL] = {49U,53U};
    sgluWriteText(321.582F, 769.464F, lArray0_text_41, 255L);
  }

  /* Object: text_42, Type: text, OID: c325fb80-d0f0-4c33-9bdf-41e918c0d5f9 */
  {
    static SGLuint8 lArray0_text_42[255UL] = {50U,48U};
    sgluWriteText(321.582F, 948.297F, lArray0_text_42, 255L);
  }

  /* Object: text_43, Type: text, OID: f5853811-0a81-4c71-a4b9-4844fb3cd42e */
  {
    static SGLuint8 lArray0_text_43[255UL] = {50U,53U};
    sgluWriteText(321.582F, 1127.13F, lArray0_text_43, 255L);
  }

  /* Object: text_44, Type: text, OID: 91ec3734-5785-4ef8-b4c3-99742dd85ebb */
  {
    static SGLuint8 lArray0_text_44[255UL] = {51U,48U};
    sgluWriteText(321.582F, 1305.963F, lArray0_text_44, 255L);
  }
  sglEndStaticSequence();
  /* Static sequence for Object: CounterBox, Type: container, OID: 13bec8d9-95b7-4f13-a33d-4e55244f506f */
  aol_symbology_layer_stc8 = sglBeginStaticSequence(-61.576996F, -26.074005F, 68.58002F, 26.677002F);

  /* Object: CounterBackground, Type: shape, OID: 43bc71c9-e6b1-4d26-be76-e85687e1a3f9 */
  {
    /* color object part */
    sglIndexColori(1L);
    sglDisable(SGL_MODULATE);
    sglDisable(SGL_POLYGON_SMOOTH);
    sglTransparency8(255L);
    sglDisable(SGL_TEXTURE_2D);
    sglDisable(SGL_GRADIENT);
    /* fill object part */
    sglDisable(SGL_TESSELLATION);
    sglBegin(SGL_POLYGON);
    sglVertex2f(27.33F, 20.677F);
    sglVertex2f(27.33F, 15.175F);
    sglVertex2f(62.33F, 14.924F);
    sglVertex2f(62.58F, -14.576F);
    sglVertex2f(26.83F, -14.826F);
    sglVertex2f(26.33F, -20.074F);
    sglVertex2f(-43.08F, -20.064F);
    sglVertex2f(-55.577F, -0.554F);
    sglVertex2f(-43.08F, 20.207F);
    sglVertex2f(27.58F, 20.677F);
    sglEnd();
    /* outline object part */
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglBegin(SGL_LINE_LOOP);
    sglVertex2f(27.33F, 20.677F);
    sglVertex2f(27.33F, 15.175F);
    sglVertex2f(62.33F, 14.924F);
    sglVertex2f(62.58F, -14.576F);
    sglVertex2f(26.83F, -14.826F);
    sglVertex2f(26.33F, -20.074F);
    sglVertex2f(-43.08F, -20.064F);
    sglVertex2f(-55.577F, -0.554F);
    sglVertex2f(-43.08F, 20.207F);
    sglVertex2f(27.58F, 20.677F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: Outline, Type: container, OID: 12cb0ba7-92dd-4d6b-8209-15acb728e256 */
  aol_symbology_layer_stc9 = sglBeginStaticSequence(-20.701996F, -203.161F, 85.07498F, 203.75002F);

  /* Object: line_114, Type: line, OID: 7722f5db-c3e8-4612-8989-9817a4623919 */
  {
    /* outline object part */
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(0.098F, 197.75F);
    sglVertex2f(0.0F, -197.161F);
  }

  /* Object: line_115, Type: line, OID: 872a9eb4-8970-440d-9bb6-38470dc76f1f */
  {
    /* outline object part */
    sglVertex2f(79.075F, 197.75F);
    sglVertex2f(-13.898F, 197.75F);
  }

  /* Object: line_116, Type: line, OID: 725f75bd-0eb3-4ab9-8a12-b3cc06c591d3 */
  {
    /* outline object part */
    sglVertex2f(-14.702F, -197.161F);
    sglVertex2f(78.408F, -197.161F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: Outline_1, Type: container, OID: 1c56295d-2211-48f9-a8fa-db85342bd84e */
  aol_symbology_layer_stc10 = sglBeginStaticSequence(-51.144012F, -203.181F, 58.406006F, 203.02402F);

  /* Object: line_117, Type: line, OID: dcd81442-2164-4b05-9b7a-7a677d64c1a6 */
  {
    /* outline object part */
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(-45.144F, 197.024F);
    sglVertex2f(52.406F, 196.681F);
  }

  /* Object: line_118, Type: line, OID: 44d90747-977f-46c7-a4f7-873a26dd8498 */
  {
    /* outline object part */
    sglVertex2f(41.654F, 196.18F);
    sglVertex2f(41.654F, -196.18F);
  }

  /* Object: line_119, Type: line, OID: 93088548-272d-42d7-983b-912b6ed26c10 */
  {
    /* outline object part */
    sglVertex2f(-45.144F, -197.181F);
    sglVertex2f(52.406F, -197.181F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: lines1, Type: container, OID: 869a7410-f7fb-47a3-8004-031f02fa60ba */
  aol_symbology_layer_stc11 = sglBeginStaticSequence(-268.736F, 237.278F, -242.736F, 1352.798F);

  /* Object: line_120, Type: line, OID: ea7396f4-7f45-4b4a-9d73-a400e9eab908 */
  {
    /* outline object part */
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(2L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(-248.736F, 243.278F);
    sglVertex2f(-262.736F, 243.278F);
  }

  /* Object: line_121, Type: line, OID: f158be29-3b3e-4f2d-ba53-746ef86afdb6 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 287.419F);
    sglVertex2f(-262.736F, 287.419F);
  }

  /* Object: line_122, Type: line, OID: b145604a-5d6e-489f-bfdb-945a79673801 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 331.564F);
    sglVertex2f(-262.736F, 331.564F);
  }

  /* Object: line_123, Type: line, OID: de40aba0-f9e4-4c9b-aeab-af94dd8b3ef6 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 375.705F);
    sglVertex2f(-262.736F, 375.705F);
  }

  /* Object: line_124, Type: line, OID: 9979ef61-d866-4702-aa69-8d93cbf33d06 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 419.846F);
    sglVertex2f(-262.736F, 419.846F);
  }

  /* Object: line_125, Type: line, OID: 918e6d11-b5fa-48c6-bce9-1f3373857c61 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 463.986F);
    sglVertex2f(-262.736F, 463.986F);
  }

  /* Object: line_126, Type: line, OID: eb5ddb7c-4a7a-4f34-8de8-c94383ca9e0a */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 508.127F);
    sglVertex2f(-262.736F, 508.127F);
  }

  /* Object: line_127, Type: line, OID: 7d068db5-b673-46cf-b2a8-02b2083fd51d */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 552.267F);
    sglVertex2f(-262.736F, 552.267F);
  }

  /* Object: line_128, Type: line, OID: 7af91f56-5a22-4d92-a480-8846f9b2c736 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 596.408F);
    sglVertex2f(-262.736F, 596.408F);
  }

  /* Object: line_129, Type: line, OID: 68160e32-49f6-4625-af96-c7d365337494 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 640.549F);
    sglVertex2f(-262.736F, 640.549F);
  }

  /* Object: line_130, Type: line, OID: ada76c6a-1cca-45a8-8fd9-3dcd7b3a5cc6 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 684.689F);
    sglVertex2f(-262.736F, 684.689F);
  }

  /* Object: line_131, Type: line, OID: b005a30c-96e3-4304-b56b-64b0b5dfc293 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 728.83F);
    sglVertex2f(-262.736F, 728.83F);
  }

  /* Object: line_132, Type: line, OID: 7b48f236-8e63-40d7-92e1-65819ad3bf69 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 772.97F);
    sglVertex2f(-262.736F, 772.97F);
  }

  /* Object: line_133, Type: line, OID: 705313c0-664d-4b9f-a555-bf9b61bb96e3 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 817.111F);
    sglVertex2f(-262.736F, 817.111F);
  }

  /* Object: line_134, Type: line, OID: 3866287a-1472-4f04-bbb7-35e157616f8b */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 861.251F);
    sglVertex2f(-262.736F, 861.251F);
  }

  /* Object: line_135, Type: line, OID: a7d881e2-a8ba-4012-9f31-164e429e2627 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 905.392F);
    sglVertex2f(-262.736F, 905.392F);
  }

  /* Object: line_136, Type: line, OID: a473eade-bccb-4c8e-bcf3-93e03e8cdf9f */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 949.533F);
    sglVertex2f(-262.736F, 949.533F);
  }

  /* Object: line_137, Type: line, OID: b9370101-e0cb-4e41-8dbb-0233f9006a84 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 993.673F);
    sglVertex2f(-262.736F, 993.673F);
  }

  /* Object: line_138, Type: line, OID: d0d846e8-ace2-441c-8a7e-fd48d5029ffc */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1037.814F);
    sglVertex2f(-262.736F, 1037.814F);
  }

  /* Object: line_139, Type: line, OID: 9d397a42-4dea-4922-b9cd-1d9147373ef3 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1081.954F);
    sglVertex2f(-262.736F, 1081.954F);
  }

  /* Object: line_140, Type: line, OID: a8e3970c-a344-4981-a5f8-1fa1db78ad1a */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1126.095F);
    sglVertex2f(-262.736F, 1126.095F);
  }

  /* Object: line_141, Type: line, OID: f5061a41-7c57-4958-ba84-60c2b0cfa408 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1170.235F);
    sglVertex2f(-262.736F, 1170.235F);
  }

  /* Object: line_142, Type: line, OID: fe45070f-4504-4947-8845-d024b10dc1e5 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1214.376F);
    sglVertex2f(-262.736F, 1214.376F);
  }

  /* Object: line_143, Type: line, OID: afae389a-ac3d-4b1a-860d-346a61fd12b3 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1258.517F);
    sglVertex2f(-262.736F, 1258.517F);
  }

  /* Object: line_144, Type: line, OID: f98b6b9e-95e1-42d0-add4-d1a9bddc7ad3 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1302.657F);
    sglVertex2f(-262.736F, 1302.657F);
  }

  /* Object: line_145, Type: line, OID: 94559f82-9d4f-43a1-a15e-dd7e2d83010d */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1346.798F);
    sglVertex2f(-262.736F, 1346.798F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: lines2, Type: container, OID: 3c79cfc6-7852-42b2-83e0-9fb842e5d8c2 */
  aol_symbology_layer_stc12 = sglBeginStaticSequence(-268.736F, 237.27795F, -242.736F, 1352.7981F);

  /* Object: line_146, Type: line, OID: ea7396f4-7f45-4b4a-9d73-a400e9eab908 */
  {
    /* outline object part */
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(2L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglTransparency8(255L);
    sglBegin(SGL_LINES);
    sglVertex2f(-248.736F, 243.278F);
    sglVertex2f(-262.736F, 243.278F);
  }

  /* Object: line_147, Type: line, OID: f158be29-3b3e-4f2d-ba53-746ef86afdb6 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 287.419F);
    sglVertex2f(-262.736F, 287.419F);
  }

  /* Object: line_148, Type: line, OID: b145604a-5d6e-489f-bfdb-945a79673801 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 331.564F);
    sglVertex2f(-262.736F, 331.564F);
  }

  /* Object: line_149, Type: line, OID: de40aba0-f9e4-4c9b-aeab-af94dd8b3ef6 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 375.705F);
    sglVertex2f(-262.736F, 375.705F);
  }

  /* Object: line_150, Type: line, OID: 9979ef61-d866-4702-aa69-8d93cbf33d06 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 419.846F);
    sglVertex2f(-262.736F, 419.846F);
  }

  /* Object: line_151, Type: line, OID: 918e6d11-b5fa-48c6-bce9-1f3373857c61 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 463.986F);
    sglVertex2f(-262.736F, 463.986F);
  }

  /* Object: line_152, Type: line, OID: eb5ddb7c-4a7a-4f34-8de8-c94383ca9e0a */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 508.127F);
    sglVertex2f(-262.736F, 508.127F);
  }

  /* Object: line_153, Type: line, OID: 7d068db5-b673-46cf-b2a8-02b2083fd51d */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 552.267F);
    sglVertex2f(-262.736F, 552.267F);
  }

  /* Object: line_154, Type: line, OID: 7af91f56-5a22-4d92-a480-8846f9b2c736 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 596.408F);
    sglVertex2f(-262.736F, 596.408F);
  }

  /* Object: line_155, Type: line, OID: 68160e32-49f6-4625-af96-c7d365337494 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 640.549F);
    sglVertex2f(-262.736F, 640.549F);
  }

  /* Object: line_156, Type: line, OID: ada76c6a-1cca-45a8-8fd9-3dcd7b3a5cc6 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 684.689F);
    sglVertex2f(-262.736F, 684.689F);
  }

  /* Object: line_157, Type: line, OID: b005a30c-96e3-4304-b56b-64b0b5dfc293 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 728.83F);
    sglVertex2f(-262.736F, 728.83F);
  }

  /* Object: line_158, Type: line, OID: 7b48f236-8e63-40d7-92e1-65819ad3bf69 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 772.97F);
    sglVertex2f(-262.736F, 772.97F);
  }

  /* Object: line_159, Type: line, OID: 705313c0-664d-4b9f-a555-bf9b61bb96e3 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 817.111F);
    sglVertex2f(-262.736F, 817.111F);
  }

  /* Object: line_160, Type: line, OID: 3866287a-1472-4f04-bbb7-35e157616f8b */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 861.251F);
    sglVertex2f(-262.736F, 861.251F);
  }

  /* Object: line_161, Type: line, OID: a7d881e2-a8ba-4012-9f31-164e429e2627 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 905.392F);
    sglVertex2f(-262.736F, 905.392F);
  }

  /* Object: line_162, Type: line, OID: a473eade-bccb-4c8e-bcf3-93e03e8cdf9f */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 949.533F);
    sglVertex2f(-262.736F, 949.533F);
  }

  /* Object: line_163, Type: line, OID: b9370101-e0cb-4e41-8dbb-0233f9006a84 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 993.673F);
    sglVertex2f(-262.736F, 993.673F);
  }

  /* Object: line_164, Type: line, OID: d0d846e8-ace2-441c-8a7e-fd48d5029ffc */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1037.814F);
    sglVertex2f(-262.736F, 1037.814F);
  }

  /* Object: line_165, Type: line, OID: 9d397a42-4dea-4922-b9cd-1d9147373ef3 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1081.954F);
    sglVertex2f(-262.736F, 1081.954F);
  }

  /* Object: line_166, Type: line, OID: a8e3970c-a344-4981-a5f8-1fa1db78ad1a */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1126.095F);
    sglVertex2f(-262.736F, 1126.095F);
  }

  /* Object: line_167, Type: line, OID: f5061a41-7c57-4958-ba84-60c2b0cfa408 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1170.235F);
    sglVertex2f(-262.736F, 1170.235F);
  }

  /* Object: line_168, Type: line, OID: fe45070f-4504-4947-8845-d024b10dc1e5 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1214.376F);
    sglVertex2f(-262.736F, 1214.376F);
  }

  /* Object: line_169, Type: line, OID: afae389a-ac3d-4b1a-860d-346a61fd12b3 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1258.517F);
    sglVertex2f(-262.736F, 1258.517F);
  }

  /* Object: line_170, Type: line, OID: f98b6b9e-95e1-42d0-add4-d1a9bddc7ad3 */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1302.657F);
    sglVertex2f(-262.736F, 1302.657F);
  }

  /* Object: line_171, Type: line, OID: 94559f82-9d4f-43a1-a15e-dd7e2d83010d */
  {
    /* outline object part */
    sglVertex2f(-248.736F, 1346.798F);
    sglVertex2f(-262.736F, 1346.798F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: numbers1, Type: container, OID: 3e815ecb-ec99-4524-9f69-fa0f7c12c532 */
  aol_symbology_layer_stc13 = sglBeginStaticSequence(-313.01678F, 228.78172F, -264.98328F, 1317.2195F);

  /* Object: text_45, Type: text, OID: 724e789e-e03f-4fc4-b848-eb778213ad6e */
  {
    static SGLuint8 lArray0_text_45[255UL] = {48U};
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexFontLineWidthi(2L);
    sglIndexFonti(1L);
    sglDisable(SGL_LINE_HALOING);
    sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    sgluWriteText(-288.739F, 243.283F, lArray0_text_45, 255L);
  }

  /* Object: text_46, Type: text, OID: 18ad26a0-87c5-4b4c-a9d9-ac3a445200f1 */
  {
    static SGLuint8 lArray0_text_46[255UL] = {50U,48U};
    sgluWriteText(-288.739F, 331.564F, lArray0_text_46, 255L);
  }

  /* Object: text_47, Type: text, OID: 538219b3-5b1d-4b22-ba19-41104eaeb203 */
  {
    static SGLuint8 lArray0_text_47[255UL] = {52U,48U};
    sgluWriteText(-288.739F, 419.846F, lArray0_text_47, 255L);
  }

  /* Object: text_48, Type: text, OID: a0967331-d38e-4f87-b230-8da0ed72dec7 */
  {
    static SGLuint8 lArray0_text_48[255UL] = {54U,48U};
    sgluWriteText(-288.739F, 508.127F, lArray0_text_48, 255L);
  }

  /* Object: text_49, Type: text, OID: dcf1b5c7-8765-40ef-ab64-ce70608e0983 */
  {
    static SGLuint8 lArray0_text_49[255UL] = {56U,48U};
    sgluWriteText(-288.739F, 596.408F, lArray0_text_49, 255L);
  }

  /* Object: text_50, Type: text, OID: a5554064-bacb-4578-9784-c307b2183b9e */
  {
    static SGLuint8 lArray0_text_50[255UL] = {49U,48U,48U};
    sgluWriteText(-288.739F, 684.689F, lArray0_text_50, 255L);
  }

  /* Object: text_51, Type: text, OID: 869a6757-3ce3-4241-b0c9-7c5b487493ab */
  {
    static SGLuint8 lArray0_text_51[255UL] = {49U,50U,48U};
    sgluWriteText(-288.739F, 772.97F, lArray0_text_51, 255L);
  }

  /* Object: text_52, Type: text, OID: 7f57a35d-52e1-425d-8034-dee30cb0e89c */
  {
    static SGLuint8 lArray0_text_52[255UL] = {49U,52U,48U};
    sgluWriteText(-288.739F, 861.251F, lArray0_text_52, 255L);
  }

  /* Object: text_53, Type: text, OID: 15bb5ae1-e164-44f6-8e57-61de504c3773 */
  {
    static SGLuint8 lArray0_text_53[255UL] = {49U,54U,48U};
    sgluWriteText(-288.739F, 949.533F, lArray0_text_53, 255L);
  }

  /* Object: text_54, Type: text, OID: 45c9ecac-5974-4673-b07c-e6301fb6f1fd */
  {
    static SGLuint8 lArray0_text_54[255UL] = {49U,56U,48U};
    sgluWriteText(-288.739F, 1037.814F, lArray0_text_54, 255L);
  }

  /* Object: text_55, Type: text, OID: 5c5d908f-c6e7-4caa-aa38-234a9baf91de */
  {
    static SGLuint8 lArray0_text_55[255UL] = {50U,48U,48U};
    sgluWriteText(-288.739F, 1126.095F, lArray0_text_55, 255L);
  }

  /* Object: text_56, Type: text, OID: 0e646773-48b9-43c2-91d2-4700c8506a4e */
  {
    static SGLuint8 lArray0_text_56[255UL] = {50U,50U,48U};
    sgluWriteText(-288.739F, 1214.376F, lArray0_text_56, 255L);
  }

  /* Object: text_57, Type: text, OID: 967d07da-0f81-4f4c-a585-fd7aed49228d */
  {
    static SGLuint8 lArray0_text_57[255UL] = {50U,52U,48U};
    sgluWriteText(-288.739F, 1302.657F, lArray0_text_57, 255L);
  }
  sglEndStaticSequence();
  /* Static sequence for Object: numbers2, Type: container, OID: 376c0fd6-e5a6-48b4-b865-1d7bdea90c40 */
  aol_symbology_layer_stc14 = sglBeginStaticSequence(-313.01678F, 228.78174F, -264.98328F, 1317.2195F);

  /* Object: text_58, Type: text, OID: 724e789e-e03f-4fc4-b848-eb778213ad6e */
  {
    static SGLuint8 lArray0_text_58[255UL] = {50U,54U,48U};
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexFontLineWidthi(2L);
    sglIndexFonti(1L);
    sglDisable(SGL_LINE_HALOING);
    sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
    sgluWriteText(-288.739F, 243.283F, lArray0_text_58, 255L);
  }

  /* Object: text_59, Type: text, OID: 18ad26a0-87c5-4b4c-a9d9-ac3a445200f1 */
  {
    static SGLuint8 lArray0_text_59[255UL] = {50U,56U,48U};
    sgluWriteText(-288.739F, 331.564F, lArray0_text_59, 255L);
  }

  /* Object: text_60, Type: text, OID: 538219b3-5b1d-4b22-ba19-41104eaeb203 */
  {
    static SGLuint8 lArray0_text_60[255UL] = {51U,48U,48U};
    sgluWriteText(-288.739F, 419.846F, lArray0_text_60, 255L);
  }

  /* Object: text_61, Type: text, OID: a0967331-d38e-4f87-b230-8da0ed72dec7 */
  {
    static SGLuint8 lArray0_text_61[255UL] = {51U,50U,48U};
    sgluWriteText(-288.739F, 508.127F, lArray0_text_61, 255L);
  }

  /* Object: text_62, Type: text, OID: dcf1b5c7-8765-40ef-ab64-ce70608e0983 */
  {
    static SGLuint8 lArray0_text_62[255UL] = {51U,52U,48U};
    sgluWriteText(-288.739F, 596.408F, lArray0_text_62, 255L);
  }

  /* Object: text_63, Type: text, OID: a5554064-bacb-4578-9784-c307b2183b9e */
  {
    static SGLuint8 lArray0_text_63[255UL] = {51U,54U,48U};
    sgluWriteText(-288.739F, 684.689F, lArray0_text_63, 255L);
  }

  /* Object: text_64, Type: text, OID: 869a6757-3ce3-4241-b0c9-7c5b487493ab */
  {
    static SGLuint8 lArray0_text_64[255UL] = {51U,56U,48U};
    sgluWriteText(-288.739F, 772.97F, lArray0_text_64, 255L);
  }

  /* Object: text_65, Type: text, OID: 7f57a35d-52e1-425d-8034-dee30cb0e89c */
  {
    static SGLuint8 lArray0_text_65[255UL] = {52U,48U,48U};
    sgluWriteText(-288.739F, 861.251F, lArray0_text_65, 255L);
  }

  /* Object: text_66, Type: text, OID: 15bb5ae1-e164-44f6-8e57-61de504c3773 */
  {
    static SGLuint8 lArray0_text_66[255UL] = {52U,50U,48U};
    sgluWriteText(-288.739F, 949.533F, lArray0_text_66, 255L);
  }

  /* Object: text_67, Type: text, OID: 45c9ecac-5974-4673-b07c-e6301fb6f1fd */
  {
    static SGLuint8 lArray0_text_67[255UL] = {52U,52U,48U};
    sgluWriteText(-288.739F, 1037.814F, lArray0_text_67, 255L);
  }

  /* Object: text_68, Type: text, OID: 5c5d908f-c6e7-4caa-aa38-234a9baf91de */
  {
    static SGLuint8 lArray0_text_68[255UL] = {52U,54U,48U};
    sgluWriteText(-288.739F, 1126.095F, lArray0_text_68, 255L);
  }

  /* Object: text_69, Type: text, OID: 0e646773-48b9-43c2-91d2-4700c8506a4e */
  {
    static SGLuint8 lArray0_text_69[255UL] = {52U,56U,48U};
    sgluWriteText(-288.739F, 1214.376F, lArray0_text_69, 255L);
  }

  /* Object: text_70, Type: text, OID: 967d07da-0f81-4f4c-a585-fd7aed49228d */
  {
    static SGLuint8 lArray0_text_70[255UL] = {53U,48U,48U};
    sgluWriteText(-288.739F, 1302.657F, lArray0_text_70, 255L);
  }
  sglEndStaticSequence();
  /* Static sequence for Object: CounterBox_1, Type: container, OID: 5c38709c-fe1b-4dbd-9ebd-b27cdc719e87 */
  aol_symbology_layer_stc15 = sglBeginStaticSequence(167.89001F, 170.091F, 255.926F, 221.641F);

  /* Object: CounterBackground_1, Type: shape, OID: 7b81eaa1-3eb5-4a57-af47-779724842564 */
  {
    /* color object part */
    sglIndexColori(1L);
    sglDisable(SGL_MODULATE);
    sglDisable(SGL_POLYGON_SMOOTH);
    sglTransparency8(255L);
    sglDisable(SGL_TEXTURE_2D);
    sglDisable(SGL_GRADIENT);
    /* fill object part */
    sglDisable(SGL_TESSELLATION);
    sglBegin(SGL_POLYGON);
    sglVertex2f(173.89F, 215.641F);
    sglVertex2f(234.931F, 215.612F);
    sglVertex2f(249.926F, 196.602F);
    sglVertex2f(234.931F, 176.091F);
    sglVertex2f(173.89F, 176.798F);
    sglEnd();
    /* outline object part */
    sglIndexColori(41L);
    sglIndexHaloColori(-1L);
    sglIndexLineWidthi(1L);
    sglIndexLineStipplei(0L);
    sglDisable(SGL_LINE_HALOING);
    sglSetLineCaps(SGL_ROUNDED_CAPS);
    sglBegin(SGL_LINE_LOOP);
    sglVertex2f(173.89F, 215.641F);
    sglVertex2f(234.931F, 215.612F);
    sglVertex2f(249.926F, 196.602F);
    sglVertex2f(234.931F, 176.091F);
    sglVertex2f(173.89F, 176.798F);
    sglEnd();
  }
  sglEndStaticSequence();
  /* Static sequence for Object: ReferenceLine, Type: container, OID: 8fd9ff5f-2b20-49d4-9b69-7816547b9e0d */
  aol_symbology_layer_stc16 = sglBeginStaticSequence(-16.487015F, -6.352997F, 23.151993F, 6.0F);

  /* Object: IAS_REF_LINE, Type: container, OID: 3bc28184-da6c-4864-90f3-da24a4ab8dc0 */
  {

    /* Object: line_172, Type: line, OID: 32023109-d2ce-4641-8297-5bc8b42a5209 */
    {
      /* outline object part */
      sglIndexColori(41L);
      sglIndexHaloColori(-1L);
      sglIndexLineWidthi(5L);
      sglIndexLineStipplei(0L);
      sglDisable(SGL_LINE_HALOING);
      sglSetLineCaps(SGL_ROUNDED_CAPS);
      sglTransparency8(255L);
      sglBegin(SGL_LINES);
      sglVertex2f(-10.487F, -0.353F);
      sglVertex2f(17.152F, 0.0F);
      sglEnd();
    }
  }
  sglEndStaticSequence();
  /* Static sequence for Object: begin_moving_5, Type: container, OID: e6e17c2a-4923-4b64-96ce-8f299f0d4587 */
  aol_symbology_layer_stc17 = sglBeginStaticSequence(-195.375F, 184.39299F, -176.515F, 225.821F);

  /* Object: FULL_SELIASBUG, Type: container, OID: 24a4ecb5-5909-464d-b0c4-13fc2eb182c5 */
  {
    sglPushMatrixAndTranslate(-185.945F, 205.107F);

    /* Object: shape_2, Type: shape, OID: f1f84c5f-a585-4af8-be92-ff6be15e5f5f */
    {
      /* color object part */
      sglIndexColori(16L);
      sglDisable(SGL_MODULATE);
      sglDisable(SGL_POLYGON_SMOOTH);
      sglTransparency8(255L);
      sglDisable(SGL_TEXTURE_2D);
      sglDisable(SGL_GRADIENT);
      /* fill object part */
      sglDisable(SGL_TESSELLATION);
      sglBegin(SGL_POLYGON);
      sglVertex2f(3.43F, 14.714F);
      sglVertex2f(-3.43F, 14.714F);
      sglVertex2f(-3.43F, 0.0F);
      sglVertex2f(3.43F, 2.457F);
      sglEnd();
    }

    /* Object: shape_3, Type: shape, OID: d580a47c-139d-424b-b8dc-0de4e0a2b1dd */
    {
      /* color object part */
      /* fill object part */
      sglBegin(SGL_POLYGON);
      sglVertex2f(3.43F, -14.714F);
      sglVertex2f(-3.43F, -14.714F);
      sglVertex2f(-3.43F, 0.0F);
      sglVertex2f(3.43F, -2.472F);
      sglEnd();
    }
    sglPopMatrixAndTranslate();
  }
  sglEndStaticSequence();
}

void aol_symbology_layer_draw(aol_typ_symbology_layer *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, 0L)) {

    /* Object: symbology_layer, Type: layer, OID: 1e511ea2-f6ce-4291-9e1a-91e87faff083 */
    {
      sglPushMatrixAndTranslate(333.0F, 310.0F);

      /* Object: PFD, Type: container, OID: 20541c13-610c-48e8-aaa8-ebf2553cd13a */
      {
        sglPushMatrixAndTranslate(1.0F, 0.0F);

        /* Object: ADI, Type: container, OID: edbdd276-6bdb-4456-bc81-2738054a05e0 */
        {
          sglPushMatrixAndTranslate(30.123F, -242.425F);

          /* Object: ADI_masked_parts, Type: container, OID: cb3d839a-a363-4199-88d2-2f7edb74e725 */
          {
            SGLuint32 lMask_MaskOutlinerADI_001 = SGL_NO_MASK;
            sglPushMatrixAndTranslate(-29.403F, 241.792F);

            /* Object: MaskOutlinerADI_001, Type: stencil, OID: efce174a-fd4f-4c2a-83b8-ab6c0fe55be7 */
            {
              sglDisable(SGL_TESSELLATION);
              lMask_MaskOutlinerADI_001 = sglAllocateMaskID(SGL_TYPE_STENCIL);
              sglBegin(SGLuint32_to_uint8(lMask_MaskOutlinerADI_001));
              sglVertex2f(-170.538F, 98.384F);
              sgluArcSegment(SGL_TRUE, 120.002F);
              sglVertex2f(168.362F, 98.384F);
              sglVertex2f(168.362F, -94.716F);
              sgluArcSegment(SGL_TRUE, 120.002F);
              sglVertex2f(-170.538F, -94.716F);
              sglEnd();
            }

            /* Object: SkyEarthAndScales, Type: container, OID: a08f5f6d-09ae-47e6-8a6b-707af9c43b73 */
            {
              sglPushMatrix();
              sglRotatef(aol_symbology_layer_G_PN_ROLL_ANGLE(pContext));

              /* Object: SKY_EARTH, Type: container, OID: 6ed53397-9eca-49f6-a26a-12ff5ce4cc3f */
              {
                sglPushMatrixAndTranslate(0.0F, aol_symbology_layer_G_PN_PITCH_ANGLE(pContext));

                /* Object: SkyRect, Type: rectangle, OID: ba4677cd-ca59-4e79-bfb8-eadbb8ebe62c */
                {
                  sglSetActiveMasks(lMask_MaskOutlinerADI_001);
                  /* color object part */
                  sglIndexColori(18L);
                  sglDisable(SGL_MODULATE);
                  sglDisable(SGL_POLYGON_SMOOTH);
                  sglTransparency8(255L);
                  sglDisable(SGL_TEXTURE_2D);
                  sglDisable(SGL_GRADIENT);
                  /* fill object part */
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(-375.953F, 0.0F);
                  sglVertex2f(375.953F, 0.0F);
                  sglVertex2f(375.953F, 392.361F);
                  sglVertex2f(-375.953F, 392.361F);
                  sglEnd();
                }

                /* Object: EarthRect, Type: rectangle, OID: 125a0d1d-2b38-4396-925b-e20bebd48d79 */
                {
                  /* color object part */
                  sglIndexColori(33L);
                  sglEnable(SGL_POLYGON_SMOOTH);
                  /* fill object part */
                  sglBegin(SGL_POLYGON);
                  sglVertex2f(-375.953F, -392.361F);
                  sglVertex2f(375.953F, -392.361F);
                  sglVertex2f(375.953F, 0.0F);
                  sglVertex2f(-375.953F, 0.0F);
                  sglEnd();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: ScaleAndAlarms, Type: container, OID: e97ffa67-a488-441a-964c-538bc8b467a3 */
              {

                /* Object: PitchScale, Type: container, OID: 0ec3a91a-30a7-4260-888c-e16cdc8a8488 */
                {
                  sglPushMatrixAndTranslate(0.0F, aol_symbology_layer_G_PN_PITCH_ANGLE(pContext));

                  /* Object: SCALE_DAN_F00, Type: container, OID: 27fb21e4-15ae-4a72-8389-ae365552db5c */
                  {
                    sglCallStaticSequence(aol_symbology_layer_stc0);
                  }
                  sglPopMatrixAndTranslate();
                }

                /* Object: HighWarning, Type: container, OID: 711db25a-ea73-40fc-9cf5-48a2a7770c3e */
                {
                  sglPushMatrixAndTranslate(0.0F, 181.467F);

                  /* Object: HIGHWARNING_DAN, Type: container, OID: 586e0ebe-6c8d-4eb7-9084-5e4f3ba76ee7 */
                  {
                    sglPushMatrixAndTranslate(0.0F, aol_symbology_layer_G_PN_PITCH_ANGLE(pContext));

                    /* Object: begin_moving_1, Type: container, OID: c41cd992-a3d1-4a48-9012-091bf5febe73 */
                    {
                      sglSetActiveMasks(lMask_MaskOutlinerADI_001);
                      sglPushMatrixAndTranslate(0.0F, 14.714F);
                      sglCallStaticSequence(aol_symbology_layer_stc1);
                      sglPopMatrixAndTranslate();
                    }
                    sglPopMatrixAndTranslate();
                  }
                  sglPopMatrixAndTranslate();
                }

                /* Object: HighAlarm, Type: container, OID: bc920bf8-9684-4f9e-a671-bb1e89ed3d9d */
                {
                  sglPushMatrixAndTranslate(0.0F, 269.748F);

                  /* Object: HIGHALARM_DAN, Type: container, OID: 0d782c29-589e-40ef-8f1b-4957d4da1ff6 */
                  {
                    sglPushMatrixAndTranslate(0.0F, aol_symbology_layer_G_PN_PITCH_ANGLE(pContext));

                    /* Object: begin_moving_2, Type: container, OID: 43f31cba-c89b-4886-859b-bff0e14d074b */
                    {
                      sglSetActiveMasks(lMask_MaskOutlinerADI_001);
                      sglPushMatrixAndTranslate(0.0F, 40.462F);
                      sglCallStaticSequence(aol_symbology_layer_stc2);
                      sglPopMatrixAndTranslate();
                    }
                    sglPopMatrixAndTranslate();
                  }
                  sglPopMatrixAndTranslate();
                }

                /* Object: LowWarning, Type: container, OID: 7d762d69-5f27-4d1f-bd8f-2572f22219c4 */
                {
                  sglPushMatrixAndTranslate(0.0F, -181.467F);

                  /* Object: LOWWARNING_DAN, Type: container, OID: 022b3f33-42c9-48c2-b222-4dcdfd7d3712 */
                  {
                    sglPushMatrixAndTranslate(0.0F, aol_symbology_layer_G_PN_PITCH_ANGLE(pContext));

                    /* Object: begin_moving_3, Type: container, OID: 78cf04ed-ca57-409d-87d4-af6171a295e9 */
                    {
                      sglSetActiveMasks(lMask_MaskOutlinerADI_001);
                      sglPushMatrixAndTranslate(0.0F, -14.714F);
                      sglCallStaticSequence(aol_symbology_layer_stc3);
                      sglPopMatrixAndTranslate();
                    }
                    sglPopMatrixAndTranslate();
                  }
                  sglPopMatrixAndTranslate();
                }

                /* Object: LowAlarm, Type: container, OID: 5e3d493c-e8ed-4923-b1f7-50874f2a0dc1 */
                {
                  sglPushMatrixAndTranslate(0.0F, -269.748F);

                  /* Object: LOWALARM_DAN, Type: container, OID: 0549bfb4-523a-426d-8d59-be1aa470ccb2 */
                  {
                    sglPushMatrixAndTranslate(0.0F, aol_symbology_layer_G_PN_PITCH_ANGLE(pContext));

                    /* Object: begin_moving_4, Type: container, OID: c583e163-9526-4e80-96f2-28106825490b */
                    {
                      sglSetActiveMasks(lMask_MaskOutlinerADI_001);
                      sglPushMatrixAndTranslate(0.0F, -40.462F);
                      sglCallStaticSequence(aol_symbology_layer_stc4);
                      sglPopMatrixAndTranslate();
                    }
                    sglPopMatrixAndTranslate();
                  }
                  sglPopMatrixAndTranslate();
                }
              }

              /* Object: BugReference, Type: container, OID: 91017c9b-4cc7-4582-b9e9-72396866927a */
              {
                sglSetActiveMasks(lMask_MaskOutlinerADI_001);
                sglCallStaticSequence(aol_symbology_layer_stc5);
              }
              sglPopMatrix();
            }

            /* Object: lunula, Type: container, OID: 76cd939a-1559-464c-8ca1-b7f191ca84d2 */
            {
              sglPushMatrix();
              sglRotatef(aol_symbology_layer_G_PN_ROLL_ANGLE(pContext));

              /* Object: TOP_Lunula, Type: rectangle, OID: 0093e3a7-0b1c-4a3b-9309-4df2531ab0ec */
              {
                sglSetActiveMasks(lMask_MaskOutlinerADI_001);
                /* color object part */
                sglIndexColori(18L);
                sglDisable(SGL_MODULATE);
                sglEnable(SGL_POLYGON_SMOOTH);
                sglTransparency8(255L);
                sglDisable(SGL_TEXTURE_2D);
                sglDisable(SGL_GRADIENT);
                /* fill object part */
                sglDisable(SGL_TESSELLATION);
                sglBegin(SGL_POLYGON);
                sglVertex2f(160.365F, 161.849F);
                sglVertex2f(-153.896F, 161.849F);
                sglVertex2f(-153.896F, 199.437F);
                sglVertex2f(160.365F, 199.437F);
                sglEnd();
              }

              /* Object: BOT_Lunula, Type: rectangle, OID: 01a7d1d9-328e-48c1-8d28-65cd8ef43aa4 */
              {
                /* color object part */
                sglIndexColori(33L);
                /* fill object part */
                sglBegin(SGL_POLYGON);
                sglVertex2f(159.365F, -195.768F);
                sglVertex2f(-159.777F, -195.768F);
                sglVertex2f(-159.777F, -161.849F);
                sglVertex2f(159.365F, -161.849F);
                sglEnd();
              }
              sglPopMatrix();
            }

            /* Object: RollIndex, Type: container, OID: ea40417d-97c3-488f-b092-88ee233e4570 */
            {
              sglPushMatrix();
              sglRotatef(aol_symbology_layer_G_PN_ROLL_ANGLE(pContext));

              /* Object: shape, Type: shape, OID: f13c137c-45b4-483b-8b6d-e707138a0599 */
              {
                /* outline object part */
                sglIndexColori(41L);
                sglIndexHaloColori(-1L);
                sglIndexLineWidthi(2L);
                sglIndexLineStipplei(0L);
                sglEnable(SGL_LINE_HALOING);
                sglSetLineCaps(SGL_ROUNDED_CAPS);
                sglBegin(SGL_LINE_LOOP);
                sglVertex2f(-0.588F, 193.728F);
                sglVertex2f(-10.389F, 171.658F);
                sglVertex2f(9.213F, 171.658F);
                sglEnd();
              }
              sglPopMatrix();
            }
            sglFreeMaskID(lMask_MaskOutlinerADI_001);
            sglPopMatrixAndTranslate();
          }

          /* Object: RollFix, Type: container, OID: 9aee87cc-a752-4514-bd78-e2acf16be4a5 */
          {

            /* Object: shape_1, Type: shape, OID: db5c4f85-5589-4323-9e9d-b015fbea7db0 */
            {
              /* color object part */
              sglIndexColori(1L);
              /* fill object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-29.991F, 438.954F);
              sglVertex2f(-20.19F, 461.024F);
              sglVertex2f(-39.792F, 461.024F);
              sglEnd();
              /* outline object part */
              sglIndexColori(41L);
              sglBegin(SGL_LINE_LOOP);
              sglVertex2f(-29.991F, 438.954F);
              sglVertex2f(-20.19F, 461.024F);
              sglVertex2f(-39.792F, 461.024F);
              sglEnd();
            }

            /* Object: RollGraduations, Type: container, OID: bf7cd3de-4843-46d9-a74e-91004b67a88d */
            {

              /* Object: group, Type: container, OID: c7f6e0c5-1a3f-48a0-9a3c-bcddacc01a68 */
              {

                /* Object: Ind_45, Type: shape, OID: 21700b90-77c0-440e-a47c-9e03a2f9fe97 */
                {
                  /* outline object part */
                  sglBegin(SGL_LINE_LOOP);
                  sglVertex2f(-170.45F, 381.948F);
                  sglVertex2f(-173.699F, 397.206F);
                  sglVertex2f(-185.196F, 385.7F);
                  sglEnd();
                }
              }

              /* Object: group_1, Type: container, OID: 4fa5a091-8237-4468-8ad5-6f112cb82b24 */
              {
                sglPushMatrixAndTranslate(295.913F, 0.5F);

                /* Object: Ind45, Type: shape, OID: e0b59922-1ec5-44c4-802b-ad793fa74090 */
                {
                  /* outline object part */
                  sglBegin(SGL_LINE_LOOP);
                  sglVertex2f(-185.196F, 381.948F);
                  sglVertex2f(-181.946F, 397.206F);
                  sglVertex2f(-170.45F, 385.7F);
                  sglEnd();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: group_2, Type: container, OID: 853e0255-64d1-48d4-bea3-cb3cb1348a8a */
              {
                sglPushMatrixAndTranslate(-0.75F, 0.628F);

                /* Object: Ind_30, Type: line, OID: 5869d6df-699b-4ef1-a09d-efbd1dca35cf */
                {
                  /* outline object part */
                  sglIndexLineWidthi(3L);
                  sglBegin(SGL_LINES);
                  sglVertex2f(-129.212F, 413.465F);
                  sglVertex2f(-136.46F, 426.472F);
                  sglEnd();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: group_3, Type: container, OID: 3034bc82-4824-436e-bbbc-8d2ec400f072 */
              {
                sglPushMatrixAndTranslate(206.062F, -0.123F);

                /* Object: Ind30, Type: line, OID: 39441dfc-ad1b-4800-b70b-4ad99156b6e5 */
                {
                  /* outline object part */
                  sglBegin(SGL_LINES);
                  sglVertex2f(-136.46F, 413.465F);
                  sglVertex2f(-129.212F, 426.472F);
                  sglEnd();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: group_4, Type: container, OID: d6ba8695-1416-4260-8d77-2564d13c1dc7 */
              {

                /* Object: line_69, Type: line, OID: 8714d235-689f-42b9-9e88-fd6248ae2e45 */
                {
                  /* outline object part */
                  sglIndexLineWidthi(1L);
                  sglBegin(SGL_LINES);
                  sglVertex2f(-97.721F, 427.972F);
                  sglVertex2f(-101.47F, 437.227F);
                }
              }

              /* Object: group_5, Type: container, OID: 2e97a657-ec56-417f-856a-ea89d3ce10a8 */
              {

                /* Object: line_70, Type: line, OID: f06e1bc1-6be4-4a51-bb66-fb14f81dd906 */
                {
                  /* outline object part */
                  sglVertex2f(-64.481F, 436.727F);
                  sglVertex2f(-65.981F, 445.732F);
                  sglEnd();
                }
              }

              /* Object: group_6, Type: container, OID: 1d4967e9-8ce3-4f34-9d1e-0c6d77d9dd6e */
              {
                sglPushMatrixAndTranslate(139.581F, 0.5F);

                /* Object: line_71, Type: line, OID: dc5e414d-6435-4378-a4ad-9dc245dac25a */
                {
                  /* outline object part */
                  sglBegin(SGL_LINES);
                  sglVertex2f(-101.47F, 427.972F);
                  sglVertex2f(-97.721F, 437.227F);
                  sglEnd();
                }
                sglPopMatrixAndTranslate();
              }

              /* Object: group_7, Type: container, OID: a312e12d-0622-4d97-9eb0-6286bc4992a2 */
              {
                sglPushMatrixAndTranslate(71.102F, 0.75F);

                /* Object: line_72, Type: line, OID: b81d9646-5fcb-41d3-b29e-83a1d1fa8df4 */
                {
                  /* outline object part */
                  sglBegin(SGL_LINES);
                  sglVertex2f(-65.981F, 436.727F);
                  sglVertex2f(-64.481F, 445.732F);
                  sglEnd();
                }
                sglPopMatrixAndTranslate();
              }
            }
          }
          sglPopMatrixAndTranslate();
        }

        /* Object: Altitude, Type: container, OID: eff212d0-e6c3-4c8c-ac38-eec1a8235c5e */
        {
          SGLuint32 lMask_TOP_ALTI_001 = SGL_NO_MASK;
          SGLuint32 lMask_BOT_ALTI_001 = SGL_NO_MASK;
          sglPushMatrixAndTranslate(-43.585F, -232.797F);

          /* Object: TOP_ALTI_001, Type: clipPlane, OID: 129dc753-9251-42aa-a231-b01953314aae */
          {
            lMask_TOP_ALTI_001 = sglAllocateMaskID(SGL_TYPE_CLIP_PLANE);
            sglClipPlane(lMask_TOP_ALTI_001, -42.987F, 430.597F, 0.0F, SGL_FALSE);
          }

          /* Object: BOT_ALTI_001, Type: clipPlane, OID: 8d7a5550-c31c-4c62-9215-ca841805d472 */
          {
            lMask_BOT_ALTI_001 = sglAllocateMaskID(SGL_TYPE_CLIP_PLANE);
            sglClipPlane(lMask_BOT_ALTI_001, -50.985F, 35.312F, 179.99F, SGL_FALSE);
          }

          /* Object: ClippedBackground, Type: container, OID: b161065e-70da-45b1-ba04-6e7435c16466 */
          {
            SGLuint32 lMask_clip_box_001 = SGL_NO_MASK;
            sglPushMatrixAndTranslate(254.827F, 232.474F);

            /* Object: clip_box_001, Type: clipBox, OID: 7c93c290-1e6a-48b0-bbc1-de187deaefc9 */
            {
              lMask_clip_box_001 = sglAllocateMaskID(SGL_TYPE_CLIP_BOX);
              sglClipBox(lMask_clip_box_001, SGL_VISIBLE_OUTSIDE, 11.095F, 16.675F, 77.487F, -20.167F);
            }

            /* Object: rectangle, Type: rectangle, OID: e70955db-d016-431f-a910-1b9a462d2710 */
            {
              sglSetActiveMasks(lMask_BOT_ALTI_001|lMask_TOP_ALTI_001|lMask_clip_box_001);
              /* color object part */
              sglIndexColori(21L);
              sglDisable(SGL_POLYGON_SMOOTH);
              /* fill object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(0.417F, -196.259F);
              sglVertex2f(78.825F, -196.259F);
              sglVertex2f(78.825F, 197.161F);
              sglVertex2f(0.417F, 197.161F);
              sglEnd();
            }
            sglFreeMaskID(lMask_clip_box_001);
            sglPopMatrixAndTranslate();
          }

          /* Object: RADALT_Group, Type: container, OID: 32084191-5f0b-45c1-bab4-50bc4ec33b10 */
          {
            SGLuint32 lMask_clip_box_001_1 = SGL_NO_MASK;

            /* Object: clip_box_001_1, Type: clipBox, OID: 6d2756dc-0929-4143-b107-4c4a9d7ae397 */
            {
              lMask_clip_box_001_1 = sglAllocateMaskID(SGL_TYPE_CLIP_BOX);
              sglClipBox(lMask_clip_box_001_1, SGL_VISIBLE_OUTSIDE, 267.49F, 250.915F, 333.882F, 214.072F);
            }

            /* Object: RADALT_Analog, Type: functionalTranslate, OID: c3005c07-a608-48e3-b4b4-80c0aba35fcd */
            {
              sglPushMatrixAndTranslate(0.0F, (SGLfloat_le(aol_symbology_layer_G_PN_ALTI(pContext), 0.0F) ? 0.0F : (SGLfloat_ge(aol_symbology_layer_G_PN_ALTI(pContext), 5500.0F) ? -40.08F : SGLfloat_mul(aol_symbology_layer_G_PN_ALTI(pContext), -0.00728727272727F))));

              /* Object: rectangle_1, Type: rectangle, OID: 9dd11082-cacb-4e32-a3cf-6cb0666ca1b4 */
              {
                sglSetActiveMasks(lMask_BOT_ALTI_001|lMask_TOP_ALTI_001|lMask_clip_box_001_1);
                /* color object part */
                sglIndexColori(33L);
                sglEnable(SGL_POLYGON_SMOOTH);
                /* fill object part */
                sglBegin(SGL_POLYGON);
                sglVertex2f(256.454F, 232.67F);
                sglVertex2f(333.49F, 232.67F);
                sglVertex2f(333.49F, 37.274F);
                sglVertex2f(256.454F, 37.274F);
                sglEnd();
              }
              sglPopMatrixAndTranslate();
            }
            sglFreeMaskID(lMask_clip_box_001_1);
          }

          /* Object: AltiScale, Type: functionalTranslate, OID: 2eb17003-4a6a-4103-8f18-66faf537ecc4 */
          {
            sglPushMatrixAndTranslate(0.0F, SGLfloat_mul(aol_symbology_layer_G_PN_ALTI(pContext), -0.073F));

            /* Object: lines, Type: container, OID: 385d301b-5209-446c-8df2-f369f88c5797 */
            {
              sglCallStaticSequence(aol_symbology_layer_stc6);
            }

            /* Object: texts, Type: container, OID: 6735061e-83bc-41b0-a081-b5a666dd730d */
            {
              sglSetActiveMasks(lMask_BOT_ALTI_001|lMask_TOP_ALTI_001);
              sglPushMatrixAndTranslate(-9.801F, 0.0F);
              sglCallStaticSequence(aol_symbology_layer_stc7);
              sglPopMatrixAndTranslate();
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: Counter, Type: container, OID: ae2eef66-07a3-4ce4-a35d-85ff9300337c */
          {

            /* Object: CounterBox, Type: container, OID: 13bec8d9-95b7-4f13-a33d-4e55244f506f */
            {
              sglSetActiveMasks(lMask_BOT_ALTI_001|lMask_TOP_ALTI_001);
              sglPushMatrixAndTranslate(309.002F, 231.12F);
              sglCallStaticSequence(aol_symbology_layer_stc8);
              sglPopMatrixAndTranslate();
            }

            /* Object: CounterHundreds, Type: container, OID: 9874f627-9d1a-4470-b34f-8440cb27b7b6 */
            {
              SGLuint32 lMask_clip_box = SGL_NO_MASK;

              /* Object: clip_box, Type: clipBox, OID: 65bb2084-bb29-4ed4-aee6-1b793cf2ffbe */
              {
                lMask_clip_box = sglAllocateMaskID(SGL_TYPE_CLIP_BOX);
                sglClipBox(lMask_clip_box, SGL_VISIBLE_OUTSIDE, 329.584F, 246.795F, 369.582F, 215.798F);
              }

              /* Object: AltiCount1000, Type: bifont, OID: 7f8a0e9d-8a64-478f-8f4b-202ccc50ba85 */
              {
                sglSetActiveMasks(lMask_BOT_ALTI_001|lMask_TOP_ALTI_001|lMask_clip_box);
                sglIndexColori(11L);
                sglIndexHaloColori(-1L);
                sglIndexFontLineWidthi(2L);
                sglIndexFonti(0L);
                sglDisable(SGL_LINE_HALOING);
                sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
                sglSetSecondFontAttributes(11L, 0L, 2L);
                {
                  sgl_numeric_format lFormat;
                  lFormat.l_integralPart = 5L;
                  lFormat.l_fractionalPart = 0L;
                  lFormat.l_secondFontPos = 1L;
                  lFormat.b_separator = 46U;
                  lFormat.b_leadingZeros = SGL_TRUE;
                  lFormat.l_displaySign = SGL_SIGN_NEVER;
                  sgluWriteFloat(323.434F, 231.797F, aol_symbology_layer_G_PN_ALTI(pContext), &lFormat);
                }
              }
              sglFreeMaskID(lMask_clip_box);
            }

            /* Object: CounterUnits, Type: bifont, OID: 5eb12fa7-413e-4c15-bdb6-0d9f0baec3e4 */
            {
              sgl_numeric_format lFormat;
              lFormat.l_integralPart = 2L;
              lFormat.l_fractionalPart = 0L;
              lFormat.l_secondFontPos = 1L;
              lFormat.b_separator = 46U;
              lFormat.b_leadingZeros = SGL_TRUE;
              lFormat.l_displaySign = SGL_SIGN_NEVER;
              sgluWriteFloat(350.583F, 230.796F, aol_symbology_layer_G_PN_ALTI(pContext), &lFormat);
            }
          }

          /* Object: Outline, Type: container, OID: 12cb0ba7-92dd-4d6b-8209-15acb728e256 */
          {
            sglPushMatrixAndTranslate(254.827F, 232.474F);
            sglCallStaticSequence(aol_symbology_layer_stc9);
            sglPopMatrixAndTranslate();
          }

          /* Object: AltitudeSelectedBug, Type: shape, OID: cc5a57f0-c69e-4d64-8f1f-f12d5358e68b */
          {
            sglSetActiveMasks(lMask_BOT_ALTI_001|lMask_TOP_ALTI_001);
            /* color object part */
            sglIndexColori(16L);
            sglDisable(SGL_MODULATE);
            sglEnable(SGL_POLYGON_SMOOTH);
            sglTransparency8(255L);
            sglDisable(SGL_TEXTURE_2D);
            sglDisable(SGL_GRADIENT);
            /* fill object part */
            sglDisable(SGL_TESSELLATION);
            sglBegin(SGL_POLYGON);
            sglVertex2f(250.279F, 232.081F);
            sglVertex2f(242.635F, 223.253F);
            sglVertex2f(242.635F, 214.425F);
            sglVertex2f(252.338F, 214.425F);
            sglVertex2f(252.044F, 249.738F);
            sglVertex2f(242.635F, 249.738F);
            sglVertex2f(242.635F, 240.615F);
            sglVertex2f(250.867F, 232.081F);
            sglEnd();
            /* outline object part */
            sglIndexColori(17L);
            sglIndexHaloColori(-1L);
            sglIndexLineWidthi(0L);
            sglIndexLineStipplei(0L);
            sglDisable(SGL_LINE_HALOING);
            sglSetLineCaps(SGL_ROUNDED_CAPS);
            sglBegin(SGL_LINE_LOOP);
            sglVertex2f(250.279F, 232.081F);
            sglVertex2f(242.635F, 223.253F);
            sglVertex2f(242.635F, 214.425F);
            sglVertex2f(252.338F, 214.425F);
            sglVertex2f(252.044F, 249.738F);
            sglVertex2f(242.635F, 249.738F);
            sglVertex2f(242.635F, 240.615F);
            sglVertex2f(250.867F, 232.081F);
            sglEnd();
          }
          sglFreeMaskID(lMask_TOP_ALTI_001|lMask_BOT_ALTI_001);
          sglPopMatrixAndTranslate();
        }

        /* Object: Airspeed, Type: container, OID: 4d6ba6f4-0bb6-4385-80cb-40d8eeb852d3 */
        {
          SGLuint32 lMask_TOP_IAS_001 = SGL_NO_MASK;
          SGLuint32 lMask_BOT_IAS_001 = SGL_NO_MASK;
          sglPushMatrixAndTranslate(37.239F, -242.783F);

          /* Object: TOP_IAS_001, Type: clipPlane, OID: 6824c463-f9e1-480a-bffe-fc6f33f5d6e0 */
          {
            lMask_TOP_IAS_001 = sglAllocateMaskID(SGL_TYPE_CLIP_PLANE);
            sglClipPlane(lMask_TOP_IAS_001, -162.952F, 440.425F, 0.0F, SGL_FALSE);
          }

          /* Object: BOT_IAS_001, Type: clipPlane, OID: 948cd161-b42b-42c6-82f2-6fe5188f4e70 */
          {
            lMask_BOT_IAS_001 = sglAllocateMaskID(SGL_TYPE_CLIP_PLANE);
            sglClipPlane(lMask_BOT_IAS_001, -112.967F, 45.857F, 179.99F, SGL_FALSE);
          }

          /* Object: ClippedBackground_1, Type: container, OID: 8558a5ec-daff-4bb5-9432-dd55a11e1dac */
          {
            SGLuint32 lMask_clip_box_001_2 = SGL_NO_MASK;
            sglPushMatrixAndTranslate(-124.963F, 11.006F);

            /* Object: clip_box_001_2, Type: clipBox, OID: 310118af-1d13-4302-8ad3-8e90fe4d451b */
            {
              lMask_clip_box_001_2 = sglAllocateMaskID(SGL_TYPE_CLIP_BOX);
              sglClipBox(lMask_clip_box_001_2, SGL_VISIBLE_OUTSIDE, -144.957F, 212.11F, -211.938F, 250.13F);
            }

            /* Object: background, Type: rectangle, OID: 8ff4a4d3-9b4f-4677-aa36-ab3811269d61 */
            {
              sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001|lMask_clip_box_001_2);
              /* color object part */
              sglIndexColori(21L);
              /* fill object part */
              sglBegin(SGL_POLYGON);
              sglVertex2f(-123.317F, 36.019F);
              sglVertex2f(-208.586F, 36.019F);
              sglVertex2f(-208.586F, 428.379F);
              sglVertex2f(-123.317F, 428.379F);
              sglEnd();
            }
            sglFreeMaskID(lMask_clip_box_001_2);
            sglPopMatrixAndTranslate();
          }

          /* Object: Outline_1, Type: container, OID: 1c56295d-2211-48f9-a8fa-db85342bd84e */
          {
            sglPushMatrixAndTranslate(-288.915F, 243.205F);
            sglCallStaticSequence(aol_symbology_layer_stc10);
            sglPopMatrixAndTranslate();
          }

          /* Object: AirspeedScale, Type: functionalTranslate, OID: ad607e50-6887-442e-bf6c-75f1feec9721 */
          {
            sglPushMatrixAndTranslate(0.0F, SGLfloat_mul(aol_symbology_layer_G_PN_AIRSPEED(pContext), -0.90005F));

            /* Object: lines1, Type: container, OID: 869a7410-f7fb-47a3-8004-031f02fa60ba */
            {
              sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001);
              sglCallStaticSequence(aol_symbology_layer_stc11);
            }

            /* Object: lines2, Type: container, OID: 3c79cfc6-7852-42b2-83e0-9fb842e5d8c2 */
            {
              sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001);
              sglPushMatrixAndTranslate(0.0F, 1147.655F);
              sglCallStaticSequence(aol_symbology_layer_stc12);
              sglPopMatrixAndTranslate();
            }

            /* Object: numbers1, Type: container, OID: 3e815ecb-ec99-4524-9f69-fa0f7c12c532 */
            {
              sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001);
              sglCallStaticSequence(aol_symbology_layer_stc13);
            }

            /* Object: numbers2, Type: container, OID: 376c0fd6-e5a6-48b4-b865-1d7bdea90c40 */
            {
              sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001);
              sglPushMatrixAndTranslate(0.0F, 1147.655F);
              sglCallStaticSequence(aol_symbology_layer_stc14);
              sglPopMatrixAndTranslate();
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: CounterBox_1, Type: container, OID: 5c38709c-fe1b-4dbd-9ebd-b27cdc719e87 */
          {
            sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001);
            sglPushMatrixAndTranslate(-506.851F, 47.024F);
            sglCallStaticSequence(aol_symbology_layer_stc15);
            sglPopMatrixAndTranslate();
          }

          /* Object: ReferenceLine, Type: container, OID: 8fd9ff5f-2b20-49d4-9b69-7816547b9e0d */
          {
            sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001);
            sglPushMatrixAndTranslate(-247.437F, 242.479F);
            sglCallStaticSequence(aol_symbology_layer_stc16);
            sglPopMatrixAndTranslate();
          }

          /* Object: AirspeedSelectedBug, Type: functionalTranslate, OID: db0d2b19-d9b1-4335-821f-7d1678ec7dc3 */
          {
            sglPushMatrixAndTranslate(-56.89F, 37.019F);

            /* Object: begin_moving_5, Type: container, OID: e6e17c2a-4923-4b64-96ce-8f299f0d4587 */
            {
              sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001);
              sglPushMatrixAndTranslate(-0.093F, 0.0F);
              sglCallStaticSequence(aol_symbology_layer_stc17);
              sglPopMatrixAndTranslate();
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: AirspeedTrend, Type: conditional, OID: 5de2ce95-c271-4522-b1de-5624d60ce326 */
          {
            sglPushMatrixAndTranslate(-256.101F, 243.612F);

            /* Object: UpArrow, Type: container, OID: dd9e3902-d52b-45d7-bf3c-dd60807c8939 */
            {
              SGLuint32 lMask_clip_plane_001 = SGL_NO_MASK;
              sglPushMatrixAndTranslate(0.0F, 1.957F);

              /* Object: clip_plane_001, Type: clipPlane, OID: f057d9a3-8033-4863-8ab4-911243991dbe */
              {
                lMask_clip_plane_001 = sglAllocateMaskID(SGL_TYPE_CLIP_PLANE);
                sglClipPlane(lMask_clip_plane_001, -30.991F, 0.574F, 180.0F, SGL_FALSE);
              }

              /* Object: translate_group, Type: functionalTranslate, OID: a1d320bc-6577-425c-9d97-5999edba63b9 */
              {

                /* Object: line_173, Type: line, OID: cdf30aaa-b615-4e09-ad71-cd40a16b9ba2 */
                {
                  sglSetActiveMasks(lMask_BOT_IAS_001|lMask_TOP_IAS_001|lMask_clip_plane_001);
                  /* outline object part */
                  sglIndexColori(11L);
                  sglIndexHaloColori(-1L);
                  sglIndexLineWidthi(1L);
                  sglIndexLineStipplei(0L);
                  sglDisable(SGL_LINE_HALOING);
                  sglSetLineCaps(SGL_ROUNDED_CAPS);
                  sglTransparency8(255L);
                  sglBegin(SGL_LINES);
                  sglVertex2f(0.0F, -2.163F);
                  sglVertex2f(4.881F, -16.818F);
                }

                /* Object: line_174, Type: line, OID: a5e660e2-4fd3-49d7-b65e-83328a7abc3c */
                {
                  /* outline object part */
                  sglVertex2f(0.0F, -2.163F);
                  sglVertex2f(-4.881F, -16.818F);
                }

                /* Object: line_175, Type: line, OID: 17a1c81a-45fb-40f9-bfa7-5fd7439a5f11 */
                {
                  /* outline object part */
                  sglVertex2f(0.0F, -2.163F);
                  sglVertex2f(0.0F, -270.92F);
                  sglEnd();
                }
              }
              sglFreeMaskID(lMask_clip_plane_001);
              sglPopMatrixAndTranslate();
            }
            sglPopMatrixAndTranslate();
          }

          /* Object: RollCount, Type: bifont, OID: 6d0cacca-0941-406a-acc8-bd43281af0e7 */
          {
            sglIndexFontLineWidthi(2L);
            sglIndexFonti(0L);
            sglEnable(SGL_LINE_HALOING);
            sglSetTextAlignment(SGL_ALIGN_CENTER, SGL_ALIGN_MIDDLE);
            sglSetSecondFontAttributes(11L, 0L, 2L);
            {
              sgl_numeric_format lFormat;
              lFormat.l_integralPart = 3L;
              lFormat.l_fractionalPart = 0L;
              lFormat.l_secondFontPos = 1L;
              lFormat.b_separator = 46U;
              lFormat.b_leadingZeros = SGL_TRUE;
              lFormat.l_displaySign = SGL_SIGN_NEVER;
              sgluWriteFloat(-299.735F, 243.779F, aol_symbology_layer_G_PN_AIRSPEED(pContext), &lFormat);
            }
          }
          sglFreeMaskID(lMask_TOP_IAS_001|lMask_BOT_IAS_001);
          sglPopMatrixAndTranslate();
        }
        sglPopMatrixAndTranslate();
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:53:48
 *********************************************************/

