/*********************************************************
 **
 ** File  aol_color_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:53:48
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sgfx
 *********************************************************/

#ifndef AOL_COLOR_TABLE_H
#define AOL_COLOR_TABLE_H

#include "sgl_types.h"

/* Color table definition */

#define aol_color_table_size 52UL

extern const sgl_color aol_color_table[aol_color_table_size];

#define aol_color_table_background_index 1UL

#endif /* AOL_COLOR_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:53:48
 *********************************************************/

