/*********************************************************
 **
 ** File  aol_static_sequences.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.7 (build i2)
 **
 ** Date of generation: 2018-02-08T18:53:48
 ** Command line: ScadeDisplayKCG.exe -texturemax 1024 -static -map -outdir D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\code D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sct D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.swt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sst D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.stt D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sft D:\AnsysDev\6.7\Code\sdyoglx-6-7\examples\pfd\PrimaryFlightDisplay.sgfx
 *********************************************************/

#ifndef AOL_STATIC_SEQUENCES_H
#define AOL_STATIC_SEQUENCES_H

extern void aol_static_sequences(void);

#endif /* AOL_STATIC_SEQUENCES_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-02-08T18:53:48
 *********************************************************/
